document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<!--");
document.writeln("");
document.writeln("* { word-wrap: break-word; }");
document.writeln("*{padding:0;margin:0}");
document.writeln("* { word-wrap: break-word; }");
document.writeln("* {");
document.writeln("	PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln(".stylesqbz {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("-->");
document.writeln("</style>");
document.writeln("");
document.writeln("<body>");
document.writeln("  ");
document.writeln("");
document.writeln("  <table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #8bafaf\' bgcolor=#8bafaf height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 18pt\'><font color=\'#FFFF00\'>澳门玄机86957</font><font color=\'#FFFFFF\'>『一肖一码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\'cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");




document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		309期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		309期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">12</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		309期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		12.36.02</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		309期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		12.36.02.38.10.22</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		309期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		12.36.02.38.10.22.35.47.30 <br>");
document.writeln("		42.29.41.28.40.31.43.25.49</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		309期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		马</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		309期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马龙猴</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		309期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马龙猴羊鼠</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		309期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马龙猴羊鼠牛虎</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		309期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马龙猴羊鼠牛虎猪蛇</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");





document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		308期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		308期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">03</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		308期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		03.15.17</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		308期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		03.15.17.29.20.32</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		308期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		03.15.17.29.20.32.22.34.12<br>");
document.writeln("		24.26.38.19.31.18.30.04.40</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		308期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		<span style='background-color: #FFFF00\'>兔</span></font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		308期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		<span style='background-color: #FFFF00\'>兔</span>牛狗</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		308期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		<span style='background-color: #FFFF00\'>兔</span>牛狗猴马</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		308期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		<span style='background-color: #FFFF00\'>兔</span>牛狗猴马龙猪</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		308期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		<span style='background-color: #FFFF00\'>兔</span>牛狗猴马龙猪鼠虎</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");









document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		306期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		306期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">20</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:牛17</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		306期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		20.32.21</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:牛17</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		306期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		20.32.21.33.16.28</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:牛17</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		306期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		20.32.21.33.16.28.<span style='background-color: #FFFF00\'>17</span>.29.15<br>");
document.writeln("		27.13.25.12.24.11.23.10.22</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:牛17</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		306期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		狗</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:牛17</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		306期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		狗鸡虎</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:牛17</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		306期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		狗鸡虎<span style='background-color: #FFFF00\'>牛</span>兔</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:牛17</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		306期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		狗鸡虎<span style='background-color: #FFFF00\'>牛</span>兔蛇马</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:牛17</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		306期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		狗鸡虎<span style='background-color: #FFFF00\'>牛</span>兔蛇马羊猴</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:牛17</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");






document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		305期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		305期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">18</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠42</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		305期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		18.30.19</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠42</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		305期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		18.30.19.31.21.33</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠42</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		305期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		18.30.19.31.21.33.26.38.34<br>");
document.writeln("		46.11.23.20.32.25.37.24.36</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠42</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		305期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		<span style='background-color: #FFFF00\'>鼠</span></font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠42</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		305期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		<span style='background-color: #FFFF00\'>鼠</span>猪鸡</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠42</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		305期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		<span style='background-color: #FFFF00\'>鼠</span>猪鸡龙猴</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠42</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		305期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		<span style='background-color: #FFFF00\'>鼠</span>猪鸡龙猴羊狗</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠42</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		305期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		<span style='background-color: #FFFF00\'>鼠</span>猪鸡龙猴羊狗蛇马</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠42</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");




document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		304期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		304期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">01</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马48</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		304期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		01.13.20</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马48</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		304期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		01.13.20.32.35.47</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马48</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		304期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		01.13.20.32.35.47.27.39.05<br>");
document.writeln("		17.33.45.19.31.04.16.24.36</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马48</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		304期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		蛇</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马48</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		304期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		蛇狗羊</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马48</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		304期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		蛇狗羊兔牛</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马48</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		304期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		蛇狗羊兔牛鸡猪</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马48</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		304期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		蛇狗羊兔牛鸡猪龙<span style='background-color: #FFFF00\'>马</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马48</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");










document.writeln("   ");
document.writeln("   ");
document.writeln("");
document.writeln("			</table>	");
document.writeln("</body>");