document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<!--");
document.writeln("");
document.writeln("* { word-wrap: break-word; }");
document.writeln("*{padding:0;margin:0}");
document.writeln("* { word-wrap: break-word; }");
document.writeln("* {");
document.writeln("	PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln(".stylesqbz {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("-->");
document.writeln("</style>");
document.writeln("");
document.writeln("<body>");
document.writeln("  ");
document.writeln("");
document.writeln("  <table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #8bafaf\' bgcolor=#8bafaf height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 18pt\'><font color=\'#FFFF00\'>澳门玄机86957</font><font color=\'#FFFFFF\'>『一肖一码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\'cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");









document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		096期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		096期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">29</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		096期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		29.17.25</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		096期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		29.17.25.37.15.39</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		096期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		29.17.25.37.15.39.23.47.45<br>");
document.writeln("		21.43.31.12.48.08.20.06.42</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		096期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		牛</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		096期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛蛇兔</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		096期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛蛇兔羊鸡</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		096期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛蛇兔羊鸡猪马</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		096期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛蛇兔羊鸡猪马狗鼠</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");
document.writeln("   ");










document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		095期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		095期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">25</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		095期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		25.37.15</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		095期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		25.37.15.39.21.33</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		095期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		25.37.15.39.21.33.29.17.40<br>");
document.writeln("		28.06.42.11.47.22.46.08.44</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		095期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		蛇</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		095期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		蛇兔鸡</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		095期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		蛇兔鸡牛虎</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		095期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		蛇兔鸡牛虎鼠羊</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		095期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		蛇兔鸡牛虎鼠羊猴<span style='background-color: #FFFF00\'>狗</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");







document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		094期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		094期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">10</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		094期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		10.22.11</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		094期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		10.22.11.23.25.37</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		094期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		10.22.11.23.25.37.05.17.20<br>");
document.writeln("		32.21.<span style='background-color: #FFFF00\'>33</span>.03.15.14.26.30.42</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		094期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		猴</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		094期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		猴羊蛇</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		094期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		猴羊蛇牛狗</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		094期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		猴羊蛇牛狗<span style='background-color: #FFFF00\'>鸡</span>兔</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		094期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		猴羊蛇牛狗<span style='background-color: #FFFF00\'>鸡</span>兔龙鼠</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");











document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		093期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		093期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">30</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴10</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		093期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		30.42.14</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴10</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		093期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		30.42.14.26.11.23</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴10</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		093期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		30.42.14.26.11.23.07.19.<span style='background-color: #FFFF00\'>10</span><br>");
document.writeln("		22.20.32.13.25.03.15.05.17</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴10</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		093期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		鼠</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴10</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		093期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		鼠龙羊</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴10</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		093期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		鼠龙羊猪<span style='background-color: #FFFF00\'>猴</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴10</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		093期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		鼠龙羊猪<span style='background-color: #FFFF00\'>猴</span>狗蛇</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴10</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		093期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		鼠龙羊猪<span style='background-color: #FFFF00\'>猴</span>狗蛇兔牛</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴10</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");








document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		092期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		092期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">12</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		092期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		12.36.07</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		092期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		12.36.07.31.03.15</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		092期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		12.36.07.31.03.15.10.22.11<br>");
document.writeln("		23.20.32.05.17.04.16.13.25</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		092期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		马</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		092期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马猪<span style='background-color: #FFFF00\'>兔</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		092期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马猪<span style='background-color: #FFFF00\'>兔</span>猴羊</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		092期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马猪<span style='background-color: #FFFF00\'>兔</span>猴羊狗牛</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		092期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马猪<span style='background-color: #FFFF00\'>兔</span>猴羊狗牛虎蛇</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔39</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");






document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		090期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		090期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">04</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		090期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		04.16.12</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		090期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		04.16.12.36.13.25</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		090期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		04.16.12.36.13.25.11.23.02<br>");
document.writeln("		14.21.33.30.42.10.22.20.32</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		090期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		虎</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		090期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		虎马蛇</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		090期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		虎马蛇<span style='background-color: #FFFF00\'>羊</span>龙</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		090期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		虎马蛇<span style='background-color: #FFFF00\'>羊</span>龙鸡鼠</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		090期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		虎马蛇<span style='background-color: #FFFF00\'>羊</span>龙鸡鼠猴狗</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");







document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		089期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		089期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">20</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:龙14</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		089期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		20.32.12</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:龙14</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		089期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		20.32.12.36.05.17</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:龙14</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		089期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		20.32.12.36.05.17.03.15.13<br>");
document.writeln("		25.10.22.31.43.<span style='background-color: #FFFF00\'>14</span>.26.04.16</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:龙14</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		089期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		狗</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:龙14</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		089期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		狗马牛</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:龙14</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		089期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		狗马牛兔蛇</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:龙14</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		089期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		狗马牛兔蛇猴猪</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:龙14</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		089期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		狗马牛兔蛇猴猪<span style='background-color: #FFFF00\'>龙</span>虎</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:龙14</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");






document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		088期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		088期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">04</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		088期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		04.16.30</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		088期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		04.16.30.42.07.31</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		088期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		04.16.30.42.07.31.12.24.03<br>");
document.writeln("		<span style='background-color: #FFFF00\'>15</span>.11.23.21.33.20.32.05.17</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		088期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		虎</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		088期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		虎鼠猪</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		088期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		虎鼠猪马<span style='background-color: #FFFF00\'>兔</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		088期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		虎鼠猪马<span style='background-color: #FFFF00\'>兔</span>羊鸡</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		088期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		虎鼠猪马<span style='background-color: #FFFF00\'>兔</span>羊鸡狗牛</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");








document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		087期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		087期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">12</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		087期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		12.24.13</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		087期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		12.24.13.25.02.14</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		087期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		12.24.13.25.02.14.30.42.43<br>");
document.writeln("		31.10.22.05.17.04.16.03.<span style='background-color: #FFFF00\'>15</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		087期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		马</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		087期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马蛇龙</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		087期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马蛇龙鼠猪</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		087期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马蛇龙鼠猪猴牛</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		087期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马蛇龙鼠猪猴牛虎<span style='background-color: #FFFF00\'>兔</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:兔15</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");











document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		086期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		086期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">12</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠30</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		086期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		12.24.13</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠30</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		086期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		12.24.13.49.14.02</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠30</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		086期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		12.24.13.49.14.02.09.33.20<br>");
document.writeln("		32.27.39.42.18.10.22.29.41</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠30</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		086期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		马</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠30</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		086期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马蛇龙</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠30</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		086期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马蛇龙鸡狗</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠30</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		086期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马蛇龙鸡狗兔<span style='background-color: #FFFF00\'>鼠</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠30</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		086期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		马蛇龙鸡狗兔<span style='background-color: #FFFF00\'>鼠</span>猴牛</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠30</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");




document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		085期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		085期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">16</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		085期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		16.40.19</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		085期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		16.40.19.43.47.23</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		085期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		16.40.19.43.47.23.34.22.06<br>");
document.writeln("		42.15.39.14.02.09.33.20.32</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		085期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		虎</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		085期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		虎猪<span style='background-color: #FFFF00\'>羊</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		085期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		虎猪<span style='background-color: #FFFF00\'>羊</span>猴鼠</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		085期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		虎猪<span style='background-color: #FFFF00\'>羊</span>猴鼠兔龙</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		085期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		虎猪<span style='background-color: #FFFF00\'>羊</span>猴鼠兔龙鸡狗</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");








document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		084期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		084期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">06</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		084期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		06.18.41</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		084期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		06.18.41.17.04.40</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		084期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		06.18.41.17.04.40.45.33.44<br>");
document.writeln("		32.43.19.36.48.35.47.10.34</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		084期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		鼠</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		084期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		鼠牛虎</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		084期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		鼠牛虎鸡<span style='background-color: #FFFF00\'>狗</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		084期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		鼠牛虎鸡<span style='background-color: #FFFF00\'>狗</span>猪马</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		084期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		鼠牛虎鸡<span style='background-color: #FFFF00\'>狗</span>猪马羊猴</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:狗20</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");











document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		083期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		083期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">16</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:虎28</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		083期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		16.<span style='background-color: #FFFF00\'>28</span>.35</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:虎28</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		083期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		16.<span style='background-color: #FFFF00\'>28</span>.35.47.34.46</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:虎28</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		083期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		16.<span style='background-color: #FFFF00\'>28</span>.35.47.34.46.08.20.43<br>");
document.writeln("		31.42.18.25.37.36.48.45.21</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:虎28</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		083期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		<span style='background-color: #FFFF00\'>虎</span></font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:虎28</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		083期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		<span style='background-color: #FFFF00\'>虎</span>羊猴</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:虎28</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		083期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		<span style='background-color: #FFFF00\'>虎</span>羊猴狗猪</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:虎28</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		083期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		<span style='background-color: #FFFF00\'>虎</span>羊猴狗猪鼠蛇</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:虎28</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		083期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		<span style='background-color: #FFFF00\'>虎</span>羊猴狗猪鼠蛇马鸡</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:虎28</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");










document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		082期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		082期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">14</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴34</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		082期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		14.26.25</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴34</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		082期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		14.26.25.37.12.24</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴34</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		082期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		14.26.25.37.12.24.35.47.<span style='background-color: #FFFF00\'>34</span><br>");
document.writeln("		46.08.20.45.21.43.31.42.18</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴34</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		082期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		龙</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴34</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		082期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		龙蛇马</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴34</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		082期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		龙蛇马羊<span style='background-color: #FFFF00\'>猴</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴34</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		082期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		龙蛇马羊<span style='background-color: #FFFF00\'>猴</span>狗鸡</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴34</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		082期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		龙蛇马羊<span style='background-color: #FFFF00\'>猴</span>狗鸡猪鼠</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:猴34</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");








document.writeln("   ");
document.writeln("   ");
document.writeln("");
document.writeln("			</table>	");
document.writeln("</body>");