document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<!--");
document.writeln("");
document.writeln("* { word-wrap: break-word; }");
document.writeln("*{padding:0;margin:0}");
document.writeln("* { word-wrap: break-word; }");
document.writeln("* {");
document.writeln("	PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln(".stylesqbz {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("-->");
document.writeln("</style>");
document.writeln("");
document.writeln("<body>");
document.writeln("  ");
document.writeln("");
document.writeln("  <table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #8bafaf\' bgcolor=#8bafaf height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 18pt\'><font color=\'#FFFF00\'>澳门玄机86957</font><font color=\'#FFFFFF\'>『一肖一码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\'cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");





document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		254期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		254期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">05</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		254期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		05.17.21</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		254期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		05.17.21.33.14.26</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		254期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		05.17.21.33.14.26.19.31.15 <br>");
document.writeln("		27.10.22.24.36.13.25.23.35</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		254期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		牛</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		254期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛鸡龙</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		254期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛鸡龙猪兔</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		254期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛鸡龙猪兔猴马</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		254期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛鸡龙猪兔猴马蛇羊</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:？00</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");






document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		253期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		253期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">10</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		253期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		10.34.02</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		253期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		10.34.02.14.23.35</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		253期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		10.34.02.14.23.35.12.24.16<br>");
document.writeln("		28.08.20.29.41.13.25.09.21</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		253期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		猴</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		253期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		猴龙羊</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		253期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		猴龙羊马虎</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		253期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		猴龙羊马虎狗牛</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		253期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		猴龙羊马虎狗牛蛇<span style='background-color: #FFFF00\'>鸡</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鸡33</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");








document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		251期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		251期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">39</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		251期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		39.27.34</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		251期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		39.27.34.46.36.48</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		251期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		39.27.34.46.36.48.23.<span style='background-color: #FFFF00\'>35</span>.14<br>");
document.writeln("		26.08.20.16.28.07.19.17.29</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		251期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		兔</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		251期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		兔猴马</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		251期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		兔猴马<span style='background-color: #FFFF00\'>羊</span>龙</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		251期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		兔猴马<span style='background-color: #FFFF00\'>羊</span>龙狗虎</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		251期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		兔猴马<span style='background-color: #FFFF00\'>羊</span>龙狗虎猪牛</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:羊35</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");










document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		248期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		248期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">05</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马12</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		248期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		05.17.21</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马12</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		248期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		05.17.21.33.14.26</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马12</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		248期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		05.17.21.33.14.26.19.31.15<br>");
document.writeln("		27.10.22.24.36.13.25.23.35</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马12</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		248期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		牛</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马12</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		248期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛鸡龙</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马12</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		248期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛鸡龙猪兔</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马12</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		248期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛鸡龙猪兔猴<span style='background-color: #FFFF00\'>马</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马12</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		248期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛鸡龙猪兔猴<span style='background-color: #FFFF00\'>马</span>蛇羊</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:马12</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");




document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		247期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		247期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">05</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:蛇25</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		247期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		05.17.21</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:蛇25</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		247期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		05.17.21.33.14.26</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:蛇25</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		247期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		05.17.21.33.14.26.19.31.15 <br>");
document.writeln("		27.10.22.24.36.13.<span style='background-color: #FFFF00\'>25</span>.23.35</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:蛇25</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		247期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		牛</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:蛇25</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		247期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛鸡龙</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:蛇25</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		247期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛鸡龙猪兔</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:蛇25</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		247期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛鸡龙猪兔猴马</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:蛇25</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		247期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		牛鸡龙猪兔猴马<span style='background-color: #FFFF00\'>蛇</span>羊</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:蛇25</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");






document.writeln("");
document.writeln(" <!----开始---->");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'99%\' colspan=\'3\' bgcolor=\'#D4D4D4\'>");
document.writeln("		<p align=\"center\"><font face=\'Arial Black\' size=\'4\' color=\'#000000\'> ");
document.writeln("		246期A级大公开;准确率100%!</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		246期一码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><font size=\'4\' color=\'#0000FF\'>重拳出击-</font><b><font color=\'#FF0000\' face=\'Arial\' size=\"5\">16</font></b><font size=\'4\' color=\'#0000FF\'>-信心十足</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠06</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		246期三码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		16.28.05</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠06</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		246期06码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		16.28.05.17.22.46</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠06</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		246期18码</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"> ");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'>");
document.writeln("		27.39.34.43.22.34.09.21.14 <br>");
document.writeln("		26.17.29.30.42.13.25.11.35</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠06</font></td> ");
document.writeln("    </tr> ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		246期一肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\"><b>");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' size=\"5\"> ");
document.writeln("		兔</font></b></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠06</font></td> ");
document.writeln("    </tr>");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		246期三肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		兔猪猴</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠06</font></td> ");
document.writeln("    </tr> ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		246期五肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		兔猪猴鸡龙</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠06</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("        <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		246期七肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		兔猪猴鸡龙牛<span style='background-color: #FFFF00\'>鼠</span></font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠06</font></td> ");
document.writeln("    </tr> ");
document.writeln("    ");
document.writeln("    <tr height=\'31\'> ");
document.writeln("     <td width=\'23%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> ");
document.writeln("		246期九肖</font></td> ");
document.writeln("     <td width=\'59%\' bgcolor=\'#FFFFFF\' align=\"center\">");
document.writeln("		<font color=\'#FF0000\' face=\'宋体\' style=\'font-size: 12pt; font-weight:700\'> ");
document.writeln("		兔猪猴鸡龙牛<span style='background-color: #FFFF00\'>鼠</span>蛇羊</font></td> ");
document.writeln("     <td width=\'18%\' bgcolor=\'#CCFF66\' align=\"center\"><font face=\'宋体\' style=\'font-size: 12pt;color:#000\'> 開:鼠06</font></td> ");
document.writeln("    </tr> ");
document.writeln(" ");
document.writeln("    <tr> ");
document.writeln("     <td colspan=\'3\' height=\'27\' width=\'99%\' bgcolor=\'#000000\'>");
document.writeln("		<p align=\"center\"><font color=\'#FFFFFF\' style=\' font-size: 11pt; font-weight: 700;\'>资料由www. 86957.com长期免费公开!</font></td> ");
document.writeln("    </tr> ");
document.writeln("<!----结束---->    ");
document.writeln("   ");
document.writeln("   ");











document.writeln("   ");
document.writeln("   ");
document.writeln("");
document.writeln("			</table>	");
document.writeln("</body>");