document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<!--");
document.writeln("");
document.writeln("* { word-wrap: break-word; }");
document.writeln("*{padding:0;margin:0}");
document.writeln("* { word-wrap: break-word; }");
document.writeln("* {");
document.writeln("	PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln(".stylesqbz {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("-->");
document.writeln("</style>");
document.writeln("");
document.writeln("<body>");
document.writeln("  ");
document.writeln("");
document.writeln("  <table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #8bafaf\' bgcolor=#8bafaf height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 18pt\'><font color=\'#FFFF00\'>澳门玄机86563</font><font color=\'#FFFFFF\'>『必中4肖8码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");




document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>249期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'>猴鼠蛇马</span><br>");
document.writeln("		</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\' size=\"4\">（14.26.04.40.<span style='background-color: #FFFF00\'>03</span>.27.05.29</span>）</td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:000</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		248期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:000</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		247期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:狗31</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");




document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>246期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'>兔牛<span style='background-color: #FFFF00\'>虎</span><span style='background-color: #FFFF00\'>鼠</span></span><br>");
document.writeln("		</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\' size=\"4\">（14.26.04.40.<span style='background-color: #FFFF00\'>03</span>.27.05.29</span>）</td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:虎15</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		245期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:鼠17</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		244期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:虎03</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");




document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>243期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'>鸡<span style='background-color: #FFFF00\'>猪</span>兔蛇</span><br>");
document.writeln("		</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\' size=\"4\">（20.32.<span style='background-color: #FFFF00\'>30</span>.42.02.14.12.36</span>）</td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:龙01</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		242期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:猪30</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		241期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:牛04</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");





document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>240期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'>猴鸡马<span style='background-color: #FFFF00\'>狗</span></span><br>");
document.writeln("		</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\' size=\"4\">（09.21.20.32.11.23.07.<span style='background-color: #FFFF00\'>31</span>）</td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:蛇24</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		239期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:狗31</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		238期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:猪18</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");






document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>237期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'>狗<span style=\'background-color: #FFFF00\'>虎</span><span style=\'background-color: #FFFF00\'>蛇</span>兔</span><br>");
document.writeln("		</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\' size=\"4\">（07.31.<span style=\'background-color: #FFFF00\'>03</span>.15.12.36.02.14）</td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:猪06</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		236期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:虎03</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		235期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:蛇24</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>234期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'>鼠<span style=\'background-color: #FFFF00\'>狗</span>猪羊</span><br>");
document.writeln("		</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\' size=\"4\">（05.41.<span style=\'background-color: #FFFF00\'>07</span>.31.30.42.10.22)</td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:狗07</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		233期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:马23</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		232期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:兔02</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>231期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'>兔<span style=\'background-color: #FFFF00\'>龙</span>鸡马</span><br>");
document.writeln("		</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\' size=\"4\">（02.14.25.37.20.32.11.23)</td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:鼠17</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		230期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:龙49</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		229期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:鼠05</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>228期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'>狗<span style=\'background-color: #FFFF00\'>羊</span>蛇<span style=\'background-color: #FFFF00\'>龙</span></span><br>");
document.writeln("		</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\' size=\"4\">（07.31.10.22.12.36.13.25)</td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:龙37</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		227期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:鸡20</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		226期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:羊34</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>225期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'4\' color=\'#FF0000\'>龙鸡马<span style=\'background-color: #FFFF00\'>猪</span></span><br>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>（13.25.20.32.11.23.06.<span style=\'background-color: #FFFF00\'>30</span>)</td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:鼠05</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		224期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:羊22</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		223期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:猪30</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>222期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>狗</span>鼠<span style=\'background-color: #FFFF00\'>猴</span>牛</span></span><br>");
document.writeln("		</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\' style=\"font-size: 14pt\">（07.31.05.41.09.<span style=\'background-color: #FFFF00\'>21</span>.04.16)</td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:狗19</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		221期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:龙01</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		220期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:猴21</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>219期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'>马<span style=\'background-color: #FFFF00\'>虎</span>牛<span style=\'background-color: #FFFF00\'>龙</span></span><br>");
document.writeln("		</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\' style=\"font-size: 14pt\">（11.23.03.<span style=\'background-color: #FFFF00\'>15</span>.04.16.13.25)</td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:兔14</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		218期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:龙37</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		217期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:虎15</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("</body>");