document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln("<!--");
document.writeln("");
document.writeln("* { word-wrap: break-word; }");
document.writeln("*{padding:0;margin:0}");
document.writeln("* { word-wrap: break-word; }");
document.writeln("* {");
document.writeln("	PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln("* {");
document.writeln("	WORD-WRAP: break-word");
document.writeln("}");
document.writeln(".stylesqbz {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("-->");
document.writeln("</style>");
document.writeln("");
document.writeln("<body>");
document.writeln("  ");
document.writeln("");
document.writeln("  <table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #8bafaf\' bgcolor=#8bafaf height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 18pt\'><font color=\'#FFFF00\'>澳门玄机86563</font><font color=\'#FFFFFF\'>『必中4肖8码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>123期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'>马鸡鼠兔</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>（23.35.08.44.05.29.02.26）</span></font></strong><font face=\'微软雅黑\' color=\'#FF0000\'></span></font></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:000</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		122期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:000</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		121期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:000</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");
document.writeln("");
document.writeln("");
document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>120期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'>羊<span style='background-color: #FFFF00\'>鼠</span>兔猪</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>（10.34.05.<span style='background-color: #FFFF00\'>29</span>.02.26.06.30）</span></font></strong><font face=\'微软雅黑\' color=\'#FF0000\'></span></font></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:鼠29</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		119期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:鸡32</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		118期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:猴21</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");
document.writeln("");
document.writeln("");


document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>117期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'>鸡<span style='background-color: #FFFF00\'>鼠</span>牛马</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>（20.32.05.<span style='background-color: #FFFF00\'>29</span>.04.40.11.47）</span></font></strong><font face=\'微软雅黑\' color=\'#FF0000\'></span></font></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:龙25</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		116期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:羊10</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		115期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:鼠29</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");
document.writeln("");
document.writeln("");




document.writeln("	<!----开始---->    ");
document.writeln("	<table border=\'1\' width=\'100%\' cellpadding=\'0\' height=\'83\' cellspacing=\'0\' bgcolor=\'#FFFFFF\' bordercolor=\'#D4D4D4\' style=\'border-collapse: collapse\'>");
document.writeln("		<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b><font face=\'微软雅黑\'>114期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'65%\' rowspan=\'3\'>");
document.writeln("		<strong>");
document.writeln("		<font face=\'微软雅黑\' size=\'5\' color=\'#FF0000\'><span style='background-color: #FFFF00\'>猪</span>兔虎牛</font>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>（06.30.02.14.15.27.04.40）</span></font></strong><font face=\'微软雅黑\' color=\'#FF0000\'></span></font></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:猪18</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		113期</font></b></td>");
document.writeln("		<td  height=\'11\' align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\'>");
document.writeln("		<font face=\'微软雅黑\'>开:蛇24</font></td>");
document.writeln("		</tr>");
document.writeln("	<tr>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<b style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("		<font face=\'微软雅黑\' style=\'word-wrap: break-word; margin: 0px; padding: 0px\'>");
document.writeln("		112期</font></b></td>");
document.writeln("		<td align=\'center\' bgcolor=\'#FFFFFF\' width=\'10%\' style=\'height: 26px\'>");
document.writeln("		<font face=\'微软雅黑\'>开:狗43</font></td>");
document.writeln("		</tr>");
document.writeln("		</table>");
document.writeln("		");
document.writeln("<!----结束----> ");
document.writeln("");
document.writeln("");






document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("		");
document.writeln("</body>");