
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	183期<font color=\'#0000FF\'>【龙鸡鼠猪猴狗】</font><font color=\'#FF00FF\'>开？00准</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	182期<font color=\'#0000FF\'>【鼠鸡龙兔<span style=\'background-color: #FFFF00\'>猴</span>蛇】</font><font color=\'#FF00FF\'>开猴08准</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	180期<font color=\'#0000FF\'>【猴羊鼠虎<span style=\'background-color: #FFFF00\'>马</span>牛】</font><font color=\'#FF00FF\'>开马34准</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	179期<font color=\'#0000FF\'>【<span style=\'background-color: #FFFF00\'>鼠</span>鸡龙兔猴蛇】</font><font color=\'#FF00FF\'>开鼠04准</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	178期<font color=\'#0000FF\'>【狗<span style=\'background-color: #FFFF00\'>虎</span>牛鸡猴兔】</font><font color=\'#FF00FF\'>开虎02准</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	176期<font color=\'#0000FF\'>【龙鸡鼠猪<span style=\'background-color: #FFFF00\'>猴</span>狗】</font><font color=\'#FF00FF\'>开猴32准</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	175期<font color=\'#0000FF\'>【鸡鼠虎兔<span style=\'background-color: #FFFF00\'>狗</span>马】</font><font color=\'#FF00FF\'>开狗06准</font></font></b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");
document.writeln("			<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	172期<font color=\'#0000FF\'>【鼠狗马兔<span style=\'background-color: #FFFF00\'>龙</span>鸡】</font><font color=\'#FF00FF\'>开龙12准</font></font></b></font></table>");
document.writeln("		<!--结束-->");
 
document.writeln("			<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\'><b><font size=\'4\'>");
document.writeln("	170期<font color=\'#0000FF\'>【鼠狗<span style=\'background-color: #FFFF00\'>马</span>兔龙鸡】</font><font color=\'#FF00FF\'>开马10准</font></font></b></font></table>");
document.writeln("		<!--结束-->");
 
 
document.writeln("			");
document.writeln("<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.100tzz.com:100/\' style=\'text-decoration: none\'><img src=/yyy123.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 15pt\'>点击投注澳门六合彩</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>100.cc</font></span></a></strong></tr></table>		");
