document.writeln("");
document.writeln("");
document.writeln("<script language=\'JavaScript\' type=\'text/javascript\' src=\'/chajiansb.js\' charset=\'utf-8\'></script>");
document.writeln("");
document.writeln("<table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\'>");
document.writeln("");
document.writeln("");


document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>165期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>双</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开猫00</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>164期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>双</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开马10</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>162期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>单</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开猪17</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");

 
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>160期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>双</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开狗42</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>157期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>双</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开猴44</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");

document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>156期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>单</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开鸡43</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
 
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>154期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>单</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开牛03</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>153期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>单</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开鸡19</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>151期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>双</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开狗30</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>150期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>双</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开狗06</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
 
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>147期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>双</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开马22</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
 
document.writeln("");
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>145期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>双</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开狗06</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
 
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>143期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>单</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开猪29</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>142期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>单</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开猪05</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>140期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>单</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开兔13</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("<!--开始-->	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td class=\'center f11 black l150\' align=\'center\'>");
document.writeln("	");
document.writeln("		<p>");
document.writeln("	");
document.writeln("		<span>");
document.writeln("	");
document.writeln("		<b>");
document.writeln("	");
document.writeln("		<font size=\'4\'>138期:<font color=\'#0000FF\'>单双中特</font><font color=\'#FF00FF\'>【</font></font><font color=\'#FF0000\' face=\'禹卫书法行书简体");
document.writeln("\' style=\'font-size: 14pt\'>单</font><font size=\'4\'><font color=\'#FF00FF\'>】</font><font color=\'#0000FF\'>开兔01</font></font></b></td></tr>");
document.writeln("");
document.writeln("<!--结束-->");
document.writeln("");
 
  
 
document.writeln("");
document.writeln("<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.100tzz.com:100/\' style=\'text-decoration: none\'><img src=/yyy123.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 15pt\'>点击投注澳门六合彩</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>100.cc</font></span></a></strong></tr></table>");
document.writeln("	</table>");
document.writeln("</div>	");