document.writeln("");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Language\' content=\'zh-cn\'>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("");
document.writeln("<style type=\'text/css\'>");
document.writeln(".stylei {");
document.writeln("	color: #FFFF00;");
document.writeln("	background-color: #000000;");
document.writeln("}");
document.writeln(".stylei {");
document.writeln("	font-size: medium;");
document.writeln("	color: #FFFF00;");
document.writeln("	background-color: #000000;");
document.writeln("}");
document.writeln(".styleszwbz {");
document.writeln("	color: #FF0000;");
document.writeln("}");
document.writeln(".style1jsll {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("  <table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #8bafaf\' bgcolor=#8bafaf height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳门玄机网</font><font color=\'#FFFFFF\'>『平码玩家』</font></font></b></table>");
document.writeln("<script language=\'JavaScript\' type=\'text/javascript\' src=\'/chajiansb.js\' charset=\'utf-8\'></script>");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		171期：开00.00.00.00.00.00T00</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【猪狗拖猴羊】<Br>");
document.writeln("06.42.07.31拖21.33.34.46<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【23拖79】<br>22.32.42.03.13.23拖07.17.27.29.39.49<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【02.05.16.17.18】<BR> ②【22.30.31.32.39】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");






document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		170期：开12.43.34.28.01.08T10</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【牛兔拖猪猴】<Br>");
document.writeln("28.40.26.38拖30.18.45.21<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【36拖49】<br>03.13.23.16.26.36拖04.14.24.19.29.39<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>05.07.16.17.18</span>】<BR> ②【19.23.34.35.38】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		169期：开22.03.15.09.16.40T45</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【虎狗拖牛龙】<Br>");
document.writeln("15.39.07.31拖04.40.13.49	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>61</span>拖91】<br><span style='background-color: #FFFF00\'>16</span>.26.36.02.12.<span style='background-color: #FFFF00\'>22</span>拖09.19.29.01.11.21<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【10.11.14.15.16】<BR> ②【<span style='background-color: #FFFF00\'>20.21.24.35.37</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		167期：开32.02.29.11.34.49T14</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【鸡虎拖兔狗】<Br>");
document.writeln("20.32.27.39拖14.26.19.43	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【39拖51】<br>13.23.33.19.29.49拖05.25.35.11.21.31<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>08.09.24.25.27</span>】<BR> ②【<span style='background-color: #FFFF00\'>38.39.40.41.42</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln(" ");








document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		165期：开40.17.26.37.41.29T03</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【牛马拖鸡鼠】<Br>");
document.writeln("04.40.47.35拖32.20.17.29	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【14拖58】<br>01.21.31.24.44.14拖05.15.25.28.38.48<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>01.09.10.11.12</span>】<BR> ②【24.25.26.30.38】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");



document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		164期：开20.07.42.32.19.24T44</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【蛇牛拖鼠虎】<Br>");
document.writeln("36.48.40.28拖05.17.27.39	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【38拖16】<br>13.23.33.18.28.48拖01.11.21.06.36.46<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>01.07.27.28.29</span>】<BR> ②【<span style='background-color: #FFFF00\'>30.33.34.35.46</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");






document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		163期：开20.31.25.42.27.0T40</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【<span style='background-color: #FFFF00\'>狗虎</span>拖蛇马】<Br>");
document.writeln("07.<span style='background-color: #FFFF00\'>31</span>.15.39拖48.24.35.23	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>72</span>拖16】<br>17.<span style='background-color: #FFFF00\'>27</span>.47.02.22.32拖21.31.41.16.26.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【22.23.26.31.32】<BR> ②【<span style='background-color: #FFFF00\'>35.36.37.38.39</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		162期：开11.25.06.44.05.13T01</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【猴鼠拖虎龙】<Br>");
document.writeln("09.33.17.29拖15.39.25.37	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【58拖07】<br>05.15.25.28.38.48拖10.20.30.07.17.27<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>07.15.16.19.20</span>】<BR> ②【<span style='background-color: #FFFF00\'>21.28.29.30.3</span>6】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln("");
document.writeln("	");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		161期：开20.23.19.41.47.11T35</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【兔羊拖牛马】<Br>");
document.writeln("26.14.46.22拖16.40.47.23	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>53</span>拖16】<br>25.<span style='background-color: #FFFF00\'>35</span>.45.03.13.<span style='background-color: #FFFF00\'>23</span>拖11.21.31.16.26.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>03.20.21.22.28</span>】<BR> ②【<span style='background-color: #FFFF00\'>29.30.31.32.45</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");






document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		160期：开48.15.36.49.32.03T27</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【兔牛拖猪羊】<Br>");
document.writeln("14.02.28.40拖18.06.46.22	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【43拖<span style='background-color: #FFFF00\'>85</span>】<br>04.14.24.13.23.33拖28.38.<span style='background-color: #FFFF00\'>48</span>.05.<span style='background-color: #FFFF00\'>15</span>.35<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>02.05.06.07.18</span>】<BR> ②【<span style='background-color: #FFFF00\'>19.20.21.28.34</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln(" ");
document.writeln("");






document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		159期：开29.07.44.49.06.01T43</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【鸡鼠拖羊龙】<Br>");
document.writeln("44.20.05.29拖10.34.49.25	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>47</span>拖05】<br>14.24.34.27.37.47拖20.30.40.05.15.25<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【07.16.17.18.22】<BR> ②【<span style='background-color: #FFFF00\'>33.34.35.38.47</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln(" ");
document.writeln("");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		158期：开47.12.06.27.42.05T20</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【猪狗拖猴羊】<Br>");
document.writeln("06.42.07.31拖21.33.34.46<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【23拖79】<br>22.32.42.03.13.23拖07.17.27.29.39.49<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【02.05.16.17.18】<BR> ②【<span style='background-color: #FFFF00\'>22.30.31.32.39</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		157期：开11.13.47.29.41.48T45</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【牛兔拖猪猴】<Br>");
document.writeln("28.40.26.38拖30.18.45.21<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【36拖49】<br>03.13.23.16.26.36拖04.14.24.19.29.39<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>05.07.16.17.18</span>】<BR> ②【<span style='background-color: #FFFF00\'>19.23.34.35.38</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		156期：开38.44.06.12.26.25T42</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【虎狗拖牛龙】<Br>");
document.writeln("15.39.07.31拖04.40.13.49	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>62</span>拖91】<br>16.26.36.02.<span style='background-color: #FFFF00\'>12</span>.22拖09.19.29.01.11.21<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>10.11.14.15.16</span>】<BR> ②【<span style='background-color: #FFFF00\'>20.21.24.35.37</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		155期：开40.29.23.47.07.32T44</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【牛兔拖鼠猪】<Br>");
document.writeln("04.28.02.26拖17.29.06.42	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【56拖08】<br>15.25.35.26.36.46拖20.30.40.08.18.38<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>01.02.03.09.10</span>】<BR> ②【<span style='background-color: #FFFF00\'>11.12.13.14.15</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");






document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		152期：开16.35.18.30.15.40T21</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【<span style='background-color: #FFFF00\'>牛马</span>拖鸡鼠】<Br>");
document.writeln("04.<span style='background-color: #FFFF00\'>40</span>.47.<span style='background-color: #FFFF00\'>35</span>拖32.20.17.29	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【14拖<span style='background-color: #FFFF00\'>58</span>】<br>01.21.31.24.44.14拖05.15.25.28.38.48<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>01.09.10.11.12</span>】<BR> ②【24.25.26.30.38】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		151期：开12.41.09.05.44.26T48</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【蛇牛拖鼠虎】<Br>");
document.writeln("36.48.40.28拖05.17.27.39	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【38拖<span style='background-color: #FFFF00\'>16</span>】<br>13.23.33.18.28.48拖01.11.21.06.36.46<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>01.07.27.28.29</span>】<BR> ②【<span style='background-color: #FFFF00\'>30.33.34.35.46</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");







document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		150期：开24.16.45.21.40.15T33</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【狗虎拖蛇马】<Br>");
document.writeln("07.31.15.39拖48.24.35.23	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【72拖16】<br>17.27.47.02.22.32拖21.31.41.16.26.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>22.23.26.31.32</span>】<BR> ②【<span style='background-color: #FFFF00\'>35.36.37.38.39</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		149期：开12.32.45.46.01.06T22</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【猴鼠拖虎龙】<Br>");
document.writeln("09.33.17.29拖15.39.25.37	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【58拖07】<br>05.15.25.28.38.48拖10.20.30.07.17.27<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【07.15.16.19.20】<BR> ②【21.28.29.30.36】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln("");
document.writeln("	");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		148期：开10.15.45.23.49.09T27</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【兔羊拖牛马】<Br>");
document.writeln("26.14.46.22拖16.40.47.23	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>53</span>拖16】<br>25.35.<span style='background-color: #FFFF00\'>45</span>.03.13.<span style='background-color: #FFFF00\'>23</span>拖11.21.31.16.26.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>03.20.21.22.28</span>】<BR> ②【29.30.31.32.45】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		147期：开21.33.06.17.38.35T02</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【兔牛拖猪羊】<Br>");
document.writeln("14.02.28.40拖18.06.46.22	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【43拖<span style='background-color: #FFFF00\'>85</span>】<br>04.14.24.13.23.33拖28.<span style='background-color: #FFFF00\'>38</span>.48.05.15.<span style='background-color: #FFFF00\'>35</span><Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【02.05.06.07.18】<BR> ②【19.20.21.28.34】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln(" ");
document.writeln("");







document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		146期：开03.15.08.28.38.40T43</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【鸡鼠拖羊龙】<Br>");
document.writeln("44.20.05.29拖10.34.49.25	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【47拖<span style='background-color: #FFFF00\'>05</span>】<br>14.24.34.27.37.47拖20.30.<span style='background-color: #FFFF00\'>40</span>.05.<span style='background-color: #FFFF00\'>15</span>.25<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>07.16.17.18.22</span>】<BR> ②【33.34.35.38.47】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln(" ");
document.writeln("");



document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		145期：开45.29.27.23.11.28T02</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【猪狗拖猴羊】<Br>");
document.writeln("06.42.07.31拖21.33.34.46<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>23</span>拖<span style='background-color: #FFFF00\'>79</span>】<br>22.32.42.03.13.<span style='background-color: #FFFF00\'>23</span>拖07.17.<span style='background-color: #FFFF00\'>27.29</span>.39.49<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【02.05.16.17.18】<BR> ②【<span style='background-color: #FFFF00\'>22.30.31.32.39</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");






document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		144期：开10.09.02.17.28.05T16</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【<span style='background-color: #FFFF00\'>牛兔</span>拖猪猴】<Br>");
document.writeln("28.40.26.38拖30.18.45.21<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【36拖49】<br>03.13.23.16.26.36拖04.14.24.19.29.39<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【05.07.16.17.18】<BR> ②【<span style='background-color: #FFFF00\'>19.23.34.35.38</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");






document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		141期：开23.05.19.06.28.46T43</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【鸡虎拖兔狗】<Br>");
document.writeln("20.32.27.39拖14.26.19.43	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>39</span>拖51】<br>13.<span style='background-color: #FFFF00\'>23</span>.33.<span style='background-color: #FFFF00\'>19</span>.29.49拖05.25.35.11.21.31<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>08.09.24.25.27</span>】<BR> ②【<span style='background-color: #FFFF00\'>38.39.40.41.42</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln(" ");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		140期：开05.13.30.36.23.07T35</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【猴蛇拖<span style='background-color: #FFFF00\'>马猪</span>】<Br>");
document.writeln("45.21.12.24拖35.47.18.30	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【43拖16】<br>24.34.44.03.13.23拖11.21.31.16.26.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【04.05.09.10.11】<BR> ②【12.13.14.17.18】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");











document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		137期：开20.42.15.26.01.10T16</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【狗虎拖蛇马】<Br>");
document.writeln("07.31.15.39拖48.24.35.23	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【72拖<span style='background-color: #FFFF00\'>16</span>】<br>17.27.47.02.22.32拖21.31.41.<span style='background-color: #FFFF00\'>16.26</span>.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【22.23.26.31.32】<BR> ②【<span style='background-color: #FFFF00\'>35.36.37.38.39</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");





document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://76891.com/#868627\' style=\'text-decoration: none\'><img src=/yyy123.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 15pt\'>进入澳彩网</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>76891.com</font></span></a></strong></tr></table>		");
document.writeln("  </tbody>");
document.writeln("</table>");