document.writeln("");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Language\' content=\'zh-cn\'>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("");
document.writeln("<style type=\'text/css\'>");
document.writeln(".stylei {");
document.writeln("	color: #FFFF00;");
document.writeln("	background-color: #000000;");
document.writeln("}");
document.writeln(".stylei {");
document.writeln("	font-size: medium;");
document.writeln("	color: #FFFF00;");
document.writeln("	background-color: #000000;");
document.writeln("}");
document.writeln(".styleszwbz {");
document.writeln("	color: #FF0000;");
document.writeln("}");
document.writeln(".style1jsll {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("  <table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #8bafaf\' bgcolor=#8bafaf height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳门玄机网</font><font color=\'#FFFFFF\'>『平码玩家』</font></font></b></table>");
document.writeln("<script language=\'JavaScript\' type=\'text/javascript\' src=\'/chajiansb.js\' charset=\'utf-8\'></script>");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");


document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		124期：开00.00.00.00.00.00T00</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【狗虎拖蛇马】<Br>");
document.writeln("07.31.15.39拖48.24.35.23	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【72拖16】<br>17.27.47.02.22.32拖21.31.41.16.26.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【22.23.26.31.32】<BR> ②【35.36.37.38.39】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		123期：开09.07.19.11.10.31T21</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【猴鼠拖虎龙】<Br>");
document.writeln("09.33.17.29拖15.39.25.37	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【58拖<span style='background-color: #FFFF00\'>07</span>】<br>05.15.25.28.38.48拖<span style='background-color: #FFFF00\'>10</span>.20.30.<span style='background-color: #FFFF00\'>07</span>.17.27<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【07.15.16.19.20】<BR> ②【21.28.29.30.36】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln("");
document.writeln("	");



document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		122期：开25.10.02.20.40.15T36</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【<span style='background-color: #FFFF00\'>兔羊</span>拖牛马】<Br>");
document.writeln("26.14.46.22拖16.40.47.23	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【53拖16】<br>25.35.45.03.13.23拖11.21.31.16.26.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>03.20.21.22.28</span>】<BR> ②【<span style='background-color: #FFFF00\'>29.30.31.32.45</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		121期：开15.24.08.43.33.47T02</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【兔牛拖猪羊】<Br>");
document.writeln("14.02.28.40拖18.06.46.22	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>43</span>拖<span style='background-color: #FFFF00\'>85</span>】<br>04.14.<span style='background-color: #FFFF00\'>24</span>.13.23.<span style='background-color: #FFFF00\'>33</span>拖28.38.48.05.<span style='background-color: #FFFF00\'>15</span>.35<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【02.05.06.07.18】<BR> ②【1<span style='background-color: #FFFF00\'>9.20.21.28.34</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln(" ");
document.writeln("");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		120期：开21.10.05.32.25.22T29</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【<span style='background-color: #FFFF00\'>鸡鼠</span>拖<span style='background-color: #FFFF00\'>羊龙</span>】<Br>");
document.writeln("44.20.<span style='background-color: #FFFF00\'>05</span>.<span style='background-color: #FFFF00\'>29</span>拖<span style='background-color: #FFFF00\'>10</span>34.49.<span style='background-color: #FFFF00\'>25</span>	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【47拖05】<br>14.24.34.27.37.47拖20.30.40.05.15.25<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【07.16.17.18.22】<BR> ②【<span style='background-color: #FFFF00\'>33.34.35.38.47</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln(" ");
document.writeln("");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		119期：开09.16.20.02.27.40T32</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【猪狗拖猴羊】<Br>");
document.writeln("06.42.07.31拖21.33.34.46<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【23拖<span style='background-color: #FFFF00\'>79</span>】<br>22.32.42.03.13.23拖07.17.<span style='background-color: #FFFF00\'>27</span>.29.39.49<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【02.05.16.17.18】<BR> ②【22.30.31.32.39】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		118期：开41.26.40.43.46.49T21</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【<span style='background-color: #FFFF00\'>牛兔</span>拖猪猴】<Br>");
document.writeln("28.<span style='background-color: #FFFF00\'>40.26</span>.38拖30.18.45.21<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>36</span>拖49】<br>03.13.23.16.<span style='background-color: #FFFF00\'>26</span>.36拖04.14.24.19.29.39<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>05.07.16.17.18</span>】<BR> ②【<span style='background-color: #FFFF00\'>19.23.34.35.38</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		117期：开43.09.14.29.19.45T25</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【虎狗拖牛龙】<Br>");
document.writeln("15.39.07.31拖04.40.13.49	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【62拖91】<br>16.26.36.02.12.22拖09.19.29.01.11.21<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>10.11.14.15.16</span>】<BR> ②【<span style='background-color: #FFFF00\'>20.21.24.35.37</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		116期：开02.11.15.12.20.08T10</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【牛兔拖鼠猪】<Br>");
document.writeln("04.28.02.26拖17.29.06.42	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【56拖<span style='background-color: #FFFF00\'>08</span>】<br>15.25.35.26.36.46拖<span style='background-color: #FFFF00\'>20</span>.30.40.<span style='background-color: #FFFF00\'>08</span>.18.38<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【01.02.03.09.10】<BR> ②【11.12.13.14.15】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		115期：开23.46.10.44.20.33T29</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【鸡虎拖兔狗】<Br>");
document.writeln("20.32.27.39拖14.26.19.43	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>39</span>拖51】<br>13<span style='background-color: #FFFF00\'>.23.33</span>.19.<span style='background-color: #FFFF00\'>29</span>.49拖05.25.35.11.21.31<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>08.09.24.25.27</span>】<BR> ②【<span style='background-color: #FFFF00\'>38.39.40.41.42</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln(" ");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		114期：开34.07.43.19.39.01T18</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【猴蛇拖马猪】<Br>");
document.writeln("45.21.12.24拖35.47.18.30	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>43</span>拖16】<br>24.<span style='background-color: #FFFF00\'>34</span>.44.03.13.23拖11.21.31.16.26.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>04.05.09.10.11</span>】<BR> ②【12.13.14.17.18】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");



document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		113期：开39.37.48.49.05.19T24</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【牛马拖鸡鼠】<Br>");
document.writeln("04.40.47.35拖32.20.17.29	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【14拖<span style='background-color: #FFFF00\'>58</span>】<br>01.21.31.24.44.14拖<span style='background-color: #FFFF00\'>05</span>.15.25.28.38.<span style='background-color: #FFFF00\'>48</span><Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>01.09.10.11.12</span>】<BR> ②【<span style='background-color: #FFFF00\'>24.25.26.30.38</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");



document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		112期：开35.44.48.29.45.36T43</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【蛇牛拖鼠虎】<Br>");
document.writeln("36.48.40.28拖05.17.27.39	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>38</span>拖16】<br>13.23.33.18.28.48拖01.11.21.06.36.46<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>01.07.27.28.29</span>】<BR> ②【<span style='background-color: #FFFF00\'>30.33.34.35.46</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		111期：开18.01.40.16.37.34T43</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【狗虎拖蛇马】<Br>");
document.writeln("07.31.15.39拖48.24.35.23	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【72拖<span style='background-color: #FFFF00\'>16</span>】<br>17.27.47.02.22.32拖21.31.41.<span style='background-color: #FFFF00\'>16</span>.26.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>22.23.26.31.32</span>】<BR> ②【35.36.37.38.39】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		110期：开21.34.10.35.24.06T48</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【猴鼠拖虎龙】<Br>");
document.writeln("09.33.17.29拖15.39.25.37	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>58</span>拖07】<br>05.15.25.28.38.48拖10.20.30.07.17.27<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>07.15.16.19.2007.15.16.19.20</span>】<BR> ②【<span style='background-color: #FFFF00\'>21.28.29.30.36</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln("");
document.writeln("	");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		109期：开22.41.30.40.02.25T43</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【<span style='background-color: #FFFF00\'>兔羊</span>拖牛马】<Br>");
document.writeln("26.14.46.22拖16.40.47.23	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>53</span>拖16】<br><span style='background-color: #FFFF00\'>25</span>.35.45.03.13.23拖11.21.31.16.26.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>03.20.21.22.28</span>】<BR> ②【29.30.31.32.45】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");








document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		106期：开25.46.49.47.01.36T16</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【猪狗拖猴羊】<Br>");
document.writeln("06.42.07.31拖21.33.34.46<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【23拖<span style='background-color: #FFFF00\'>79</span>】<br>22.32.42.03.13.23拖07.17.27.29.39.49<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【02.05.16.17.18】<BR> ②【<span style='background-color: #FFFF00\'>22.30.31.32.39</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		105期：开19-07-14-10-30-16T49</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【<span style=\'background-color: #FFFF00\'>牛</span>兔拖<span style=\'background-color: #FFFF00\'>猪</span>猴】<Br>");
document.writeln("28.40.26.38拖<span style=\'background-color: #FFFF00\'>30</span>.18.45.21<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【3<span style=\'background-color: #FFFF00\'>6</span>拖4<span style=\'background-color: #FFFF00\'>9</span>】<br>03.13.23.<span style=\'background-color: #FFFF00\'>16</span>.26.36拖04.14.24.<span style=\'background-color: #FFFF00\'>19</span>.29.39<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style=\'background-color: #FFFF00\'>05.07.16.17.18</span>】<BR> ②【19.23.34.35.38】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		102期：开36.41.18.08.07.10T19</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【<span style=\'background-color: #FFFF00\'>鸡</span>虎拖兔<span style=\'background-color: #FFFF00\'>狗</span>】<Br>");
document.writeln("20.32.27.39拖14.26.<span style=\'background-color: #FFFF00\'>19</span>.43	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【3<span style=\'background-color: #FFFF00\'>9</span>拖5<span style=\'background-color: #FFFF00\'>1</span>】<br>13.23.33.19.29.49拖05.25.35.11.21.31<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【08.09.24.25.27】<BR> ②【38.39.40.41.42】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln(" ");



document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		101期：开29.07.45.06.26.27T21</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【<span style=\'background-color: #FFFF00\'>猴</span>蛇拖马<span style=\'background-color: #FFFF00\'>猪</span>】<Br>");
document.writeln("45.<span style=\'background-color: #FFFF00\'>21</span>.12.24拖35.47.18.30	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【43拖16】<br>24.34.44.03.13.23拖11.21.31.16.26.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style=\'background-color: #FFFF00\'>04.05.09.10.11</span>】<BR> ②【<span style=\'background-color: #FFFF00\'>12.13.14.17.18</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");



document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		100期：开05.38.35.32.24.06T17</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【牛<span style=\'background-color: #FFFF00\'>马</span>拖<span style=\'background-color: #FFFF00\'>鸡鼠</span>】<Br>");
document.writeln("04.40.47.<span style=\'background-color: #FFFF00\'>35</span>拖<span style=\'background-color: #FFFF00\'>32</span>.20.<span style=\'background-color: #FFFF00\'>17</span>.29	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【1<span style=\'background-color: #FFFF00\'>4</span>拖<span style=\'background-color: #FFFF00\'>58</span>】<br>01.21.31.<span style=\'background-color: #FFFF00\'>24</span>.44.14拖<span style=\'background-color: #FFFF00\'>05</span>.15.25.28.<span style=\'background-color: #FFFF00\'>38</span>.48<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style=\'background-color: #FFFF00\'>01.09.10.11.12</span>】<BR> ②【24.25.26.30.38】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");










document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://76891.com/#868627\' style=\'text-decoration: none\'><img src=/yyy123.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 15pt\'>进入澳彩网</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>76891.com</font></span></a></strong></tr></table>		");
document.writeln("  </tbody>");
document.writeln("</table>");