document.writeln("");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Language\' content=\'zh-cn\'>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("");
document.writeln("<style type=\'text/css\'>");
document.writeln(".stylei {");
document.writeln("	color: #FFFF00;");
document.writeln("	background-color: #000000;");
document.writeln("}");
document.writeln(".stylei {");
document.writeln("	font-size: medium;");
document.writeln("	color: #FFFF00;");
document.writeln("	background-color: #000000;");
document.writeln("}");
document.writeln(".styleszwbz {");
document.writeln("	color: #FF0000;");
document.writeln("}");
document.writeln(".style1jsll {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("  <table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #8bafaf\' bgcolor=#8bafaf height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>澳门玄机网</font><font color=\'#FFFFFF\'>『平码玩家』</font></font></b></table>");
document.writeln("<script language=\'JavaScript\' type=\'text/javascript\' src=\'/chajiansb.js\' charset=\'utf-8\'></script>");
document.writeln("");
document.writeln("<table width=\'100%\' id=\'table1\' cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("  <tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		174期：开00.00.00.00.00.00T00</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【兔羊拖牛马】<Br>");
document.writeln("26.14.46.22拖16.40.47.23	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【53拖16】<br>25.35.45.03.13.23拖11.21.31.16.26.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【03.20.21.22.28】<BR> ②【29.30.31.32.45】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		173期：开11.10.47.41.17.09T49</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【兔牛拖猪羊】<Br>");
document.writeln("14.02.28.40拖18.06.46.22	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【43拖85】<br>04.14.24.13.23.33拖28.38.48.05.15.35<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>02.05.06.07.18</span>】<BR> ②【<span style='background-color: #FFFF00\'>19.20.21.28.34</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln(" ");
document.writeln("");






document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		172期：开10.20.07.30.29.05T32</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【<span style='background-color: #FFFF00\'>鸡鼠</span>拖羊龙】<Br>");
document.writeln("44.<span style='background-color: #FFFF00\'>20</span>.<span style='background-color: #FFFF00\'>05.29</span>拖10.34.49.25	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【47拖<span style='background-color: #FFFF00\'>05</span>】<br>14.24.34.27.37.47拖<span style='background-color: #FFFF00\'>20.30.</span>40.<span style='background-color: #FFFF00\'>05</span>.15.25<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【07.16.17.18.22】<BR> ②【<span style='background-color: #FFFF00\'>33.34.35.38.47</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln(" ");
document.writeln("");






document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		171期：开19.33.42.43.113.08T16</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【<span style='background-color: #FFFF00\'>猪狗</span>拖猴羊】<Br>");
document.writeln("06.<span style='background-color: #FFFF00\'>42</span>.07.31拖21.33.34.46<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>23</span>拖79】<br>22.32.<span style='background-color: #FFFF00\'>42</span>.03.<span style='background-color: #FFFF00\'>13</span>.23拖07.17.27.29.39.49<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【02.05.16.17.18】<BR> ②【<span style='background-color: #FFFF00\'>22.30.31.32.39</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");






document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		170期：开12.43.34.28.01.08T10</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【牛兔拖猪猴】<Br>");
document.writeln("28.40.26.38拖30.18.45.21<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【36拖49】<br>03.13.23.16.26.36拖04.14.24.19.29.39<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>05.07.16.17.18</span>】<BR> ②【19.23.34.35.38】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");





document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		169期：开22.03.15.09.16.40T45</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【虎狗拖牛龙】<Br>");
document.writeln("15.39.07.31拖04.40.13.49	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>61</span>拖91】<br><span style='background-color: #FFFF00\'>16</span>.26.36.02.12.<span style='background-color: #FFFF00\'>22</span>拖09.19.29.01.11.21<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【10.11.14.15.16】<BR> ②【<span style='background-color: #FFFF00\'>20.21.24.35.37</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");




document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		167期：开32.02.29.11.34.49T14</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【鸡虎拖兔狗】<Br>");
document.writeln("20.32.27.39拖14.26.19.43	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【39拖51】<br>13.23.33.19.29.49拖05.25.35.11.21.31<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>08.09.24.25.27</span>】<BR> ②【<span style='background-color: #FFFF00\'>38.39.40.41.42</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");
document.writeln(" ");








document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		165期：开40.17.26.37.41.29T03</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【牛马拖鸡鼠】<Br>");
document.writeln("04.40.47.35拖32.20.17.29	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【14拖58】<br>01.21.31.24.44.14拖05.15.25.28.38.48<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>01.09.10.11.12</span>】<BR> ②【24.25.26.30.38】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");



document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		164期：开20.07.42.32.19.24T44</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【蛇牛拖鼠虎】<Br>");
document.writeln("36.48.40.28拖05.17.27.39	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【38拖16】<br>13.23.33.18.28.48拖01.11.21.06.36.46<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		①【<span style='background-color: #FFFF00\'>01.07.27.28.29</span>】<BR> ②【<span style='background-color: #FFFF00\'>30.33.34.35.46</span>】<Br>");
document.writeln("<Br>");
document.writeln("</font></b></td>");
document.writeln("    </tr>");
document.writeln("");
document.writeln("    ");
document.writeln("    	<tr>");
document.writeln("      <td align=\'left\' height=28 bgcolor=\'#0000FF\' ><p><b>");
document.writeln("		<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("		<a target=\'_blank\' href=\'https://j.1999xz.com:1999/\' style=\'text-decoration: none\'>");
document.writeln("		<font color=\'#FFFFFF\'>关注玄机网</font></font><font color=\'#FFFF00\' size=\'4\' face=\'微软雅黑\'>868680.com</font><font color=\'#FFFFFF\' face=\'微软雅黑\' size=\'2\'>最早看料</font></a><font face=\'微软雅黑\' size=\'2\'><font color=\'#FFFFFF\'> </font>  ");
document.writeln("		</font>  ");
document.writeln("		</b> </td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    <!--结束-->     ");
document.writeln(" ");






document.writeln("   <!--开始--->");
document.writeln("");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=47 bgcolor=\'#FFFFFF\' ><p>");
document.writeln("		<font face=\'微软雅黑\'>");
document.writeln("		<font color=\'#000000\' style=\'font-size: 14pt; font-weight:700\'>");
document.writeln("		163期：开20.31.25.42.27.0T40</font></font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("	<tr>");
document.writeln("      <td align=\'left\' height=35 bgcolor=\'#FFFFFF\' ><p><b>");
document.writeln("		<font color=\'#FF0000\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		【平码小娱乐：共同探讨彩界真理】</font><font color=\'#6600CC\' style=\'font-size: 12pt\' face=\'微软雅黑\'><br></font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平特连肖：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		【<span style='background-color: #FFFF00\'>狗虎</span>拖蛇马】<Br>");
document.writeln("07.<span style='background-color: #FFFF00\'>31</span>.15.39拖48.24.35.23	<Br>	");
document.writeln("	（16组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		");
document.writeln("		平特连尾：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("	【<span style='background-color: #FFFF00\'>72</span>拖16】<br>17.<span style='background-color: #FFFF00\'>27</span>.47.02.22.32拖21.31.41.16.26.36<Br>		");
document.writeln("	（36组2中2）<Br><Br>	");
document.writeln("		");
document.writeln("</font>");
document.writeln("		<font color=\'#FF00FF\' style=\'font-size: 12pt\' face=\'微软雅黑\'>");
document.writeln("		");
document.writeln("		平码五不中：</font><font color=\'#000080\' style=\'font-size: 12pt\' face=\'微软雅黑\'><Br>");
document.writeln("		�