document.writeln("<html>");
document.writeln("");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Language\' content=\'zh-cn\'>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("<title>030期</title>");
document.writeln("<style type=\'text/css\'>");
document.writeln(".stylef {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");
document.writeln("<script language=\'JavaScript\' type=\'text/javascript\' src=\'/chajiansb.js\' charset=\'utf-8\'></script>");
document.writeln("<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("<div class=\'box\' id=\'ptyx\'>");
document.writeln("");
document.writeln("");
document.writeln("<table border=\'1\' width=\'100%\' cellpadding=\'0\' cellspacing=\'0\' bordercolorlight=\'#FFFFFF\' bordercolordark=\'#FFFFFF\' bgcolor=\'#FFFFFF\'>");
document.writeln("		");
document.writeln("		");

document.writeln("				");
document.writeln("					<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font size=\'4\' face=\'楷体\'>");
document.writeln("	<b>181期<font color=\'#6600CC\'>【二尾→拖49尾】开</font><font color=\'#FF6600\'>00.00.00</font>准</b></font></table>");
document.writeln("		");
document.writeln("		");
document.writeln("				");
document.writeln("			<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font size=\'4\' face=\'楷体\'>");
document.writeln("	<b>180期<font color=\'#6600CC\'>【<span style=\'background-color: #FFFF00\'>八尾</span>→拖<span style=\'background-color: #FFFF00\'>4</span>9尾】开</font><font color=\'#FF6600\'>38.48.34</font>准</b></font></table>");
document.writeln("		");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln("			<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font size=\'4\' face=\'楷体\'>");
document.writeln("	<b>179期<font color=\'#6600CC\'>【<span style=\'background-color: #FFFF00\'>三尾</span>→拖1<span style=\'background-color: #FFFF00\'>7</span>尾】开</font><font color=\'#FF6600\'>03.07.00</font>准</b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font size=\'4\' face=\'楷体\'>");
document.writeln("	<b>178期<font color=\'#6600CC\'>【<span style=\'background-color: #FFFF00\'>二尾</span>→拖<span style=\'background-color: #FFFF00\'>48</span>尾】开</font><font color=\'#FF6600\'>02.14.18</font>准</b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("			<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font size=\'4\' face=\'楷体\'>");
document.writeln("	<b>177期<font color=\'#6600CC\'>【<span style=\'background-color: #FFFF00\'>三尾</span>→拖<span style=\'background-color: #FFFF00\'>2</span>5尾】开</font><font color=\'#FF6600\'>33.32.00</font>准</b></font></table>");
document.writeln("		");
document.writeln("		");

document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font size=\'4\' face=\'楷体\'>");
document.writeln("	<b>176期<font color=\'#6600CC\'>【<span style=\'background-color: #FFFF00\'>六尾</span>→拖<span style=\'background-color: #FFFF00\'>25</span>尾】开</font><font color=\'#FF6600\'>26.32.45</font>准</b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		");
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font size=\'4\' face=\'楷体\'>");
document.writeln("	<b>174期<font color=\'#6600CC\'>【<span style=\'background-color: #FFFF00\'>四尾</span>→拖3<span style=\'background-color: #FFFF00\'>8</span>尾】开</font><font color=\'#FF6600\'>34.18.28</font>准</b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("		");
document.writeln("				<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font size=\'4\' face=\'楷体\'>");
document.writeln("	<b>172期<font color=\'#6600CC\'>【<span style=\'background-color: #FFFF00\'>三尾</span>→拖<span style=\'background-color: #FFFF00\'>1</span>6尾】开</font><font color=\'#FF6600\'>33.31.00</font>准</b></font></table>");
document.writeln("		<!--结束-->");
 
document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font size=\'4\' face=\'楷体\'>");
document.writeln("	<b>169期<font color=\'#6600CC\'>【<span style=\'background-color: #FFFF00\'>四尾</span>→拖38尾】开</font><font color=\'#FF6600\'>04.00.00</font>准</b></font></table>");
document.writeln("		<!--结束-->");

document.writeln("			<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font size=\'4\' face=\'楷体\'>");
document.writeln("	<b>168期<font color=\'#6600CC\'>【<span style=\'background-color: #FFFF00\'>一尾</span>→拖4<span style=\'background-color: #FFFF00\'>8</span>尾】开</font><font color=\'#FF6600\'>21.18.00</font>准</b></font></table>");
document.writeln("		<!--结束-->");
document.writeln("");

document.writeln("		<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font size=\'4\' face=\'楷体\'>");
document.writeln("	<b>167期<font color=\'#6600CC\'>【六尾→拖<span style=\'background-color: #FFFF00\'>25</span>尾】开</font><font color=\'#FF6600\'>32.15.00</font>准</b></font></table>");
document.writeln("		<!--结束-->");

 
document.writeln("		");
document.writeln("<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://j.100tzz.com:100/\' style=\'text-decoration: none\'><img src=/yyy123.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 15pt\'>点击投注澳门六合彩</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>100.cc</font></span></a></strong></tr></table>								");
document.writeln("		</table>");
document.writeln("</div>	");