document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Language\' content=\'zh-cn\'>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("");
document.writeln("<style type=\'text/css\'>");
document.writeln(".stylei {");
document.writeln("	color: #FFFF00;");
document.writeln("	background-color: #000000;");
document.writeln("}");
document.writeln(".stylei {");
document.writeln("	font-size: medium;");
document.writeln("	color: #FFFF00;");
document.writeln("	background-color: #000000;");
document.writeln("}");
document.writeln(".stylezhtw {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln(".style1js547 {");
document.writeln("	background-color: #FFFF00;");
document.writeln("	color: #FF0000;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("  <table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #8bafaf\' bgcolor=#8bafaf height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>战澳团队</font><font color=\'#FFFFFF\'>『综合特码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<script language=\'JavaScript\' type=\'text/javascript\' src=\'/chajiansb.js\' charset=\'utf-8\'></script>");
document.writeln("");
document.writeln("");
document.writeln("<table border=\'1\' width=\'100%\' style=\'box-sizing: border-box; border-collapse: collapse; border-spacing: 0px; margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, 微软雅黑, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;\'>");
document.writeln("	<tbody style=\'box-sizing: border-box;\'>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\' size=\'4\'><b>");
document.writeln("	<font color=\'#0000FF\'>【战澳团队━以&#39;稳&#39;闻名】</font></b></font></table>");
document.writeln("");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font size=\'4\' face=\'楷体\'>");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");

document.writeln("  307期团队十肖：鼠猴马羊虎狗兔猪龙鸡√<br>");
document.writeln("  306期团队十肖：鼠猴蛇马虎狗兔猪牛<span style='background-color: #FFFF00\'>鸡</span>√<br>");
document.writeln("  305期团队十肖：鼠猴马羊虎狗兔龙牛<span style='background-color: #FFFF00\'>鸡</span>√<br>");
document.writeln("  304期团队十肖：<span style='background-color: #FFFF00\'>鼠</span>蛇马羊虎狗猪龙牛鸡√<br>");
document.writeln("  303期团队十肖：猴蛇马猪牛龙<span style='background-color: #FFFF00\'>兔</span>狗鼠羊√<br>");
document.writeln("  302期团队十肖：牛兔猪猴马羊鸡狗鼠龙×<br>");
document.writeln("  301期团队十肖：蛇<span style='background-color: #FFFF00\'>牛</span>鼠虎猪兔羊马猴鸡√<br>");
document.writeln("  300期团队十肖：龙鼠猪蛇猴鸡虎兔狗<span style='background-color: #FFFF00\'>羊</span>√<br>");
document.writeln("  299期团队十肖：兔牛猪羊蛇鸡马<span style='background-color: #FFFF00\'>猴</span>鼠狗√<br>");
document.writeln("  298期团队十肖：<span style='background-color: #FFFF00\'>鸡</span>鼠兔猴马羊虎狗龙蛇√<br>");
document.writeln("  297期团队十肖：牛鸡狗马虎蛇猴兔<span style='background-color: #FFFF00\'>龙</span>羊√<br>");
document.writeln("  296期团队十肖：鼠<span style='background-color: #FFFF00\'>猴</span>蛇羊虎狗兔龙牛鸡√<br>");
document.writeln("  295期团队十肖：鼠猴<span style='background-color: #FFFF00\'>蛇</span>羊虎狗兔龙牛鸡√<br>");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");



document.writeln("  307期团队八尾：01345678√<br>");
document.writeln("  306期团队八尾：023456<span style='background-color: #FFFF00\'>8</span>9√<br>");
document.writeln("  305期团队八尾：01345679×<br>");
document.writeln("  304期团队八尾：4126<span style='background-color: #FFFF00\'>7</span>805√<br>");
document.writeln("  303期团队八尾：012567<span style='background-color: #FFFF00\'>8</span>9√<br>");
document.writeln("  302期团队八尾：023<span style='background-color: #FFFF00\'>4</span>5789√<br>");
document.writeln("  301期团队八尾：01245<span style='background-color: #FFFF00\'>6</span>89√<br>");
document.writeln("  300期团队八尾：1245<span style='background-color: #FFFF00\'>6</span>789√<br>");
document.writeln("  299期团队八尾：0<span style='background-color: #FFFF00\'>1</span>345678√<br>");


document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");



document.writeln("  307期团队四头：0124√<br>");
document.writeln("  306期团队四头：<span style='background-color: #FFFF00\'>0</span>124√<br>");
document.writeln("  305期团队四头：01<span style='background-color: #FFFF00\'>3</span>4√<br>");
document.writeln("  304期团队四头：<span style='background-color: #FFFF00\'>1</span>234√<br>");
document.writeln("  303期团队四头：012<span style='background-color: #FFFF00\'>3</span>√<br>");
document.writeln("  302期团队四头：01<span style='background-color: #FFFF00\'>2</span>4√<br>");
document.writeln("  301期团队四头：2<span style='background-color: #FFFF00\'>1</span>34√<br>");
document.writeln("  300期团队四头：023<span style='background-color: #FFFF00\'>4</span>√<br>");
document.writeln("  299期团队四头：01<span style='background-color: #FFFF00\'>2</span>4√<br>");
document.writeln("  298期团队四头：123<span style='background-color: #FFFF00\'>4</span>√<br>");
document.writeln("  297期团队四头：023<span style='background-color: #FFFF00\'>4</span>√<br>");
document.writeln("  296期团队四头：<span style='background-color: #FFFF00\'>0</span>134√<br>");
document.writeln("  295期团队四头：01<span style='background-color: #FFFF00\'>2</span>3√<br>");
document.writeln("  294期团队四头：012<span style='background-color: #FFFF00\'>4</span>√<br>");




document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  307期团队四行：金木火土√<br>");
document.writeln("  306期团队四行：金水<span style='background-color: #FFFF00\'>火</span>土√<br>");
document.writeln("  305期团队四行：<span style='background-color: #FFFF00\'>金</span>木火土√<br>");
document.writeln("  304期团队四行：木水<span style='background-color: #FFFF00\'>火</span>土√<br>");
document.writeln("  303期团队四行：金木水<span style='background-color: #FFFF00\'>火</span>√<br>");
document.writeln("  302期团队四行：<span style='background-color: #FFFF00\'>金</span>木水火√<br>");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<br>");
document.writeln("");
document.writeln("");
document.writeln("    </font></b></font></table>");
document.writeln("		");
document.writeln("	<!--结束-->");
document.writeln("  ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("");
document.writeln("  ");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("  ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://76891.com/#868627\' style=\'text-decoration: none\'><img src=/yyy123.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 15pt\'>进入澳彩网</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>76891.com</font></span></a></strong></tr></table>		");
document.writeln(" ");
document.writeln("");
document.writeln("</table>");
document.writeln("		</tbody>");