document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Language\' content=\'zh-cn\'>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("");
document.writeln("<style type=\'text/css\'>");
document.writeln(".stylei {");
document.writeln("	color: #FFFF00;");
document.writeln("	background-color: #000000;");
document.writeln("}");
document.writeln(".stylei {");
document.writeln("	font-size: medium;");
document.writeln("	color: #FFFF00;");
document.writeln("	background-color: #000000;");
document.writeln("}");
document.writeln(".stylezhtw {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln(".style1js547 {");
document.writeln("	background-color: #FFFF00;");
document.writeln("	color: #FF0000;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("  <table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #8bafaf\' bgcolor=#8bafaf height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>战澳团队</font><font color=\'#FFFFFF\'>『综合特码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<script language=\'JavaScript\' type=\'text/javascript\' src=\'/chajiansb.js\' charset=\'utf-8\'></script>");
document.writeln("");
document.writeln("");
document.writeln("<table border=\'1\' width=\'100%\' style=\'box-sizing: border-box; border-collapse: collapse; border-spacing: 0px; margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, 微软雅黑, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;\'>");
document.writeln("	<tbody style=\'box-sizing: border-box;\'>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=left><font face=\'楷体\' size=\'4\'><b>");
document.writeln("	<font color=\'#0000FF\'>【战澳团队━以\'稳\'闻名】</font></b></font></table>");
document.writeln("");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=left><b><font size=\'4\' face=\'楷体\'>");
document.writeln("	");




document.writeln("339期团队十肖：牛兔猪猴马羊鸡狗鼠龙<br>");
document.writeln("338期团队十肖：蛇牛鼠虎<span style=\'background-color: #FFFF00\'>猪</span>兔羊马猴鸡<br>");
document.writeln("337期团队十肖：龙<span style=\'background-color: #FFFF00\'>鼠</span>猪蛇猴鸡虎兔狗羊<br>");
document.writeln("336期团队十肖：狗兔<span style=\'background-color: #FFFF00\'>鸡</span>猴羊鼠虎马牛猪<br>");
document.writeln("335期团队十肖：猴蛇马猪牛<span style=\'background-color: #FFFF00\'>龙</span>兔狗鼠羊<br>");
document.writeln("334期团队十肖：兔牛猪羊蛇鸡马猴鼠<span style=\'background-color: #FFFF00\'>狗</span><br>");
document.writeln("333期团队十肖：鸡鼠兔猴马羊<span style=\'background-color: #FFFF00\'>兔</span>狗龙蛇<br>");
document.writeln("332期团队十肖：牛鸡狗马虎蛇<span style=\'background-color: #FFFF00\'>猴</span>兔龙羊<br>");
document.writeln("328期团队十肖：鼠猴蛇马虎狗<span style=\'background-color: #FFFF00\'>兔</span>猪牛鸡<br>");
document.writeln("327期团队十肖：鼠猴马<span style=\'background-color: #FFFF00\'>羊</span>虎狗兔龙牛鸡<br>");
document.writeln("326期团队十肖：鼠<span style=\'background-color: #FFFF00\'>蛇</span>马羊虎狗猪龙牛鸡<br>");
document.writeln("325期团队十肖：牛兔猪猴马羊<span style=\'background-color: #FFFF00\'>鸡</span>狗鼠龙<br>");
document.writeln("324期团队十肖：蛇牛鼠<span style=\'background-color: #FFFF00\'>虎</span>猪兔羊马猴鸡<br>");
document.writeln("323期团队十肖：龙鼠猪蛇猴鸡<span style=\'background-color: #FFFF00\'>虎</span>兔狗羊<br>");
document.writeln("322期团队十肖：狗兔鸡<span style=\'background-color: #FFFF00\'>猴</span>羊鼠虎马牛猪<br>");
document.writeln("320期团队十肖：兔牛猪羊<span style=\'background-color: #FFFF00\'>蛇</span>鸡马猴鼠狗<br>");
document.writeln("319期团队十肖：鸡鼠兔猴马羊虎<span style=\'background-color: #FFFF00\'>狗</span>龙蛇<br>");
document.writeln("318期团队十肖：牛鸡狗马虎蛇猴<span style=\'background-color: #FFFF00\'>兔</span>龙羊<br>");
document.writeln("316期团队十肖：<span style=\'background-color: #FFFF00\'>龙</span>牛马羊虎猪鼠鸡猴蛇<br>");
document.writeln("315期团队十肖：鼠猴马羊虎狗兔<span style=\'background-color: #FFFF00\'>猪</span>龙鸡<br>");
document.writeln("314期团队十肖：鼠猴蛇马<span style=\'background-color: #FFFF00\'>虎</span>狗兔猪牛鸡<br>");

document.writeln("313期团队十肖：鼠猴<span style=\'background-color: #FFFF00\'>马</span>羊虎狗兔龙牛鸡<br>");
document.writeln("312期团队十肖：鼠蛇马羊虎狗<span style=\'background-color: #FFFF00\'>猪</span>龙牛鸡<br>");
document.writeln("311期团队十肖：牛兔猪猴马羊鸡<span style=\'background-color: #FFFF00\'>狗</span>鼠龙<br>");
document.writeln("310期团队十肖：蛇牛鼠虎猪<span style=\'background-color: #FFFF00\'>兔</span>羊马猴鸡<br>");
document.writeln("309期团队十肖：龙<span style=\'background-color: #FFFF00\'>鼠</span>猪蛇猴鸡虎兔狗羊<br>");
document.writeln("307期团队十肖：猴蛇马猪牛龙兔狗<span style=\'background-color: #FFFF00\'>鼠</span>羊<br>");
document.writeln("306期团队十肖：兔牛猪羊蛇鸡马猴<span style=\'background-color: #FFFF00\'>鼠</span>狗<br>");
document.writeln("305期团队十肖：鸡鼠兔猴<span style=\'background-color: #FFFF00\'>马</span>羊虎狗龙蛇<br>");
document.writeln("303期团队十肖：鼠猴蛇羊虎狗兔龙<span style=\'background-color: #FFFF00\'>牛</span>鸡<br>");
document.writeln("302期团队十肖：龙牛马羊虎猪鼠鸡<span style=\'background-color: #FFFF00\'>猴</span>蛇<br>");
document.writeln("301期团队十肖：鼠猴马羊虎狗<span style=\'background-color: #FFFF00\'>兔</span>猪龙鸡<br>");
document.writeln("299期团队十肖：鼠猴马羊虎狗兔<span style=\'background-color: #FFFF00\'>龙</span>牛鸡<br>");
document.writeln("297期团队十肖：<span style=\'background-color: #FFFF00\'>牛</span>兔猪猴马羊鸡狗鼠龙<br>");
document.writeln("296期团队十肖：蛇牛鼠虎猪兔羊马<span style=\'background-color: #FFFF00\'>猴</span>鸡<br>");
document.writeln("295期团队十肖：龙鼠猪蛇<span style=\'background-color: #FFFF00\'>猴</span>鸡虎兔狗羊<br>");


document.writeln("");
document.writeln("");
document.writeln("<br>");



document.writeln("339期团队八尾：02345789<br>");
document.writeln("338期团队八尾：0<span style=\'background-color: #FFFF00\'>1</span>245689<br>");
document.writeln("337期团队八尾：1245<span style=\'background-color: #FFFF00\'>6</span>789<br>");
document.writeln("336期团队八尾：<span style=\'background-color: #FFFF00\'>1</span>2346789<br>");
document.writeln("334期团队八尾：01345<span style=\'background-color: #FFFF00\'>6</span>78<br>");
document.writeln("333期团队八尾：123567<span style=\'background-color: #FFFF00\'>7</span>9<br>");
document.writeln("332期团队八尾：012457<span style=\'background-color: #FFFF00\'>8</span>9<br>");
document.writeln("331期团队八尾：01235<span style=\'background-color: #FFFF00\'>6</span>79<br>");
document.writeln("330期团队八尾：013457<span style=\'background-color: #FFFF00\'>8</span>9<br>");
document.writeln("329期团队八尾：0134<span style=\'background-color: #FFFF00\'>5</span>678<br>");
document.writeln("327期团队八尾：0<span style=\'background-color: #FFFF00\'>1</span>345679<br>");
document.writeln("326期团队八尾：014<span style=\'background-color: #FFFF00\'>5</span>6789<br>");
document.writeln("325期团队八尾：02345<span style=\'background-color: #FFFF00\'>7</span>89<br>");
document.writeln("324期团队八尾：01245<span style=\'background-color: #FFFF00\'>6</span>89<br>");
document.writeln("323期团队八尾：1<span style=\'background-color: #FFFF00\'>2</span>456789<br>");
document.writeln("322期团队八尾：1<span style=\'background-color: #FFFF00\'>2</span>346789<br>");
document.writeln("321期团队八尾：0125678<span style=\'background-color: #FFFF00\'>9</span><br>");

document.writeln("320期团队八尾：01<span style=\'background-color: #FFFF00\'>3</span>45678<br>");
document.writeln("319期团队八尾：1<span style=\'background-color: #FFFF00\'>2</span>356789<br>");
document.writeln("318期团队八尾：0124578<span style=\'background-color: #FFFF00\'>9</span><br>");

document.writeln("317期团队八尾：0<span style=\'background-color: #FFFF00\'>1</span>235679<br>");
document.writeln("316期团队八尾：013457<span style=\'background-color: #FFFF00\'>8</span>9<br>");

document.writeln("315期团队八尾：0134<span style=\'background-color: #FFFF00\'>9</span>678<br>");
document.writeln("314期团队八尾：02345<span style=\'background-color: #FFFF00\'>6</span>89<br>");

document.writeln("313期团队八尾：<span style=\'background-color: #FFFF00\'>0</span>1345679<br>");
document.writeln("312期团队八尾：014<span style=\'background-color: #FFFF00\'>5</span>6789<br>");
document.writeln("311期团队八尾：<span style=\'background-color: #FFFF00\'>0</span>2345789<br>");
document.writeln("309期团队八尾：1245<span style=\'background-color: #FFFF00\'>6</span>789<br>");
document.writeln("308期团队八尾：123467<span style=\'background-color: #FFFF00\'>8</span>9<br>");
document.writeln("307期团队八尾：0125<span style=\'background-color: #FFFF00\'>6</span>789<br>");
document.writeln("306期团队八尾：0134567<span style=\'background-color: #FFFF00\'>8</span><br>");
document.writeln("304期团队八尾：012457<span style=\'background-color: #FFFF00\'>8</span>9<br>");
document.writeln("303期团队八尾：0123<span style=\'background-color: #FFFF00\'>5</span>679<br>");
document.writeln("301期团队八尾：0134<span style=\'background-color: #FFFF00\'>5</span>678<br>");
document.writeln("300期团队八尾：02345<span style=\'background-color: #FFFF00\'>6</span>89<br>");
document.writeln("299期团队八尾：013<span style=\'background-color: #FFFF00\'>4</span>5679<br>");
document.writeln("297期团队八尾：0234578<span style=\'background-color: #FFFF00\'>9</span><br>");
document.writeln("296期团队八尾：<span style=\'background-color: #FFFF00\'>0</span>1245689<br>");
document.writeln("295期团队八尾：12<span style=\'background-color: #FFFF00\'>4</span>56789<br>");
document.writeln("293期团队八尾：<span style=\'background-color: #FFFF00\'>0</span>1256789<br>");
document.writeln("292期团队八尾：0134<span style=\'background-color: #FFFF00\'>5</span>678<br>");
document.writeln("291期团队八尾：123567<span style=\'background-color: #FFFF00\'>8</span>9<br>");
document.writeln("290期团队八尾：01<span style=\'background-color: #FFFF00\'>2</span>45789<br>");
document.writeln("289期团队八尾：0<span style=\'background-color: #FFFF00\'>1</span>235679<br>");
document.writeln("288期团队八尾：01<span style=\'background-color: #FFFF00\'>3</span>45789<br>");
document.writeln("286期团队八尾：0234568<span style=\'background-color: #FFFF00\'>9</span><br>");
document.writeln("285期团队八尾：0<span style=\'background-color: #FFFF00\'>1</span>345679<br>");
document.writeln("284期团队八尾：0145<span style=\'background-color: #FFFF00\'>6</span>789<br>");
document.writeln("283期团队八尾：02<span style=\'background-color: #FFFF00\'>3</span>45789<br>");
document.writeln("282期团队八尾：012456<span style=\'background-color: #FFFF00\'>8</span>9<br>");
document.writeln("281期团队八尾：1245<span style=\'background-color: #FFFF00\'>6</span>789<br>");
document.writeln("280期团队八尾：1234<span style=\'background-color: #FFFF00\'>6</span>789<br>");
document.writeln("279期团队八尾：<span style=\'background-color: #FFFF00\'>0</span>1256789<br>");
document.writeln("277期团队八尾：123567<span style=\'background-color: #FFFF00\'>8</span>9<br>");
document.writeln("276期团队八尾：012457<span style=\'background-color: #FFFF00\'>8</span>9<br>");
document.writeln("275期团队八尾：<span style=\'background-color: #FFFF00\'>0</span>1235679<br>");
document.writeln("274期团队八尾：01<span style=\'background-color: #FFFF00\'>3</span>45789<br>");
document.writeln("273期团队八尾：0134567<span style=\'background-color: #FFFF00\'>8</span><br>");
document.writeln("271期团队八尾：0134567<span style=\'background-color: #FFFF00\'>9</span><br>");
document.writeln("270期团队八尾：014567<span style=\'background-color: #FFFF00\'>8</span>9<br>");
document.writeln("269期团队八尾：02<span style=\'background-color: #FFFF00\'>3</span>45789<br>");
document.writeln("267期团队八尾：1<span style=\'background-color: #FFFF00\'>2</span>456789<br>");
document.writeln("266期团队八尾：1<span style=\'background-color: #FFFF00\'>2</span>346789<br>");
document.writeln("265期团队八尾：012<span style=\'background-color: #FFFF00\'>5</span>6789<br>");
document.writeln("");
document.writeln("");
document.writeln("<br>");



document.writeln("339期团队四头：0124<br>");
document.writeln("338期团队四头：213<span style=\'background-color: #FFFF00\'>4</span><br>");
document.writeln("335期团队四头：01<span style=\'background-color: #FFFF00\'>2</span>3<br>");
document.writeln("334期团队四头：<span style=\'background-color: #FFFF00\'>0</span>124<br>");
document.writeln("333期团队四头：12<span style=\'background-color: #FFFF00\'>3</span>4<br>");
document.writeln("332期团队四头：<span style=\'background-color: #FFFF00\'>0</span>234<br>");
document.writeln("330期团队四头：0<span style=\'background-color: #FFFF00\'>1</span>23<br>");
document.writeln("328期团队四头：<span style=\'background-color: #FFFF00\'>0</span>124<br>");
document.writeln("326期团队四头：12<span style=\'background-color: #FFFF00\'>3</span>4<br>");
document.writeln("325期团队四头：<span style=\'background-color: #FFFF00\'>0</span>124<br>");
document.writeln("324期团队四头：<span style=\'background-color: #FFFF00\'>2</span>134<br>");
document.writeln("323期团队四头：<span style=\'background-color: #FFFF00\'>0</span>234<br>");
document.writeln("321期团队四头：0<span style=\'background-color: #FFFF00\'>1</span>23<br>");
document.writeln("320期团队四头：01<span style=\'background-color: #FFFF00\'>2</span>4<br>");
document.writeln("319期团队四头：123<span style=\'background-color: #FFFF00\'>4</span><br>");
document.writeln("318期团队四头：023<span style=\'background-color: #FFFF00\'>4</span><br>");
document.writeln("315期团队四头：01<span style=\'background-color: #FFFF00\'>2</span>4<br>");
document.writeln("314期团队四头：01<span style=\'background-color: #FFFF00\'>2</span>4<br>");

document.writeln("313期团队四头：0<span style=\'background-color: #FFFF00\'>1</span>34<br>");
document.writeln("310期团队四头：2<span style=\'background-color: #FFFF00\'>1</span>34<br>");
document.writeln("308期团队四头：012<span style=\'background-color: #FFFF00\'>4</span><br>");
document.writeln("307期团队四头：0<span style=\'background-color: #FFFF00\'>1</span>23<br>");
document.writeln("306期团队四头：01<span style=\'background-color: #FFFF00\'>2</span>4<br>");
document.writeln("305期团队四头：12<span style=\'background-color: #FFFF00\'>3</span>4<br>");
document.writeln("304期团队四头：0<span style=\'background-color: #FFFF00\'>2</span>34<br>");
document.writeln("303期团队四头：0<span style=\'background-color: #FFFF00\'>1</span>23<br>");
document.writeln("302期团队四头：012<span style=\'background-color: #FFFF00\'>3</span><br>");
document.writeln("301期团队四头：01<span style=\'background-color: #FFFF00\'>2</span>4<br>");
document.writeln("298期团队四头：12<span style=\'background-color: #FFFF00\'>3</span>4<br>");
document.writeln("296期团队四头：<span style=\'background-color: #FFFF00\'>2</span>134<br>");
document.writeln("295期团队四头：023<span style=\'background-color: #FFFF00\'>4</span><br>");
document.writeln("293期团队四头：01<span style=\'background-color: #FFFF00\'>2</span>3<br>");
document.writeln("292期团队四头：01<span style=\'background-color: #FFFF00\'>2</span>4<br>");
document.writeln("291期团队四头：123<span style=\'background-color: #FFFF00\'>4</span><br>");
document.writeln("290期团队四头：023<span style=\'background-color: #FFFF00\'>4</span><br>");
document.writeln("289期团队四头：01<span style=\'background-color: #FFFF00\'>2</span>3<br>");
document.writeln("288期团队四头：01<span style=\'background-color: #FFFF00\'>2</span>3<br>");
document.writeln("286期团队四头：0<span style=\'background-color: #FFFF00\'>1</span>24<br>");
document.writeln("285期团队四头：013<span style=\'background-color: #FFFF00\'>4</span><br>");
document.writeln("");
document.writeln("");
document.writeln("<br>");
document.writeln("");



document.writeln("339期团队四行：金木水火<br>");
document.writeln("338期团队四行：金木<span style=\'background-color: #FFFF00\'>水</span>土<br>");
document.writeln("337期团队四行：金水<span style=\'background-color: #FFFF00\'>火</span>土<br>");

document.writeln("336期团队四行：<span style=\'background-color: #FFFF00\'>金</span>水火土<br>");
document.writeln("335期团队四行：<span style=\'background-color: #FFFF00\'>金</span>木水火<br>");
document.writeln("333期团队四行：金木<span style=\'background-color: #FFFF00\'>火</span>土<br>");

document.writeln("332期团队四行：木水<span style=\'background-color: #FFFF00\'>火</span>土<br>");
document.writeln("331期团队四行：金木水<span style=\'background-color: #FFFF00\'>火</span><br>");
document.writeln("330期团队四行：木水火<span style=\'background-color: #FFFF00\'>土</span><br>");
document.writeln("329期团队四行：金<span style=\'background-color: #FFFF00\'>木</span>火土<br>");
document.writeln("328期团队四行：<span style=\'background-color: #FFFF00\'>金</span>水火土<br>");
document.writeln("327期团队四行：<span style=\'background-color: #FFFF00\'>金</span>木火土<br>");
document.writeln("325期团队四行：金木水<span style=\'background-color: #FFFF00\'>火</span><br>");
document.writeln("324期团队四行：金木水<span style=\'background-color: #FFFF00\'>土</span><br>");
document.writeln("323期团队四行：<span style=\'background-color: #FFFF00\'>金</span>水火土<br>");
document.writeln("322期团队四行：<span style=\'background-color: #FFFF00\'>金</span>水火土<br>");
document.writeln("321期团队四行：金木<span style=\'background-color: #FFFF00\'>水</span>火<br>");
document.writeln("320期团队四行：<span style=\'background-color: #FFFF00\'>金</span>水火土<br>");
document.writeln("318期团队四行：木<span style=\'background-color: #FFFF00\'>水</span>火土<br>");
document.writeln("317期团队四行：金木<span style=\'background-color: #FFFF00\'>水</span>火<br>");
document.writeln("316期团队四行：木水火<span style=\'background-color: #FFFF00\'>土</span><br>");

document.writeln("315期团队四行：金木<span style=\'background-color: #FFFF00\'>火</span>土<br>");

document.writeln("314期团队四行：金水火<span style=\'background-color: #FFFF00\'>土</span><br>");
document.writeln("313期团队四行：<span style=\'background-color: #FFFF00\'>金</span>木火土<br>");
document.writeln("312期团队四行：<span style=\'background-color: #FFFF00\'>木</span>水火土<br>");
document.writeln("311期团队四行：金木水<span style=\'background-color: #FFFF00\'>火</span><br>");
document.writeln("310期团队四行：金<span style=\'background-color: #FFFF00\'>木</span>水土<br>");
document.writeln("309期团队四行：金水<span style=\'background-color: #FFFF00\'>火</span>土<br>");
document.writeln("308期团队四行：金水火<span style=\'background-color: #FFFF00\'>土</span><br>");
document.writeln("307期团队四行：金木水<span style=\'background-color: #FFFF00\'>火</span><br>");
document.writeln("306期团队四行：金<span style=\'background-color: #FFFF00\'>水</span>火土<br>");
document.writeln("305期团队四行：金木火<span style=\'background-color: #FFFF00\'>土</span><br>");
document.writeln("304期团队四行：木<span style=\'background-color: #FFFF00\'>水</span>火土<br>");
document.writeln("303期团队四行：金木水<span style=\'background-color: #FFFF00\'>火</span><br>");
document.writeln("301期团队四行：金木火<span style=\'background-color: #FFFF00\'>土</span><br>");
document.writeln("299期团队四行：<span style=\'background-color: #FFFF00\'>金</span>木火土<br>");
document.writeln("297期团队四行：<span style=\'background-color: #FFFF00\'>金</span>木水火<br>");
document.writeln("296期团队四行：金木<span style=\'background-color: #FFFF00\'>水</span>土<br>");
document.writeln("293期团队四行：金木<span style=\'background-color: #FFFF00\'>水</span>火<br>");
document.writeln("292期团队四行：金水火<span style=\'background-color: #FFFF00\'>土</span><br>");
document.writeln("291期团队四行：金木火<span style=\'background-color: #FFFF00\'>土</span><br>");
document.writeln("290期团队四行：木<span style=\'background-color: #FFFF00\'>水</span>火土<br>");
document.writeln("289期团队四行：金<span style=\'background-color: #FFFF00\'>木</span>水火<br>");
document.writeln("288期团队四行：<span style=\'background-color: #FFFF00\'>金</span>木火土<br>");
document.writeln("287期团队四行：<span style=\'background-color: #FFFF00\'>金</span>木火土<br>");
document.writeln("286期团队四行：金<span style=\'background-color: #FFFF00\'>水</span>火土<br>");
document.writeln("284期团队四行：<span style=\'background-color: #FFFF00\'>木</span>水火土<br>");
document.writeln("281期团队四行：金水<span style=\'background-color: #FFFF00\'>火</span>土<br>");
document.writeln("280期团队四行：金水<span style=\'background-color: #FFFF00\'>火</span>土<br>");
document.writeln("279期团队四行：<span style=\'background-color: #FFFF00\'>金</span>木水火<br>");
document.writeln("278期团队四行：<span style=\'background-color: #FFFF00\'>金</span>水火土<br>");
document.writeln("277期团队四行：金木火<span style=\'background-color: #FFFF00\'>土</span><br>");
document.writeln("276期团队四行：木水<span style=\'background-color: #FFFF00\'>火</span>土<br>");
document.writeln("275期团队四行：<span style=\'background-color: #FFFF00\'>金</span>木水火<br>");
document.writeln("274期团队四行：金<span style=\'background-color: #FFFF00\'>木</span>火土<br>");
document.writeln("272期团队四行：金<span style=\'background-color: #FFFF00\'>水</span>火土<br>");
document.writeln("271期团队四行：<span style=\'background-color: #FFFF00\'>金</span>木火土<br>");
document.writeln("270期团队四行：木水<span style=\'background-color: #FFFF00\'>火</span>土<br>");
document.writeln("269期团队四行：金<span style=\'background-color: #FFFF00\'>木</span>水火<br>");
document.writeln("268期团队四行：金木水<span style=\'background-color: #FFFF00\'>土</span><br>");
document.writeln("267期团队四行：<span style=\'background-color: #FFFF00\'>金</span>水火土<br>");
document.writeln("266期团队四行：<span style=\'background-color: #FFFF00\'>金</span>水火土<br>");
document.writeln("");
document.writeln("<br>");
document.writeln("");
document.writeln("");
document.writeln("    </font></b></font></table>");
document.writeln("		");
document.writeln("	<!--结束-->");
document.writeln("  ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("");
document.writeln("  ");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("  ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://61269c.com/#868627\' style=\'text-decoration: none\'><img src=/yyy123.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 15pt\'>进入澳彩网</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>61269c.com</font></span></a></strong></tr></table>		");
document.writeln(" ");
document.writeln("");
document.writeln("</table>");
document.writeln("		</tbody>");