document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Language\' content=\'zh-cn\'>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("");
document.writeln("<style type=\'text/css\'>");
document.writeln(".stylei {");
document.writeln("	color: #FFFF00;");
document.writeln("	background-color: #000000;");
document.writeln("}");
document.writeln(".stylei {");
document.writeln("	font-size: medium;");
document.writeln("	color: #FFFF00;");
document.writeln("	background-color: #000000;");
document.writeln("}");
document.writeln(".stylezhtw {");
document.writeln("	background-color: #FFFF00;");
document.writeln("}");
document.writeln(".style1js547 {");
document.writeln("	background-color: #FFFF00;");
document.writeln("	color: #FF0000;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("  <table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #8bafaf\' bgcolor=#8bafaf height=50><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 20pt\'><font color=\'#FFFF00\'>战澳团队</font><font color=\'#FFFFFF\'>『综合特码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<script language=\'JavaScript\' type=\'text/javascript\' src=\'/chajiansb.js\' charset=\'utf-8\'></script>");
document.writeln("");
document.writeln("");
document.writeln("<table border=\'1\' width=\'100%\' style=\'box-sizing: border-box; border-collapse: collapse; border-spacing: 0px; margin: 0px; padding: 0px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, 微软雅黑, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;\'>");
document.writeln("	<tbody style=\'box-sizing: border-box;\'>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><font face=\'楷体\' size=\'4\'><b>");
document.writeln("	<font color=\'#0000FF\'>【战澳团队━以&#39;稳&#39;闻名】</font></b></font></table>");
document.writeln("");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff><tbody><tr>");
document.writeln("	<td width=100% height=40><p align=center><b><font size=\'4\' face=\'楷体\'>");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  257期团队十肖：鼠猴蛇羊虎狗兔龙牛鸡√<br>");
document.writeln("  256期团队十肖：鼠猴蛇羊<span style='background-color: #FFFF00\'>虎</span>狗兔龙牛鸡√<br>");
document.writeln("  255期团队十肖：鼠猴马羊虎狗兔<span style='background-color: #FFFF00\'>猪</span>龙鸡√<br>");
document.writeln("  254期团队十肖：鼠猴蛇马<span style='background-color: #FFFF00\'>虎</span>狗兔猪牛鸡√<br>");
document.writeln("  253期团队十肖：鼠猴<span style='background-color: #FFFF00\'>马</span>羊虎狗兔龙牛鸡√<br>");
document.writeln("  252期团队十肖：鼠<span style='background-color: #FFFF00\'>蛇</span>马羊虎狗猪龙牛鸡√<br>");
document.writeln("  251期团队十肖：猴蛇马猪牛龙<span style='background-color: #FFFF00\'>兔</span>狗鼠羊√<br>");
document.writeln("  250期团队十肖：牛兔猪猴马羊鸡狗鼠龙×<br>");
document.writeln("  249期团队十肖：蛇牛鼠虎猪兔羊马猴<span style='background-color: #FFFF00\'>鸡</span>√<br>");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");

document.writeln("  257期团队八尾：01234789√<br>");
document.writeln("  256期团队八尾：0123567<span style='background-color: #FFFF00\'>9</span>√<br>");
document.writeln("  255期团队八尾：<span style='background-color: #FFFF00\'>0</span>1345678√<br>");
document.writeln("  253期团队八尾：013456<span style='background-color: #FFFF00\'>7</span>9√<br>");
document.writeln("  252期团队八尾：0145<span style='background-color: #FFFF00\'>6</span>789√<br>");
document.writeln("  251期团队八尾：01256789×<br>");
document.writeln("  250期团队八尾：023<span style='background-color: #FFFF00\'>4</span>5789√<br>");
document.writeln("  249期团队八尾：01<span style='background-color: #FFFF00\'>2</span>45689√<br>");
document.writeln("  248期团队八尾：<span style='background-color: #FFFF00\'>1</span>2456789√<br>");
document.writeln("  247期团队八尾：0<span style='background-color: #FFFF00\'>1</span>345678√<br>");
document.writeln("  246期团队八尾：123<span style='background-color: #FFFF00\'>5</span>6789√<br>");
document.writeln("  245期团队八尾：01245<span style='background-color: #FFFF00\'>7</span>89√<br>");
document.writeln("  244期团队八尾：012<span style='background-color: #FFFF00\'>3</span>4789√<br>");
document.writeln("  243期团队八尾：0<span style='background-color: #FFFF00\'>1</span>235679√<br>");
document.writeln("  242期团队八尾：<span style='background-color: #FFFF00\'>0</span>1345678√<br>");
document.writeln("  241期团队八尾：023<span style='background-color: #FFFF00\'>4</span>5689√<br>");
document.writeln("  240期团队八尾：013<span style='background-color: #FFFF00\'>4</span>5679√<br>");
document.writeln("  239期团队八尾：0<span style='background-color: #FFFF00\'>1</span>456789√<br>");
document.writeln("  238期团队八尾：012567<span style='background-color: #FFFF00\'>8</span>9√<br>");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");


document.writeln("  257期团队四头：0134√<br>");
document.writeln("  256期团队四头：012<span style='background-color: #FFFF00\'>3</span>√<br>");
document.writeln("  255期团队四头：0124×<br>");
document.writeln("  254期团队四头：01<span style='background-color: #FFFF00\'>2</span>4√<br>");
document.writeln("  253期团队四头：013<span style='background-color: #FFFF00\'>4</span>√<br>");
document.writeln("  252期团队四头：12<span style='background-color: #FFFF00\'>3</span>4√<br>");
document.writeln("  251期团队四头：0<span style='background-color: #FFFF00\'>1</span>23√<br>");
document.writeln("  250期团队四头：01<span style='background-color: #FFFF00\'>2</span>4√<br>");
document.writeln("  249期团队四头：21<span style='background-color: #FFFF00\'>3</span>4√<br>");



document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<br>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");








document.writeln("  257期团队四行：金木火土√<br>");
document.writeln("  256期团队四行：金木水<span style='background-color: #FFFF00\'>火</span>√<br>");
document.writeln("  255期团队四行：金木<span style='background-color: #FFFF00\'>火</span>土√<br>");
document.writeln("  254期团队四行：金水火<span style='background-color: #FFFF00\'>土</span>√<br>");
document.writeln("  253期团队四行：金木<span style='background-color: #FFFF00\'>火</span>土√<br>");
document.writeln("  252期团队四行：<span style='background-color: #FFFF00\'>木</span>水火土√<br>");
document.writeln("  251期团队四行：金<span style='background-color: #FFFF00\'>木</span>水火√<br>");
document.writeln("  250期团队四行：<span style='background-color: #FFFF00\'>金</span>木水火√<br>");
document.writeln("  249期团队四行：<span style='background-color: #FFFF00\'>金</span>木水土√<br>");
document.writeln("  248期团队四行：<span style='background-color: #FFFF00\'>金</span>水火土√<br>");
document.writeln("  247期团队四行：金水<span style='background-color: #FFFF00\'>火</span>土√<br>");
document.writeln("  246期团队四行：金<span style='background-color: #FFFF00\'>木</span>火土√<br>");
document.writeln("  245期团队四行：木水<span style='background-color: #FFFF00\'>火</span>土√<br>");
document.writeln("  244期团队四行：<span style='background-color: #FFFF00\'>金</span>木火土√<br>");
document.writeln("  243期团队四行：金木水<span style='background-color: #FFFF00\'>火</span>√<br>");
document.writeln("  242期团队四行：金木<span style='background-color: #FFFF00\'>火</span>土√<br>");
document.writeln("  241期团队四行：金水火<span style='background-color: #FFFF00\'>土</span>√<br>");
document.writeln("  240期团队四行：<span style='background-color: #FFFF00\'>金</span>木火土√<br>");
document.writeln("  239期团队四行：木水<span style='background-color: #FFFF00\'>火</span>土√<br>");

document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<br>");
document.writeln("");
document.writeln("");
document.writeln("    </font></b></font></table>");
document.writeln("		");
document.writeln("	<!--结束-->");
document.writeln("  ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  ");
document.writeln("");
document.writeln("  ");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("  ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table style=border-collapse:collapse border=0 width=100%><tbody><tr><td height=40><p style=text-align:center><strong>");
document.writeln("			<a target=\'_blank\' href=\'https://76891.com/#868627\' style=\'text-decoration: none\'><img src=/yyy123.gif style=\'width:20px\' height=\'19\'><span style=font-family:楷体;color:#00f><font style=\'font-size: 15pt\'>进入澳彩网</font></span><span style=font-family:楷体;font-size:17pt;><font color=\'#FF0000\'>76891.com</font></span></a></strong></tr></table>		");
document.writeln(" ");
document.writeln("");
document.writeln("</table>");
document.writeln("		</tbody>");