document.writeln("	<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100% height=\'229\'>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>马会传真</font><font color=\'#FFFFFF\'>『输尽光玄机』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("   <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'><b><font color=\'#000000\'>067期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'5\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开？00中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=45 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' size=\'4\' face=\'微软雅黑\'>今期买龙猴输尽光，大数单今期不能买 </font>  ");
document.writeln("		</span> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=43 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("		<font size=\'4\' color=\'#0000FF\' face=\'微软雅黑\'>有钱不买红波单，特码就买家禽狗猪</font><font size=\'4\'>");
document.writeln("		</font></span> </td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->");
document.writeln("    ");
document.writeln("    ");
document.writeln("    ");
document.writeln("       <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'><b><font color=\'#000000\'>066期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'5\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开狗42中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=45 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' size=\'4\' face=\'微软雅黑\'>今期买牛蛇输尽光，大数单今期不能买 </font>  ");
document.writeln("		</span> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=43 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("		<font size=\'4\' color=\'#0000FF\' face=\'微软雅黑\'>有钱不买绿波单，特码就买野兽兔虎</font><font size=\'4\'>");
document.writeln("		</font></span> </td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("    ");
document.writeln("    ");
document.writeln("    ");
document.writeln("    ");
document.writeln("       <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'><b><font color=\'#000000\'>065期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'5\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开羊09中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=45 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' size=\'4\' face=\'微软雅黑\'>今期买<span style=\'background-color: #FFFF00\'>猪蛇</span>输尽光，<span style=\'background-color: #FFFF00\'>小数双</span>今期不能买 </font>  ");
document.writeln("		</span> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=43 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("		<font size=\'4\' color=\'#0000FF\' face=\'微软雅黑\'>有钱不买<span style=\'background-color: #FFFF00\'>蓝波双</span>，特码就买野兽兔龙</font><font size=\'4\'>");
document.writeln("		</font></span> </td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("    ");
document.writeln("    ");
document.writeln("       <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'><b><font color=\'#000000\'>063期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'5\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开猴32中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=45 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' size=\'4\' face=\'微软雅黑\'>今期买<span style=\'background-color: #FFFF00\'>虎猪</span>输尽光，<span style=\'background-color: #FFFF00\'>大数单</span>今期不能买 </font>  ");
document.writeln("		</span> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=43 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("		<font size=\'4\' color=\'#0000FF\' face=\'微软雅黑\'>有钱不买绿波双，特码就买<span style=\'background-color: #FFFF00\'>野兽</span>鼠<span style=\'background-color: #FFFF00\'>猴</span></font><font size=\'4\'>");
document.writeln("		</font></span> </td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("    ");
document.writeln("    ");
document.writeln("   <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'><b><font color=\'#000000\'>061期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'5\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开马46中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=45 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' size=\'4\' face=\'微软雅黑\'>今期买<span style=\'background-color: #FFFF00\'>鸡猪</span>输尽光，<span style=\'background-color: #FFFF00\'>小数单</span>今期不能买 </font>  ");
document.writeln("		</span> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=43 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("		<font size=\'4\' color=\'#0000FF\' face=\'微软雅黑\'>有钱不买<span style=\'background-color: #FFFF00\'>绿波双</span>，特码就买<span style=\'background-color: #FFFF00\'>家禽</span>牛狗</font><font size=\'4\'>");
document.writeln("		</font></span> </td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("    ");
document.writeln("    ");
document.writeln("    ");
document.writeln("       <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'><b><font color=\'#000000\'>060期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'5\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开鼠04中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=45 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' size=\'4\' face=\'微软雅黑\'>今期买<span style=\'background-color: #FFFF00\'>猴猪</span>输尽光，<span style=\'background-color: #FFFF00\'>大数双</span>今期不能买 </font>  ");
document.writeln("		</span> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=43 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("		<font size=\'4\' color=\'#0000FF\' face=\'微软雅黑\'>有钱不买<span style=\'background-color: #FFFF00\'>蓝波单</span>，特码就买<span style=\'background-color: #FFFF00\'>野兽鼠</span>兔</font><font size=\'4\'>");
document.writeln("		</font></span> </td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("    ");
document.writeln("    ");
document.writeln("    ");
document.writeln("       <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'><b><font color=\'#000000\'>059期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'5\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开牛39中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=45 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' size=\'4\' face=\'微软雅黑\'>今期买<span style=\'background-color: #FFFF00\'>狗猴</span>输尽光，<span style=\'background-color: #FFFF00\'>大数双</span>今期不能买 </font>  ");
document.writeln("		</span> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=43 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("		<font size=\'4\' color=\'#0000FF\' face=\'微软雅黑\'>有钱不买<span style=\'background-color: #FFFF00\'>红波单</span>，特码就买野兽龙蛇</font><font size=\'4\'>");
document.writeln("		</font></span> </td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("    ");
document.writeln("    ");
document.writeln("    ");
document.writeln("   <!--开始--> ");
document.writeln("    <tr>");
document.writeln("      <td align=\'left\' height=42 bgcolor=\'#FFFFFF\' ><p align=\'center\'>");
document.writeln("");
document.writeln("		<font size=\'4\' face=\'微软雅黑\'><b><font color=\'#000000\'>058期</font></b></font><b><font color=\'#FF0000\' face=\'隶书\' size=\'5\'>输尽光玄机</font><font color=\'#000000\' size=\'4\' face=\'微软雅黑\'>开兔49中</font><font size=\'4\' face=\'微软雅黑\'>");
document.writeln("		</font>  ");
document.writeln("		</b>  ");
document.writeln("		</td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=45 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("");
document.writeln("		<font color=\'#0000FF\' size=\'4\' face=\'微软雅黑\'>今期买<span style=\'background-color: #FFFF00\'>龙猪</span>输尽光，<span style=\'background-color: #FFFF00\'>小数双</span>今期不能买 </font>  ");
document.writeln("		</span> </td>");
document.writeln("    </tr>");
document.writeln("	<tr>");
document.writeln("      <td height=43 bgcolor=\'#FFFFFF\' align=\'center\' >");
document.writeln("		<span style=\'font-weight: 400\'>");
document.writeln("		<font size=\'4\' color=\'#0000FF\' face=\'微软雅黑\'>有钱不买<span style=\'background-color: #FFFF00\'>绿波双</span>，特码就买家禽羊狗</font><font size=\'4\'>");
document.writeln("		</font></span> </td>");
document.writeln("    </tr>        ");
document.writeln("    <!--结束-->");
document.writeln("");
document.writeln("    ");
document.writeln("    ");
document.writeln("");
document.writeln("");
document.writeln("<td height=\'44\'>");
document.writeln("<p align=\'center\'><img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=\'font-weight: 400\'><font face=\'方正粗黑宋简体\'><font color=\'#000000\' size=\'5\'>点击玄机网</font><font color=\'#FF00FF\' size=\'5\'>86</font><font color=\'#008000\' size=\'5\'>86</font><font color=\'#0000FF\' size=\'5\'>80</font><font size=\'5\' color=\'#FF0000\'>.com</font></font></span></td>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>马会传真</font><font color=\'#FFFFFF\'>『买尾输尽光』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--内容开始-->");
document.writeln("<table border=\'1\' width=\'100%\' cellspacing=\'0\' cellpadding=\'0\' bordercolor=\'#008000\' style=\'border-collapse: collapse; border-spacing: 0px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; color: rgb(255, 0, 0); font-size: 18.6667px; font-variant-ligatures: normal; orphans: 2; font-family: Simsun; padding: 0px; margin: 0px; word-wrap: break-word; background-color: rgb(255, 255, 255);\' height=\'47\'>");
document.writeln("	<tr>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' size=\'3\' color=\'#0000FF\'>067期</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'54%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>今期买<span style=\'background-color: #FFFF00\'>296尾</span>输尽光</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		</font><font size=\'3\' face=\'微软雅黑\' color=\'#0000FF\'>开：￥00</font></td>");
document.writeln("	</tr>");
document.writeln("	");
document.writeln("	");
document.writeln("		<tr>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' size=\'3\' color=\'#0000FF\'>065期</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'54%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>今期买<span style=\'background-color: #FFFF00\'>851尾</span>输尽光</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		</font><font size=\'3\' face=\'微软雅黑\' color=\'#0000FF\'>开：羊09</font></td>");
document.writeln("	</tr>");
document.writeln("");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("		<tr>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' size=\'3\' color=\'#0000FF\'>064期</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'54%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>今期买<span style=\'background-color: #FFFF00\'>470尾</span>输尽光</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		</font><font size=\'3\' face=\'微软雅黑\' color=\'#0000FF\'>开：马46</font></td>");
document.writeln("	</tr>");
document.writeln("");
document.writeln("	");
document.writeln("		<tr>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' size=\'3\' color=\'#0000FF\'>063期</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'54%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>今期买<span style=\'background-color: #FFFF00\'>613尾</span>输尽光</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		</font><font size=\'3\' face=\'微软雅黑\' color=\'#0000FF\'>开：猴32</font></td>");
document.writeln("	</tr>");
document.writeln("");
document.writeln("	");
document.writeln("		<tr>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' size=\'3\' color=\'#0000FF\'>062期</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'54%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>今期买<span style=\'background-color: #FFFF00\'>604尾</span>输尽光</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		</font><font size=\'3\' face=\'微软雅黑\' color=\'#0000FF\'>开：牛27</font></td>");
document.writeln("	</tr>");
document.writeln("");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("		<tr>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' size=\'3\' color=\'#0000FF\'>060期</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'54%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>今期买<span style=\'background-color: #FFFF00\'>139尾</span>输尽光</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		</font><font size=\'3\' face=\'微软雅黑\' color=\'#0000FF\'>开：鼠04</font></td>");
document.writeln("	</tr>");
document.writeln("	");
document.writeln("");
document.writeln("	");
document.writeln("	");
document.writeln("		<tr>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' size=\'3\' color=\'#0000FF\'>058期</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'54%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>今期买<span style=\'background-color: #FFFF00\'>035尾</span>输尽光</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		</font><font size=\'3\' face=\'微软雅黑\' color=\'#0000FF\'>开：兔49</font></td>");
document.writeln("	</tr>");
document.writeln("");
document.writeln("	");
document.writeln("	");
document.writeln("		<tr>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' size=\'3\' color=\'#0000FF\'>056期</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'54%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>今期买<span style=\'background-color: #FFFF00\'>643尾</span>输尽光</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'47\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		</font><font size=\'3\' face=\'微软雅黑\' color=\'#0000FF\'>开：羊21</font></td>");
document.writeln("	</tr>");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	<table id=\'table400900750\' border=\'1\' bordercolor=\'#ffcccc\' width=\'100%\' bgcolor=\'#ffffff\' style=\'font-family: &quot;Microsoft YaHei&quot;; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border-bottom-style: solid; padding: 0px; margin: 0px; word-wrap: break-word; border-top-style: solid; font-size: 9pt;\' height=\'45\'>");
document.writeln("<tbody style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=39><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'>澳门马会传真</font></span><span style=box-sizing:border-box;><font size=\'5\' color=\'#FF00FF\'>67</font><font size=\'4\' color=\'#0000FF\'>29</font><font size=\'4\' color=\'#008000\'>2</font><font size=\'4\' color=\'#FF0000\'>b.com</font></span><font color=\'#000000\'><span style=box-sizing:border-box;font-size:14pt>一定谨记!</span></font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");
