document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln(".cypt td {");
document.writeln("	text-align: center;");
document.writeln("	border: 1px solid #C0C0C0;");
document.writeln("	width: 25%;");
document.writeln("	height: 45px;");
document.writeln("	font-weight: 600;");
document.writeln("	font-size: 18px;");
document.writeln("	font-family:微软雅黑;");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table width=\'100%\' class=\'cypt\' height=\'100\'>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『13码中特』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td><font color=\'#008000\'>067期</font><img src=\'/images/zzzz.gif\'style=\'width:20px\' height=\'15\'><font color=\'#FF0000\'>【万兽妖王13码】<img src=\'/images/zzzz.gif\' style=\'width:20px\' height=\'15\'></font><font color=\'#0000FF\'>开：？00</font>准<br>");
document.writeln("15 22 35 43 37 06 14 12 17 48 07 46 18</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://62792a.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680c.com/\'>点击玄机网</a></font><a target=\'_blank\' href=\'https://868680c.com/#51\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td><font color=\'#008000\'>065期</font><img src=\'/images/zzzz.gif\'style=\'width:20px\' height=\'15\'><font color=\'#FF0000\'>【万兽妖王13码】<img src=\'/images/zzzz.gif\' style=\'width:20px\' height=\'15\'></font><font color=\'#0000FF\'>开：？00</font>准<br>");
document.writeln("27 01 40 45 33 48 30 36 06 <span style=\'background-color: #FFFF00\'>09</span> 16 38 10</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://62792a.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680c.com/\'>点击玄机网</a></font><a target=\'_blank\' href=\'https://868680c.com/#51\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『五字真言』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("	<tr>");
document.writeln("			<td align=\'center\' height=78>");
document.writeln("			<font color=\'#008080\'>067</font><font size=\'4\'><font color=\'#008080\'>期:【五字真言爆特码】</font><font color=\'#FF00FF\'>开？00准</font><br>");
document.writeln("		     <font color=\'#FF00FF\'>【&#9755;</font><span style=\'font-weight: 400; background-color:#FFFF00\'><font size=\'5\' color=\'#000000\'>五二两边出</font></span><font color=\'#FF00FF\'>&#9754;】</font><br></font>");
document.writeln("			<font color=\'#0000FF\' size=\'4\'>解：04鼠.05猪.06狗.11蛇.12龙13兔</td>");
document.writeln("		</tr>");
document.writeln(" <!--结束-->");
document.writeln(" ");
document.writeln(" ");
document.writeln(" <!--开始-->");
document.writeln("	<tr>");
document.writeln("			<td align=\'center\' height=78>");
document.writeln("			<font color=\'#008080\'>066</font><font size=\'4\'><font color=\'#008080\'>期:【五字真言爆特码】</font><font color=\'#FF00FF\'>开狗42准</font><br>");
document.writeln("		     <font color=\'#FF00FF\'>【&#9755;</font><span style=\'font-weight: 400; background-color:#FFFF00\'><font size=\'5\' color=\'#000000\'>五零两边出</font></span><font color=\'#FF00FF\'>&#9754;】</font><br></font>");
document.writeln("			<font color=\'#0000FF\' size=\'4\'>解：04鼠.05猪.<span style=\'background-color: #FFFF00\'>06狗</span>.09羊.10马.11蛇</td>");
document.writeln("		</tr>");
document.writeln(" <!--结束-->");
document.writeln("");
document.writeln(" ");
document.writeln(" ");
document.writeln(" ");
document.writeln(" ");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://62792a.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680c.com/\'>点击玄机网</a></font><a target=\'_blank\' href=\'https://868680c.com/#51\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</span>");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");