document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『男肖女肖』</font></font></b></table>");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<tr>");
document.writeln("");
document.writeln("<td align=\'center\' height=40 style=\'border-style: solid; border-width: 1px\'><b>");
document.writeln("<font style=\'font-size: 14pt\' color=\'#FF0000\'>");
document.writeln("<span style=\'background-color: #FFFF00\'>男肖：鼠牛虎龙马猴狗</span></font><font style=\'font-size: 14pt\' color=\'#000000\'><br></font>");
document.writeln("<font style=\'font-size: 14pt\' color=\'#FFFFFF\'>");
document.writeln("<span style=\'background-color: #FF0000\'>女肖：☆兔蛇羊鸡猪☆</span></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=40 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'>067期<font color=\'#0000FF\'>男女中特</font>【<font color=\'#FF0000\'>女肖</font>】开<font color=\'#008000\'>？00准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=40 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'>065期<font color=\'#0000FF\'>男女中特</font>【<font color=\'#FF0000\'>女肖</font>】开<font color=\'#008000\'>羊09准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=40 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'>063期<font color=\'#0000FF\'>男女中特</font>【<font color=\'#FF0000\'>男肖</font>】开<font color=\'#008000\'>猴32准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=40 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'>061期<font color=\'#0000FF\'>男女中特</font>【<font color=\'#FF0000\'>男肖</font>】开<font color=\'#008000\'>马46准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=40 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'>060期<font color=\'#0000FF\'>男女中特</font>【<font color=\'#FF0000\'>男肖</font>】开<font color=\'#008000\'>鼠04准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=40 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'>059期<font color=\'#0000FF\'>男女中特</font>【<font color=\'#FF0000\'>男肖</font>】开<font color=\'#008000\'>牛39准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680c.com/\'>点击玄机网</a></font><a target=\'_blank\' href=\'https://868680c.com/#51\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");