document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'taext/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『3肖+3码』</font></font></b></table>");
document.writeln("");
document.writeln("<!---每期开始--->");
document.writeln("<table id=\'table52\' border=\'1\' width=\'100%\' height=\'39\'>");
document.writeln("");
document.writeln("		<tr>");
document.writeln("			<td height=\'33\'>");
document.writeln("		");
document.writeln("			<p align=\'center\'><font size=\'4\' color=\'#FF0000\'><b>068</b></font><b><font color=\'#FF0000\' size=\'4\'>期『主3肖防3码』：开？00准</font></b></td>");
document.writeln("		</tr>");
document.writeln("</table>");
document.writeln("<table id=\'table52\' border=\'1\' width=\'100%\' height=\'46\'>");
document.writeln("");
document.writeln("		<tr>");
document.writeln("			<td height=\'40\'>");
document.writeln("		");
document.writeln("			<p align=\'center\'><b><font color=\'#008000\' size=\'5\'>【羊马蛇+48.24.36】</font></b></td>");
document.writeln("		</tr>");
document.writeln("</tr></table>");
document.writeln("<!---每期结束--->");
document.writeln("");
document.writeln("");
document.writeln("<!---每期开始--->");
document.writeln("<table id=\'table52\' border=\'1\' width=\'100%\' height=\'39\'>");
document.writeln("");
document.writeln("		<tr>");
document.writeln("			<td height=\'33\'>");
document.writeln("		");
document.writeln("			<p align=\'center\'><font size=\'4\' color=\'#FF0000\'><b>066</b></font><b><font color=\'#FF0000\' size=\'4\'>期『主3肖防3码』：开狗42准</font></b></td>");
document.writeln("		</tr>");
document.writeln("</table>");
document.writeln("<table id=\'table52\' border=\'1\' width=\'100%\' height=\'46\'>");
document.writeln("");
document.writeln("		<tr>");
document.writeln("			<td height=\'40\'>");
document.writeln("		");
document.writeln("			<p align=\'center\'><b><font color=\'#008000\' size=\'5\'>【鼠猪蛇+18.30.<span style=\'background-color: #FFFF00\'>42</span>】</font></b></td>");
document.writeln("		</tr>");
document.writeln("</tr></table>");
document.writeln("<!---每期结束--->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>潜水淹死王8</font><font color=\'#FFFFFF\'>『尾数大小』</font></font></b></table>");
document.writeln("");
document.writeln("<!---每期开始--->");
document.writeln("<table id=\'table52\' border=\'1\' width=\'100%\' height=\'39\'>");
document.writeln("");
document.writeln("		<tr>");
document.writeln("			<td height=\'33\'>");
document.writeln("		");
document.writeln("			<p align=\'center\'><b><font size=\'4\' color=\'#0000FF\'>（大尾：5.6.7.8.9） ");
document.writeln("			（小尾：0.1.2.3.4）</font></b></td>");
document.writeln("		</tr>");
document.writeln("</table>");
document.writeln("<table id=\'table52\' border=\'1\' width=\'100%\' height=\'43\'>");
document.writeln("");
document.writeln("");
document.writeln("		<tr>");
document.writeln("			<td height=\'37\'>");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#008000\'><b>068</b></font><b><font color=\'#008000\' size=\'4\'>期：</font><font color=\'#FF00FF\' size=\'4\'>必中【小尾】</font><font color=\'#008000\' size=\'4\'>开00准</font></b></td>");
document.writeln("		</tr>");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'39\'><tbody><tr>");
document.writeln("			<td height=39><p style=text-align:center><strong>");
document.writeln("			<img src=https://www.62755a.com/images/zu.gif  width=35 height=20><span style=font-family:楷体;color:#00f><font size=\'4\'>澳门马会传真</font></span><span style=font-family:楷体;><font color=\'#FF0000\' size=\'5\'>67292</font><font size=\'5\'>.com</strong></tr></table>");
document.writeln("");
document.writeln("</tr></table>");
document.writeln("<!---每期结束--->");
document.writeln("");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>半呆半萌</font><font color=\'#FFFFFF\'>『头数单双』</font></font></b></table>");
document.writeln("");
document.writeln("<!---每期开始--->");
document.writeln("<table id=\'table52\' border=\'1\' width=\'100%\' height=\'39\'>");
document.writeln("");
document.writeln("		<tr>");
document.writeln("			<td height=\'33\'>");
document.writeln("		");
document.writeln("			<p align=\'center\'><b><font size=\'4\' color=\'#0000FF\'>（双头：0.2.4.头） ");
document.writeln("			（单头：1.3.头）</font></b></td>");
document.writeln("		</tr>");
document.writeln("</table>");
document.writeln("<table id=\'table52\' border=\'1\' width=\'100%\' height=\'45\'>");
document.writeln("");
document.writeln("");
document.writeln("		<tr>");
document.writeln("			<td height=\'39\'>");
document.writeln("					<p align=\'center\'><b><font color=\'#008000\' size=\'4\'>068期：</font><font color=\'#FF00FF\' size=\'4\'>必中【单头】</font><font color=\'#008000\' size=\'4\'>开00准</font></b></td>");
document.writeln("		</tr>");
document.writeln("		");
document.writeln("		");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'39\'><tbody><tr>");
document.writeln("");
document.writeln("			<td height=39><p style=text-align:center><strong>");
document.writeln("			<img src=https://www.62755a.com/images/zu.gif  width=35 height=20><span style=font-family:楷体;color:#00f><font size=\'4\'>澳门马会传真</font></span><span style=font-family:楷体;><font color=\'#FF0000\' size=\'5\'>67292</font><font size=\'5\'>.com</strong></tr></table>");
document.writeln("");
document.writeln("</tr></table>");
document.writeln("<!---每期结束--->");
document.writeln("");
document.writeln("");