document.writeln("");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'taext/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'55\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 49px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『欲钱解特』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>067期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>欲钱解特诗</font><font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>开?00准</font><p align=\'center\'>");
document.writeln("   <span style=\'font-size: 14pt\'><font color=\'#FF0000\'>《羊猴鸡虎来发财，本期特码出小数</font><font color=\'#FF0000\'>》</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>066期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>欲钱解特诗</font><font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>开狗42准</font><p align=\'center\'>");
document.writeln("   <span style=\'font-size: 14pt\'><font color=\'#FF0000\'>《马牛鸡羊来发财，本期特码出<span style=\'background-color: #00FF00\'>大数</span>》</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>064期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>欲钱解特诗</font><font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>开马46准</font><p align=\'center\'>");
document.writeln("   <span style=\'font-size: 14pt\'><font color=\'#FF0000\'>《龙牛狗虎来发财，本期特码出<span style=\'background-color: #00FF00\'>大数</span>》</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>063期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>欲钱解特诗</font><font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>开猴32准</font><p align=\'center\'>");
document.writeln("   <span style=\'font-size: 14pt\'><font color=\'#FF0000\'>《鸡<span style=\'background-color: #00FF00\'>猴</span>虎兔来发财，本期特码出<span style=\'background-color: #00FF00\'>大数</span>》</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>062期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>欲钱解特诗</font><font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>开牛27准</font><p align=\'center\'>");
document.writeln("   <span style=\'font-size: 14pt\'><font color=\'#FF0000\'>《马兔猪龙来发财，本期特码出<span style=\'background-color: #00FF00\'>大数</span>》</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>061期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>欲钱解特诗</font><font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>开马46准</font><p align=\'center\'>");
document.writeln("   <span style=\'font-size: 14pt\'><font color=\'#FF0000\'>《鼠<span style=\'background-color: #00FF00\'>马</span>猪蛇来发财，本期特码出小数</font><font color=\'#FF0000\'>》</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>060期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>欲钱解特诗</font><font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>开鼠04准</font><p align=\'center\'>");
document.writeln("   <span style=\'font-size: 14pt\'><font color=\'#FF0000\'>《<span style=\'background-color: #00FF00\'>鼠</span>鸡马龙来发财，本期特码出<span style=\'background-color: #00FF00\'>小数</span>》</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>059期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>欲钱解特诗</font><font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>开牛39准</font><p align=\'center\'>");
document.writeln("   <span style=\'font-size: 14pt\'><font color=\'#FF0000\'>《狗虎鼠鸡来发财，本期特码出<span style=\'background-color: #00FF00\'>大数</span>》</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>057期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>欲钱解特诗</font><font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>开牛03准</font><p align=\'center\'>");
document.writeln("   <span style=\'font-size: 14pt\'><font color=\'#FF0000\'>《猪蛇虎虎来发财，本期特码出<span style=\'background-color: #00FF00\'>小数</span>》</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>056期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>欲钱解特诗</font><font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>开羊21准</font><p align=\'center\'>");
document.writeln("   <span style=\'font-size: 14pt\'><font color=\'#FF0000\'>《猪<span style=\'background-color: #00FF00\'>羊</span>蛇猴来发财，本期特码出大数</font><font color=\'#FF0000\'>》</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>054期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>欲钱解特诗</font><font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>开马46准</font><p align=\'center\'>");
document.writeln("   <span style=\'font-size: 14pt\'><font color=\'#FF0000\'>《龙牛<span style=\'background-color: #00FF00\'>马</span>猴来发财，本期特码出<span style=\'background-color: #00FF00\'>大数</span>》</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680c.com/\'>点击玄机网</a></font><a target=\'_blank\' href=\'https://868680c.com/#51\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("</tbody>");
document.writeln("");
document.writeln("");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");