document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<title>澳门马会传真</title>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<div class=\'box\'>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'>");
document.writeln("	<tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000>");
document.writeln("<p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『一肖三码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'margin: 0px; border: 1px solid rgb(229, 229, 229); word-break: break-all; padding-left:2px; padding-right:2px; padding-top:3px; padding-bottom:3px\' align=\'left\' height=\'32\'>");
document.writeln("<b><font face=\'微软雅黑\' size=\'4\' color=\'#008000\'>067期〖五肖〗</font><font face=\'微软雅黑\' size=\'4\' color=\'#0000FF\'>兔虎猪狗龙</font></b></td>");
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; border: 1px solid rgb(229, 229, 229); word-break: break-all;\' align=\'left\' height=\'30\'>");
document.writeln("<b><font face=\'微软雅黑\' color=\'#008000\' size=\'4\'>067期〖三肖〗</font><font face=\'微软雅黑\' color=\'#0000FF\' size=\'4\'>兔虎猪</font></b></td>");
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; border: 1px solid rgb(229, 229, 229); word-break: break-all;\' align=\'left\' height=\'36\'>");
document.writeln("<b><font face=\'微软雅黑\' size=\'4\' color=\'#008000\'>067期〖一肖〗</font><font face=\'微软雅黑\' color=\'#0000FF\' size=\'4\'>兔</font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; border: 1px solid rgb(229, 229, 229); word-break: break-all;\' align=\'left\' bgcolor=\'#FFFFFF\' height=\'34\'>");
document.writeln("<b><font face=\'微软雅黑\' size=\'4\' color=\'#008000\'>067期〖⑩码〗</font><font face=\'微软雅黑\' size=\'2\' color=\'#FF00FF\'>25.37.14.38.18.30.17.29.24.36</font></b></td>");
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; border: 1px solid rgb(229, 229, 229); word-break: break-all;\' align=\'left\' bgcolor=\'#FFFFFF\' height=\'38\'>");
document.writeln("<b><font face=\'微软雅黑\' color=\'#008000\' size=\'4\'>067期〖③码〗</font><font face=\'微软雅黑\' color=\'#FF00FF\' size=\'2\'>25.37.14</font></b></td>");
document.writeln("</tr>");
document.writeln(" <tr>");
document.writeln("<td bgcolor=\'#800000\' style=\'margin: 0px; padding: 3px 2px; border: 1px solid rgb(229, 229, 229); word-break: break-all;\' height=\'32\'>");
document.writeln("<h2 style=\'font-family: 微软雅黑; color: rgb(255, 253, 0); margin: 0px; padding: 0px\' align=\'left\'>");
document.writeln("<font size=\'4\'>067期: 特码开奖结果&lt;开:？00&gt;<font color=\'#00FF00\'></font></h2>");
document.writeln("</font></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'margin: 0px; border: 1px solid rgb(229, 229, 229); word-break: break-all; padding-left:2px; padding-right:2px; padding-top:3px; padding-bottom:3px\' align=\'left\' height=\'32\'>");
document.writeln("<b><font face=\'微软雅黑\' size=\'4\' color=\'#008000\'>066期〖五肖〗</font><font face=\'微软雅黑\' size=\'4\' color=\'#0000FF\'>猪蛇<span style=\'background-color: #FFFD00\'>狗</span>羊鼠</font></b></td>");
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; border: 1px solid rgb(229, 229, 229); word-break: break-all;\' align=\'left\' height=\'30\'>");
document.writeln("<b><font face=\'微软雅黑\' color=\'#008000\' size=\'4\'>066期〖三肖〗</font><font face=\'微软雅黑\' color=\'#0000FF\' size=\'4\'>猪蛇<span style=\'background-color: #FFFD00\'>狗</span></font></b></td>");
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; border: 1px solid rgb(229, 229, 229); word-break: break-all;\' align=\'left\' height=\'36\'>");
document.writeln("<b><font face=\'微软雅黑\' size=\'4\' color=\'#008000\'>066期〖一肖〗</font><font face=\'微软雅黑\' color=\'#0000FF\' size=\'4\'>猪</font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; border: 1px solid rgb(229, 229, 229); word-break: break-all;\' align=\'left\' bgcolor=\'#FFFFFF\' height=\'34\'>");
document.writeln("<b><font face=\'微软雅黑\' size=\'4\' color=\'#008000\'>066期〖⑩码〗</font><font face=\'微软雅黑\' size=\'2\' color=\'#FF00FF\'>29.41.35.47.30.<span style=\'background-color: #FFFD00\'>42</span>.33.45.28.40</font></b></td>");
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td style=\'margin: 0px; padding: 3px 2px; border: 1px solid rgb(229, 229, 229); word-break: break-all;\' align=\'left\' bgcolor=\'#FFFFFF\' height=\'38\'>");
document.writeln("<b><font face=\'微软雅黑\' color=\'#008000\' size=\'4\'>066期〖③码〗</font><font face=\'微软雅黑\' color=\'#FF00FF\' size=\'2\'>29.41.35</font></b></td>");
document.writeln("</tr>");
document.writeln(" <tr>");
document.writeln("<td bgcolor=\'#800000\' style=\'margin: 0px; padding: 3px 2px; border: 1px solid rgb(229, 229, 229); word-break: break-all;\' height=\'32\'>");
document.writeln("<h2 style=\'font-family: 微软雅黑; color: rgb(255, 253, 0); margin: 0px; padding: 0px\' align=\'left\'>");
document.writeln("<font size=\'4\'>066期: 特码开奖结果&lt;开:狗42&gt;<font color=\'#00FF00\'></font></h2>");
document.writeln("</font></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody></table>");
document.writeln("<table border=\'1\' width=\'100%\' cellspacing=\'0\' cellpadding=\'0\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\' id=\'table270\'>");
document.writeln("<tbody>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\'box\'>");
document.writeln("<table border=\'1\' width=\'100%\' cellspacing=\'0\' cellpadding=\'0\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\' id=\'table241\'>");
document.writeln("<tbody>");
document.writeln("");
document.writeln("</tbody></table>");
document.writeln("<table border=\'1\' width=\'100%\' cellspacing=\'0\' cellpadding=\'0\' style=\'border-collapse: collapse; border-spacing: 0px; color: rgb(68, 68, 68); font-family: tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\' id=\'table270\'>");
document.writeln("<tbody>");