document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("");
document.writeln("");
document.writeln("          <!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td style=\'text-align:center\' height=\'60\'>");
document.writeln("	<table border=1 width=100% bgcolor=#ffffff height=\'47\'>");
document.writeln("        <tbody>");
document.writeln("        ");
document.writeln("          <td style=\'border:6px double #800000; height: 41px;\' bgcolor=#800000><p align=center> ");
document.writeln("			<b><font face=\'楷体\' style=\'font-size: 20pt\' color=\'#FFFF00\'>068期</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『30码中特』</font></b>");
document.writeln("      </table>");
document.writeln("      <table border=1 width=100% bgcolor=#ffffff>");
document.writeln("      <tbody>");
document.writeln("        <tr>");
document.writeln("          <td align=center bgcolor=#ffffcc width=10% height=36><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>鼠</font></span></strong></span>");
document.writeln("          <td align=center width=20% height=36><strong> ");
document.writeln("			<span style=font-family:Arial;><font size=\'4\' color=\'#800000\'> </font></span></strong>");
document.writeln("          <td align=center bgcolor=#ffffcc width=10% height=36><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>猪</font></span></strong></span>");
document.writeln("          <td align=center width=\'22%\' height=36><strong>");
document.writeln("			<span style=\'font-family: Arial\'><font size=\'4\' color=\'#800000\'>");
document.writeln("			05.17.29.41 </font></span></strong>");
document.writeln("			<td align=center bgcolor=#ffffcc width=\'11%\' height=36><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>狗</font></span></strong></span>");
document.writeln("          <td align=center width=20% height=36><strong> ");
document.writeln("			<span style=font-family:Arial;>");
document.writeln("			<font size=\'4\' color=\'#800000\'> </font></span></strong></tr>");
document.writeln("        <tr>");
document.writeln("          <td align=center bgcolor=#ffffcc width=10% height=37><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>鸡</font></span></strong></span>");
document.writeln("          <td align=center width=20% height=37><strong>");
document.writeln("			<span style=\'font-family: Arial\'><font size=\'4\' color=\'#800000\'> 07.19.31.43</font></span></strong><td align=center bgcolor=#ffffcc width=10% height=37><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>猴</font></span></strong></span>");
document.writeln("          <td align=center width=\'22%\' height=37><strong> ");
document.writeln("			<span style=font-family:Arial;><font size=\'4\' color=\'#800000\'> </font></span></strong>");
document.writeln("          <td align=center bgcolor=#ffffcc width=\'11%\' height=37><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>羊</font></span></strong></span>");
document.writeln("          <td align=center width=20% height=37><strong>");
document.writeln("			<font size=\'4\' color=\'#800000\'><span style=\'font-family: Arial\'>09.33.21.45</span></font></strong>");
document.writeln("        </tr>");
document.writeln("        <tr>");
document.writeln("          <td align=center bgcolor=#ffffcc width=10% height=33><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>马</font></span></strong></span>");
document.writeln("          <td align=center width=20% height=33><strong> ");
document.writeln("			<span style=font-family:Arial;><font size=\'4\' color=\'#800000\'>10.22.34.46</font></span></strong><td align=center bgcolor=#ffffcc width=10% height=33><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>蛇</font></span></strong></span>");
document.writeln("          <td align=center width=\'22%\' height=33><strong>");
document.writeln("			<span style=\'font-family: Arial\'><font size=\'4\' color=\'#800000\'>11.23.35.47</font></span></strong>");
document.writeln("			<td align=center bgcolor=#ffffcc width=\'11%\' height=33><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>龙</font></span></strong></span>");
document.writeln("          <td align=center width=20% height=33><strong> ");
document.writeln("			<span style=font-family:Arial;><font size=\'4\' color=\'#800000\'>12.24.36.48</font></span></strong>");
document.writeln("        </tr>");
document.writeln("        <tr>");
document.writeln("          <td align=center bgcolor=#ffffcc width=10% height=38><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>兔</font></span></strong></span>");
document.writeln("          <td align=center width=20% height=38><strong> ");
document.writeln("			<span style=font-family:Arial;><font size=\'4\' color=\'#800000\'>");
document.writeln("			01.13.25.37 </font></span></strong>");
document.writeln("          <td align=center bgcolor=#ffffcc width=10% height=38><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>虎</font></span></strong></span>");
document.writeln("          <td align=center width=\'22%\' height=38><strong> ");
document.writeln("			<span style=font-family:Arial;><font size=\'4\' color=\'#800000\'> </font></span></strong>");
document.writeln("          <td align=center bgcolor=#ffffcc width=\'11%\' height=38><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>牛</font></span></strong></span>");
document.writeln("          <td align=center width=20% height=38><strong> ");
document.writeln("			<span style=font-family:Arial;><font size=\'4\' color=\'#800000\'>03.15.27.39</font></span></strong></tr>");
document.writeln("			</table>");
document.writeln("     <!--结束-->");
document.writeln("     ");
document.writeln("     ");
document.writeln("     ");
document.writeln("     ");
document.writeln("               <!--开始-->");
document.writeln("  <tr>");
document.writeln("    <td style=\'text-align:center\' height=\'60\'>");
document.writeln("	<table border=1 width=100% bgcolor=#ffffff height=\'47\'>");
document.writeln("        <tbody>");
document.writeln("        ");
document.writeln("          <td style=\'border:6px double #800000; height: 41px;\' bgcolor=#800000><p align=center> ");
document.writeln("			<b><font face=\'楷体\' style=\'font-size: 20pt\' color=\'#FFFF00\'>067期</font><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 20pt\'>『30码中特』</font></b>");
document.writeln("      </table>");
document.writeln("      <table border=1 width=100% bgcolor=#ffffff>");
document.writeln("      <tbody>");
document.writeln("        <tr>");
document.writeln("          <td align=center bgcolor=#ffffcc width=10% height=36><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>鼠</font></span></strong></span>");
document.writeln("          <td align=center width=20% height=36><strong> ");
document.writeln("			<span style=font-family:Arial;><font size=\'4\' color=\'#800000\'>04.16.28</font></span></strong>");
document.writeln("          <td align=center bgcolor=#ffffcc width=10% height=36><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>猪</font></span></strong></span>");
document.writeln("          <td align=center width=\'22%\' height=36><strong>");
document.writeln("			<span style=\'font-family: Arial\'><font size=\'4\' color=\'#800000\'>");
document.writeln("			05.17 </font></span></strong>");
document.writeln("			<td align=center bgcolor=#ffffcc width=\'11%\' height=36><span style=color:#000><strong> <span style=font-family:Arial;><font size=\'4\'>狗</font></span></strong></span>");
document.writeln("          <td align=center width=20% height=36><strong> ");
document.writeln("			<span style=font-family:Arial;>");
document.writeln("			<font size=\'4\' color=\'#800000\'>18.30.06</font></span></strong></tr>");
document.writeln("        <tr>");
document.writeln("          <td align=center bgcolor=#ffffcc width=10% height=37><span style=color:#000><strong> <span sty