document.writeln("");
document.writeln("");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'58\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 52px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『三期必中』</font></font></b></table>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'><b><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#0000FF\'>");
document.writeln("067-069期《三期必中》中</font><font color=\'#FF00FF\'>0</font><font color=\'#0000FF\'>期</font><font color=\'#000000\'><br></font><font color=\'#008000\'></font><font color=\'#FF0000\'>");
document.writeln("【鼠兔虎猪】<br>");
document.writeln("【28.25.14.17】</font></span></b>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'><b><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#0000FF\'>");
document.writeln("064-066期《三期必中》中</font><font color=\'#FF00FF\'>2</font><font color=\'#0000FF\'>期</font><font color=\'#000000\'><br></font><font color=\'#008000\'></font><font color=\'#FF0000\'>");
document.writeln("【兔<span style=\'background-color: #00FF00\'>羊狗</span>虎】<br>");
document.writeln("【25.21.18.14】</font></span></b>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'><b><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#0000FF\'>");
document.writeln("058-060期《三期必中》中</font><font color=\'#FF00FF\'>2</font><font color=\'#0000FF\'>期</font><font color=\'#000000\'><br></font><font color=\'#008000\'></font><font color=\'#FF0000\'>");
document.writeln("【鸡<span style=\'background-color: #00FF00\'>鼠兔</span>马】<br>");
document.writeln("【19.28.37.34】</font></span></b>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'><b><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#0000FF\'>");
document.writeln("055-057期《三期必中》中</font><font color=\'#FF00FF\'>1</font><font color=\'#0000FF\'>期</font><font color=\'#000000\'><br></font><font color=\'#008000\'></font><font color=\'#FF0000\'>");
document.writeln("【龙兔<span style=\'background-color: #00FF00\'>狗</span>鼠】<br>");
document.writeln("【24.49.18.28】</font></span></b>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'><b><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#0000FF\'>");
document.writeln("052-054期《三期必中》中</font><font color=\'#FF00FF\'>1</font><font color=\'#0000FF\'>期</font><font color=\'#000000\'><br></font><font color=\'#008000\'></font><font color=\'#FF0000\'>");
document.writeln("【鼠鸡</font></span><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#FF0000\'><span style=\'background-color: #00FF00\'>羊</span></font></span><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#FF0000\'>猴】<br>");
document.writeln("【16.07.45.32】</font></span></b>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'><b><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#0000FF\'>");
document.writeln("049-051期《三期必中》中</font><font color=\'#FF00FF\'>2</font><font color=\'#0000FF\'>期</font><font color=\'#000000\'><br></font><font color=\'#008000\'></font><font color=\'#FF0000\'>");
document.writeln("【<span style=\'background-color: #00FF00\'>蛇</span>鸡羊<span style=\'background-color: #00FF00\'>兔</span>】<br>");
document.writeln("【23.19.45.49】</font></span></b>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'><b><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#0000FF\'>");
document.writeln("046-048期《三期必中》中</font><font color=\'#FF00FF\'>2</font><font color=\'#0000FF\'>期</font><font color=\'#000000\'><br></font><font color=\'#008000\'></font><font color=\'#FF0000\'>");
document.writeln("【鸡羊<span style=\'background-color: #00FF00\'>狗龙</span>】<br>");
document.writeln("【43.33.42.48】</font></span></b>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'><b><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#0000FF\'>");
document.writeln("043-045期《三期必中》中</font><font color=\'#FF00FF\'>1</font><font color=\'#0000FF\'>期</font><font color=\'#000000\'><br></font><font color=\'#008000\'></font><font color=\'#FF0000\'>");
document.writeln("【猴狗<span style=\'background-color: #00FF00\'>鼠</span>马】<br>");
document.writeln("【32.42.<span style=\'background-color: #00FF00\'>16</span>.46】</font></span></b>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'><b><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#0000FF\'>");
document.writeln("040-042期《三期必中》中</font><font color=\'#FF00FF\'>1</font><font color=\'#0000FF\'>期</font><font color=\'#000000\'><br></font><font color=\'#008000\'></font><font color=\'#FF0000\'>");
document.writeln("【虎猴兔<span style=\'background-color: #00FF00\'>鸡</span>】<br>");
document.writeln("【26.20.25.19】</font></span></b>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--网址开始-->");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'>澳门马会传真</font></span><span style=box-sizing:border-box;><font size=\'5\' color=\'#FF00FF\'>67</font><font size=\'4\' color=\'#0000FF\'>29</font><font size=\'4\' color=\'#008000\'>2</font><font size=\'4\' color=\'#FF0000\'>.com</font></span><font color=\'#000000\'><span style=box-sizing:border-box;font-size:14pt>一定谨记!</span></font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("<!--网址结束-->");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'57\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 51px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『稳定七尾』</font></font></b></table>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=45><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>");
document.writeln("068期</font><font color=\'#FF0000\'>");
document.writeln("<span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<b>");
document.writeln("<img src=\'https://67292c.com/images/sg.png\' style=\'width:10px\' height=\'08\'></b>【3-1-4-6-8-9-2】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>￥00</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=45><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>");
document.writeln("067期</font><font color=\'#FF0000\'>");
document.writeln("<span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<b>");
document.writeln("<img src=\'https://67292c.com/images/sg.png\' style=\'width:10px\' height=\'08\'></b>【3-1-<span style=\'background-color: #00FF00\'>8</span>-0-7-5-4】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>猴08</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=45><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>");
document.writeln("065期</font><font color=\'#FF0000\'>");
document.writeln("<span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<b>");
document.writeln("<img src=\'https://67292c.com/images/sg.png\' style=\'width:10px\' height=\'08\'></b>【1-3-0-2-8-5-<span style=\'background-color: #00FF00\'>9</span>】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>羊09</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=45><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>");
document.writeln("063期</font><font color=\'#FF0000\'>");
document.writeln("<span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<b>");
document.writeln("<img src=\'https://67292c.com/images/sg.png\' style=\'width:10px\' height=\'08\'></b>【6-3-9-1-8-<span style=\'background-color: #00FF00\'>2</span>-4】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>猴32</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=45><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>");
document.writeln("062期</font><font color=\'#FF0000\'>");
document.writeln("<span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<b>");
document.writeln("<img src=\'https://67292c.com/images/sg.png\' style=\'width:10px\' height=\'08\'></b>【8-0-1-<span style=\'background-color: #00FF00\'>7</span>-3-2-5】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>牛27</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=45><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>");
document.writeln("061期</font><font color=\'#FF0000\'>");
document.writeln("<span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<b>");
document.writeln("<img src=\'https://67292c.com/images/sg.png\' style=\'width:10px\' height=\'08\'></b>【7-0-5-<span style=\'background-color: #00FF00\'>6</span>-8-2-1】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>马46</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=45><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>");
document.writeln("060期</font><font color=\'#FF0000\'>");
document.writeln("<span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<b>");
document.writeln("<img src=\'https://67292c.com/images/sg.png\' style=\'width:10px\' height=\'08\'></b>【8-7-2-5-<span style=\'background-color: #00FF00\'>4</span>-6-0】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>鼠04</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=45><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>");
document.writeln("058期</font><font color=\'#FF0000\'>");
document.writeln("<span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<b>");
document.writeln("<img src=\'https://67292c.com/images/sg.png\' style=\'width:10px\' height=\'08\'></b>【4-0-<span style=\'background-color: #00FF00\'>9</span>-6-5-8-3】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>兔49</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=49><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font face=\'微软雅黑\'><b><font color=\'#000000\'>");
document.writeln("057期</font><font color=\'#FF0000\'>");
document.writeln("<span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<b>");
document.writeln("<img src=\'https://67292c.com/images/sg.png\' style=\'width:10px\' height=\'08\'></b>【8-4-0-2-7-<span style=\'background-color: #00FF00\'>3</span>-9】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>牛03</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'>澳门马会传真</font></span><span style=box-sizing:border-box;><font size=\'5\' color=\'#FF00FF\'>67</font><font size=\'4\' color=\'#0000FF\'>29</font><font size=\'4\' color=\'#008000\'>2</font><font size=\'4\' color=\'#FF0000\'>.com</font></span><font color=\'#000000\'><span style=box-sizing:border-box;font-size:14pt>一定谨记!</span></font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("");
document.writeln("");
document.writeln("</table><html>");
document.writeln("<head>");
document.writeln("</tbody>");
document.writeln("");
document.writeln("");
document.writeln("</table>");