document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『双波10码』</font></font></b></table>");
document.writeln("");
document.writeln("	<!--开始-->");
document.writeln("<table style=border-collapse:collapse border=1 width=100% bgcolor=#ffffff height=\'157\'><tbody>");
document.writeln("	");
document.writeln("<tr><td width=100% height=40><p align=left><b><font face=\'黑体\' size=\'4\'>067期</font></b><font face=\'黑体\'><b><font color=\'#FFFFFF\' size=\'4\'><span style=\'background-color: #0000FF\'>【双波20码】</span></font><font color=\'#FF0000\' size=\'4\'>（开？00）</font></b></font></td></tr>");
document.writeln("");
document.writeln("<tr><td width=100% height=38><p align=left><font face=\'黑体\'><b>");
document.writeln("		<font size=\'3\' color=\'#0000FF\'>【蓝波】03.15.14.26.25.37.36.48.10.09</font></b></td></tr>");
document.writeln("");
document.writeln("<tr><td width=100% height=44><p align=left><font face=\'黑体\'><b>");
document.writeln("		<font size=\'3\' color=\'#008000\'>【绿波】27.39.43.11.06.38.49.44.16.28</font></b></td></tr>");
document.writeln("");
document.writeln("<tr><td width=100% height=38 bgcolor=\'#FFFF99\'><p align=\'left\'><b>");
document.writeln("	<span style=box-sizing:border-box;><font color=\'#000000\'>澳门马会传真</font><font size=\'5\' color=\'#FF00FF\'>67</font><font size=\'4\' color=\'#0000FF\'>29</font><font size=\'4\' color=\'#008000\'>2</font><font size=\'4\' color=\'#FF0000\'>.com</font></span><font color=\'#000000\'>一定谨记!</font></span> </b>");
document.writeln("</td></tr></table>				");
document.writeln("		<!--结束-->");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");