document.writeln("<html>");
document.writeln("");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『复式连肖』</font></font></b></table>");
document.writeln("<table border=\'1\' width=\'100%\' style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box; table-layout: fixed; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px; background-color: rgb(0, 128, 64);\'><tbody style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("  ");
document.writeln("  <tr>");
document.writeln("<td align=\'center\' width=\'25%\' height=\'35\' bgcolor=\'#CCFFFF\' style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("<span style=\'font-family:微软雅黑;font-size:18px;color:#0000FF;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("068期：</span></td>");
document.writeln("<td align=\'center\' width=\'50%\' height=\'35\' bgcolor=\'#FFFFFF\' style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'font-family:微软雅黑;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'font-family:微软雅黑;font-size:18px;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("【狗蛇龙猪马牛】</span></span></span></td>");
document.writeln("<td align=\'center\' width=\'25%\' height=\'35\' bgcolor=\'#CCFFFF\' style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'font-family:微软雅黑;font-size:18px;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("中?个</span></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <tr>");
document.writeln("<td align=\'center\' width=\'25%\' height=\'35\' bgcolor=\'#CCFFFF\' style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("<span style=\'font-family:微软雅黑;font-size:18px;color:#0000FF;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("067期：</span></td>");
document.writeln("<td align=\'center\' width=\'50%\' height=\'35\' bgcolor=\'#FFFFFF\' style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'font-family:微软雅黑;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'font-family:微软雅黑;font-size:18px;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("【龙<span style=\'background-color: #FFFF00\'>虎羊</span>猪狗<span style=\'background-color: #FFFF00\'>牛</span>】</span></span></span></td>");
document.writeln("<td align=\'center\' width=\'25%\' height=\'35\' bgcolor=\'#CCFFFF\' style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'font-family:微软雅黑;font-size:18px;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("中3个</span></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <tr>");
document.writeln("<td align=\'center\' width=\'25%\' height=\'35\' bgcolor=\'#CCFFFF\' style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("<span style=\'font-family:微软雅黑;font-size:18px;color:#0000FF;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("066期：</span></td>");
document.writeln("<td align=\'center\' width=\'50%\' height=\'35\' bgcolor=\'#FFFFFF\' style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'font-family:微软雅黑;font-size:18px;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("【<span style=\'background-color: #FFFF00\'>龙鼠</span>羊兔<span style=\'background-color: #FFFF00\'>虎狗</span>】</span></td>");
document.writeln("<td align=\'center\' width=\'25%\' height=\'35\' bgcolor=\'#CCFFFF\' style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'font-family:微软雅黑;font-size:18px;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("中4个</span></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("  <tr>");
document.writeln("<td align=\'center\' width=\'25%\' height=\'35\' bgcolor=\'#CCFFFF\' style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("<span style=\'font-family:微软雅黑;font-size:18px;color:#0000FF;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("065期：</span></td>");
document.writeln("<td align=\'center\' width=\'50%\' height=\'35\' bgcolor=\'#FFFFFF\' style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'font-family:微软雅黑;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'font-family:微软雅黑;font-size:18px;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("【虎兔<span style=\'background-color: #FFFF00\'>狗猪</span>龙<span style=\'background-color: #FFFF00\'>马</span>】</span></span></span></td>");
document.writeln("<td align=\'center\' width=\'25%\' height=\'35\' bgcolor=\'#CCFFFF\' style=\'padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'><span style=\'font-family:微软雅黑;font-size:18px;padding: 0px; margin: 0px; border: 0px; box-sizing: border-box;\'>");
document.writeln("中3个</span></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("</tbody>");
document.writeln("</table>");