document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<table border=1 width=100% style=\'border-collapse: collapse\'>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『四肖八码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>【</font><font color=\'#000000\'><span style=\'background-color: #FFFF00\'>2尾</span>-35.45</font><font color=\'#008000\'>】【</font><font color=\'#000000\'>0尾-30.40</font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#008000\'>【</font><font color=\'#000000\'>8尾-48.38</font><font color=\'#008000\'>】【</font><font color=\'#000000\'>5尾-35.45</font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#0000FF\'>第066期开奖结果:</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>狗42准</font></span></span></font><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>【</font><font color=\'#000000\'>1尾-21.31</font><font color=\'#008000\'>】【</font><font color=\'#000000\'>1尾-20.30</font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#008000\'>【</font><font color=\'#000000\'><span style=\'background-color: #FFFF00\'>8尾</span>-25.38</font><font color=\'#008000\'>】【</font><font color=\'#000000\'>5尾-25.35</font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#0000FF\'>第067期开奖结果:</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>￥00准</font></span></span></font><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>【</font><font color=\'#000000\'>4尾-04.14</font><font color=\'#008000\'>】【</font><font color=\'#000000\'>1尾-01.11</font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#008000\'>【</font><font color=\'#000000\'>3尾-03.13</font><font color=\'#008000\'>】【</font><font color=\'#000000\'>5尾-05.15</font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#0000FF\'>第068期开奖结果:</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>￥00准</font></span></span></font><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--网址结束-->");
document.writeln("</span>");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680c.com/\'><font color=\'#6600FF\'>点击玄机网</font></a></font><a target=\'_blank\' href=\'https://868680c.com/#51\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『四肖八码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>【</font><font color=\'#000000\'>兔主37.49</font><font color=\'#008000\'>】【</font><font color=\'#000000\'><span style=\'background-color: #FFFF00\'>马</span>主34.<span style=\'background-color: #FFFF00\'>46</span></font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#008000\'>【</font><font color=\'#000000\'>龙主36.48</font><font color=\'#008000\'>】【</font><font color=\'#000000\'>猪主29.41</font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#0000FF\'>第064期开奖结果:</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>马46准</font></span></span></font><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>【</font><font color=\'#000000\'>兔主01.13</font><font color=\'#008000\'>】【</font><font color=\'#000000\'>牛主03.15</font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#008000\'>【</font><font color=\'#000000\'><span style=\'background-color: #FFFF00\'>羊</span>主<span style=\'background-color: #FFFF00\'>09</span>.21</font><font color=\'#008000\'>】【</font><font color=\'#000000\'>鼠主04.16</font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#0000FF\'>第065期开奖结果:</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>羊09准</font></span></span></font><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>【</font><font color=\'#000000\'>猪主05.17</font><font color=\'#008000\'>】【</font><font color=\'#000000\'>蛇主11.23</font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#008000\'>【</font><font color=\'#000000\'>羊主09.21</font><font color=\'#008000\'>】【</font><font color=\'#000000\'><span style=\'background-color: #FFFF00\'>狗</span>主06.18</font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#0000FF\'>第066期开奖结果:</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>狗42准</font></span></span></font><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>【</font><font color=\'#000000\'>羊主33.45</font><font color=\'#008000\'>】【</font><font color=\'#000000\'>马主34.46</font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#008000\'>【</font><font color=\'#000000\'>牛主27.39</font><font color=\'#008000\'>】【</font><font color=\'#000000\'>龙主36.48</font><font color=\'#008000\'>】</font><font color=\'#000000\'><br>");
document.writeln("</font><font color=\'#0000FF\'>第068期开奖结果:</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>？00准</font></span></span></font><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--网址结束-->");
document.writeln("</span>");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680c.com/\'><font color=\'#6600FF\'>点击玄机网</font></a></font><a target=\'_blank\' href=\'https://868680c.com/#51\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");