document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<table border=1 width=100% style=\'border-collapse: collapse\'>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『单双四尾』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>068期【</font><font color=\'#FF0000\'>单:3751</font><font color=\'#008000\'>】</font><font color=\'#000000\'>尾</font><font color=\'#008000\'> ");
document.writeln("【</font><font color=\'#FF0000\'>双:0846</font><font color=\'#008000\'>】</font><font color=\'#000000\'>开00准 ");
document.writeln("　</font></span></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>067期【</font><font color=\'#FF0000\'>单:3751</font><font color=\'#008000\'>】</font><font color=\'#000000\'>尾</font><font color=\'#008000\'> ");
document.writeln("【</font><font color=\'#FF0000\'>双:0<span style=\'background-color: #0000FF\'>8</span>42</font><font color=\'#008000\'>】</font><font color=\'#000000\'>开08准 ");
document.writeln("　</font></span></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>066期【</font><font color=\'#FF0000\'>单:3951</font><font color=\'#008000\'>】</font><font color=\'#000000\'>尾</font><font color=\'#008000\'> ");
document.writeln("【</font><font color=\'#FF0000\'>双:084<span style=\'background-color: #0000FF\'>2</span></font><font color=\'#008000\'>】</font><font color=\'#000000\'>开42准 ");
document.writeln("　</font></span></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>065期【</font><font color=\'#FF0000\'>单:3<span style=\'background-color: #0000FF\'>9</span>51</font><font color=\'#008000\'>】</font><font color=\'#000000\'>尾</font><font color=\'#008000\'> ");
document.writeln("【</font><font color=\'#FF0000\'>双:0846</font><font color=\'#008000\'>】</font><font color=\'#000000\'>开09准 ");
document.writeln("　</font></span></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>064期【</font><font color=\'#FF0000\'>单:3951</font><font color=\'#008000\'>】</font><font color=\'#000000\'>尾</font><font color=\'#008000\'> ");
document.writeln("【</font><font color=\'#FF0000\'>双:084<span style=\'background-color: #0000FF\'>6</span></font><font color=\'#008000\'>】</font><font color=\'#000000\'>开46准 ");
document.writeln("　</font></span></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>063期【</font><font color=\'#FF0000\'>单:3951</font><font color=\'#008000\'>】</font><font color=\'#000000\'>尾</font><font color=\'#008000\'> ");
document.writeln("【</font><font color=\'#FF0000\'>双:084<span style=\'background-color: #0000FF\'>2</span></font><font color=\'#008000\'>】</font><font color=\'#000000\'>开32准 ");
document.writeln("　</font></span></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>062期【</font><font color=\'#FF0000\'>单:3<span style=\'background-color: #0000FF\'>7</span>51</font><font color=\'#008000\'>】</font><font color=\'#000000\'>尾</font><font color=\'#008000\'> ");
document.writeln("【</font><font color=\'#FF0000\'>双:0842</font><font color=\'#008000\'>】</font><font color=\'#000000\'>开27准 ");
document.writeln("　</font></span></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>061期【</font><font color=\'#FF0000\'>单:3751</font><font color=\'#008000\'>】</font><font color=\'#000000\'>尾</font><font color=\'#008000\'> ");
document.writeln("【</font><font color=\'#FF0000\'>双:08<span style=\'background-color: #0000FF\'>6</span>2</font><font color=\'#008000\'>】</font><font color=\'#000000\'>开46准 ");
document.writeln("　</font></span></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>060期【</font><font color=\'#FF0000\'>单:9751</font><font color=\'#008000\'>】</font><font color=\'#000000\'>尾</font><font color=\'#008000\'> ");
document.writeln("【</font><font color=\'#FF0000\'>双:08<span style=\'background-color: #0000FF\'>4</span>2</font><font color=\'#008000\'>】</font><font color=\'#000000\'>开04准 ");
document.writeln("　</font></span></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>058期【</font><font color=\'#FF0000\'>单:<span style=\'background-color: #0000FF\'>9</span>751</font><font color=\'#008000\'>】</font><font color=\'#000000\'>尾</font><font color=\'#008000\'> ");
document.writeln("【</font><font color=\'#FF0000\'>双:0842</font><font color=\'#008000\'>】</font><font color=\'#000000\'>开49准 ");
document.writeln("　</font></span></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#008000\'>057期【</font><font color=\'#FF0000\'>单:975<span style=\'background-color: #0000FF\'>3</span></font><font color=\'#008000\'>】</font><font color=\'#000000\'>尾</font><font color=\'#008000\'> ");
document.writeln("【</font><font color=\'#FF0000\'>双:0842</font><font color=\'#008000\'>】</font><font color=\'#000000\'>开03准 ");
document.writeln("　</font></span></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--网址结束-->");
document.writeln("</span>");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680c.com/\'><font color=\'#6600FF\'>点击玄机网</font></a></font><a target=\'_blank\' href=\'https://868680c.com/#51\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</html>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");