document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'taext/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>人丑就多读书</font><font color=\'#FFFFFF\'>『大肖小肖』</font></font></b></table>");
document.writeln("");
document.writeln("    <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 align=\'center\' ><b>");
document.writeln("");
document.writeln("		<font face=\'隶书\' color=\'#008000\' size=\'5\'>");
document.writeln("										大肖：牛虎马羊狗猪<br>");
document.writeln("										小肖：鼠兔龙蛇猴鸡</font></b></td>");
document.writeln("    </tr>      ");
document.writeln("  ");
document.writeln("    <!--结束-->  ");
document.writeln("");
document.writeln("    <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 align=\'center\' ><font face=\'微软雅黑\' size=\'4\' color=\'#0000FF\'>");
document.writeln("		068</font><b><font color=\'#0000FF\' face=\'微软雅黑\' size=\'4\'>期:</font><font color=\'#FF00FF\' face=\'微软雅黑\' size=\'4\'>&#9755;主四肖博八码&#9754;</font><font color=\'#0000FF\' face=\'微软雅黑\' size=\'4\'>(？00)中</font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'华文楷体\' size=\'5\'>");
document.writeln("		特肖：小肖（鼠兔龙蛇猴鸡）<br>	");
document.writeln("				主四肖：龙蛇兔鸡<br>			");
document.writeln("        <span style=\'font-weight: 400\'>博8码：12.24.11.23.07.19.01.13</span></font></b></td>");
document.writeln("    </tr>      ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("");
document.writeln("    ");
document.writeln("        <!--开始-->  ");
document.writeln("    	<tr>");
document.writeln("      <td height=40 align=\'center\' ><font face=\'微软雅黑\' size=\'4\' color=\'#0000FF\'>");
document.writeln("		067</font><b><font color=\'#0000FF\' face=\'微软雅黑\' size=\'4\'>期:</font><font color=\'#FF00FF\' face=\'微软雅黑\' size=\'4\'>&#9755;主四肖博八码&#9754;</font><font color=\'#0000FF\' face=\'微软雅黑\' size=\'4\'>(猴08)中</font><font face=\'隶书\' size=\'5\' color=\'#000000\'><br>");
document.writeln("		</font>  ");
document.writeln("		<font face=\'华文楷体\' size=\'5\'>");
document.writeln("		特肖：小肖（鼠兔龙蛇<span style=\'background-color: #008000\'>猴</span>鸡）<br>	");
document.writeln("				主四肖：鼠兔龙<span style=\'background-color: #008000\'>猴</span><br>			");
document.writeln("        <span style=\'font-weight: 400\'>博8码：04.16.01.13.12.24.<span style=\'background-color: #008000\'>08</span>.20</span></font></b></td>");
document.writeln("    </tr>      ");
document.writeln("    <!--结束--> ");
document.writeln("");
document.writeln("    ");