document.writeln("");
document.writeln("<style>");
document.writeln("");
document.writeln(".cypt td {");
document.writeln("	text-align: center;");
document.writeln("	border: 1px solid #C0C0C0;");
document.writeln("	width: 25%;");
document.writeln("	height: 45px;");
document.writeln("	font-weight: 600;");
document.writeln("	font-size: 18px;");
document.writeln("	font-family:微软雅黑;");
document.writeln("}");
document.writeln("");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr><table id=\'table400939161\' width=\'100%\' border=\'1\' height=\'34\'>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『单双四肖』</font></font></b></table>");
document.writeln("");
document.writeln("</td>");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:1px solid #000\' align=center width=100% height=50>");
document.writeln("<p style=line-height:200%>");
document.writeln("<font size=\'4\' color=\'#0000FF\'><span style=font-family:微软雅黑>068期:﹝</span></font><span style=font-family:微软雅黑><font size=\'4\' color=\'#008000\'>单双四肖</font><font size=\'4\'><font color=\'#0000FF\'>﹞开:</font><font color=\'#FF0000\'>猫00</font></font></span><font color=\'#0000FF\'><font size=\'4\'><span style=font-family:微软雅黑>准</span></font><span style=font-size:13pt;font-family:微软雅黑><br>");
document.writeln("</span></font><font size=\'4\'><span style=font-family:微软雅黑>&#9658; 单﹝羊牛蛇兔﹞&#9668;</span></font><span style=font-size:13pt;font-family:微软雅黑><br>");
document.writeln("</span><font size=\'4\'><span style=font-family:微软雅黑>&#9658; 双﹝马龙狗虎﹞&#9668;</span></font></p>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:1px solid #000\' align=center width=100% height=50>");
document.writeln("<p style=line-height:200%>");
document.writeln("<font size=\'4\' color=\'#0000FF\'><span style=font-family:微软雅黑>066期:﹝</span></font><span style=font-family:微软雅黑><font size=\'4\' color=\'#008000\'>单双四肖</font><font size=\'4\'><font color=\'#0000FF\'>﹞开:</font><font color=\'#FF0000\'>狗42</font></font></span><font color=\'#0000FF\'><font size=\'4\'><span style=font-family:微软雅黑>准</span></font><span style=font-size:13pt;font-family:微软雅黑><br>");
document.writeln("</span></font><font size=\'4\'><span style=font-family:微软雅黑>&#9658; 单﹝羊猪蛇马﹞&#9668;</span></font><span style=font-size:13pt;font-family:微软雅黑><br>");
document.writeln("</span><font size=\'4\'><span style=font-family:微软雅黑>&#9658; 双﹝马鼠<span style=\'background-color: #00FF00\'>狗</span>龙﹞&#9668;</span></font></p>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:1px solid #000\' align=center width=100% height=50>");
document.writeln("<p style=line-height:200%>");
document.writeln("<font size=\'4\' color=\'#0000FF\'><span style=font-family:微软雅黑>065期:﹝</span></font><span style=font-family:微软雅黑><font size=\'4\' color=\'#008000\'>单双四肖</font><font size=\'4\'><font color=\'#0000FF\'>﹞开:</font><font color=\'#FF0000\'>羊09</font></font></span><font color=\'#0000FF\'><font size=\'4\'><span style=font-family:微软雅黑>准</span></font><span style=font-size:13pt;font-family:微软雅黑><br>");
document.writeln("</span></font><font size=\'4\'><span style=font-family:微软雅黑>&#9658; 单﹝牛兔<span style=\'background-color: #00FF00\'>羊</span>猪﹞&#9668;</span></font><span style=font-size:13pt;font-family:微软雅黑><br>");
document.writeln("</span><font size=\'4\'><span style=font-family:微软雅黑>&#9658; 双﹝马鼠狗虎﹞&#9668;</span></font></p>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<tr>");
document.writeln("<td style=\'color:#000;font-family:微软雅黑;font-weight:700;border:1px solid #000\' align=center width=100% height=50>");
document.writeln("<p style=line-height:200%>");
document.writeln("<font size=\'4\' color=\'#0000FF\'><span style=font-family:微软雅黑>064期:﹝</span></font><span style=font-family:微软雅黑><font size=\'4\' color=\'#008000\'>单双四肖</font><font size=\'4\'><font color=\'#0000FF\'>﹞开:</font><font color=\'#FF0000\'>马46</font></font></span><font color=\'#0000FF\'><font size=\'4\'><span style=font-family:微软雅黑>准</span></font><span style=font-size:13pt;font-family:微软雅黑><br>");
document.writeln("</span></font><font size=\'4\'><span style=font-family:微软雅黑>&#9658; 单﹝鸡牛蛇羊﹞&#9668;</span></font><span style=font-size:13pt;font-family:微软雅黑><br>");
document.writeln("</span><font size=\'4\'><span style=font-family:微软雅黑>&#9658; 双﹝<span style=\'background-color: #00FF00\'>马</span>龙虎鼠﹞&#9668;</span></font></p>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("");
document.writeln("</html>");