document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『精选三头』</font></font></b></table>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>070</font><span style=box-sizing:border-box;font-size:14pt><font face=\'微软雅黑\'><b><span style=box-sizing:border-box;><font color=\'#008000\'>期<img src=\'https://67292c.com/images/kou.png\' style=\'width:20px\' height=\'15\'></font><font color=\'#000000\'>【0-0-0】头</font> <font color=\'#0000FF\'>开:￥00准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>069</font><span style=box-sizing:border-box;font-size:14pt><font face=\'微软雅黑\'><b><span style=box-sizing:border-box;><font color=\'#008000\'>期<img src=\'https://67292c.com/images/kou.png\' style=\'width:20px\' height=\'15\'></font><font color=\'#000000\'>【0-0-0】头</font> <font color=\'#0000FF\'>开:￥00准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>068</font><span style=box-sizing:border-box;font-size:14pt><font face=\'微软雅黑\'><b><span style=box-sizing:border-box;><font color=\'#008000\'>期<img src=\'https://67292c.com/images/kou.png\' style=\'width:20px\' height=\'15\'></font><font color=\'#000000\'>【1-3-2】头</font> <font color=\'#0000FF\'>开:￥00准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680c.com/\'>点击玄机网</a></font><a target=\'_blank\' href=\'https://868680c.com/#51\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>马会传真</font><font color=\'#FFFFFF\'>『1句解平特』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--内容开始-->");
document.writeln("<table border=\'1\' width=\'100%\' cellspacing=\'0\' cellpadding=\'0\' bordercolor=\'#008000\' style=\'border-collapse: collapse; border-spacing: 0px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; color: rgb(255, 0, 0); font-size: 18.6667px; font-variant-ligatures: normal; orphans: 2; font-family: Simsun; padding: 0px; margin: 0px; word-wrap: break-word; background-color: rgb(255, 255, 255);\' height=\'43\'>");
document.writeln("	<tr>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'43\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' size=\'3\' color=\'#0000FF\'>068期</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'43\' width=\'54%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>【铁马冰河入梦来】</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'43\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'left\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		</font><font size=\'3\' face=\'微软雅黑\' color=\'#0000FF\'>开000</font></td>");
document.writeln("	</tr>");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("<table id=\'table400900750\' border=\'1\' bordercolor=\'#ffcccc\' width=\'100%\' bgcolor=\'#ffffff\' style=\'font-family: &quot;Microsoft YaHei&quot;; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border-bottom-style: solid; padding: 0px; margin: 0px; word-wrap: break-word; border-top-style: solid; font-size: 9pt;\'>");
document.writeln("<tbody style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'>澳门马会传真</font></span><span style=box-sizing:border-box;><font size=\'5\' color=\'#FF00FF\'>67</font><font size=\'4\' color=\'#0000FF\'>29</font><font size=\'4\' color=\'#008000\'>2a</font><font size=\'4\' color=\'#FF0000\'>.com</font></span><font color=\'#000000\'><span style=box-sizing:border-box;font-size:14pt>一定谨记!</span></font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");