document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>马会传真</font><font color=\'#FFFFFF\'>『澳门火车头』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>067</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤狗。诗：龙死羊伤，一家人进四家门。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：关注澳门马会传真67292c.com</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>066</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤虎。诗：兔死狗伤，离家三秋保家园。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开狗42</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>065</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤猴。诗：虎死羊伤，万紫千红艳阳天。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开羊09</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>064</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤龙。诗：鸡死兔伤，三亩野地草丛生。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开马46</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>063</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤牛。诗：虎死蛇伤，阴暗之地戏红颜。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开猴32</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>062</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤狗。诗：牛死鼠伤，一年一景美春秋。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开牛27</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>061</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤龙。诗：鸡死鼠伤，胆大包天娶两妾。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开马46</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>060</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤龙。诗：鸡死鼠伤，胆大包天娶两妾。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开牛39</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>059</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤龙。诗：猴死羊伤，强占民女真土匪。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开牛39</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>058</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤鸡。诗：狗死龙伤，春满人间家和美。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开兔49</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>057</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤狗。诗：牛死虎伤，春江之水天上来。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开牛03</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>056</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤马。诗：鸡死蛇伤，五湖四海龙飞天。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开羊21</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>055</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤鸡。诗：龙死虎伤，西行大战牛魔王。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开狗06</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>054</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤鸡。诗：牛死猴伤，仰面朝天传华夏。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开马46</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>053</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤猴。诗：羊死猪伤，忠心不二伴君旁。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开羊21</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>052</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤蛇。诗：兔死鼠伤，日进斗金东家乐。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开虎26</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>051</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤羊。诗：猴死狗伤，土地金贵农家情。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开猪05</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>050</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤马。诗：蛇死猪伤，日出东方夕阳美。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开蛇23</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>049</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤龙。诗：虎死牛伤，夏日最热三伏天。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开兔13</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>048</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤马。诗：蛇死鸡伤，九五之尊本正气。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开虎02</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>047</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤狗。诗：龙死兔伤，黑帮中计二突围。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开龙12</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>046</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤猴。诗：鼠死鸡伤，日出东方夕阳红。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开狗30</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>045</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤羊。诗：狗死鼠伤，潵酒三杯敬好汉。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开鼠16</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>044</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤龙。诗：鸡死兔伤，四五稳来绿地养");
document.writeln("。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开蛇11</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>043</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤猴。诗：马死鸡伤，三山二水照红阳");
document.writeln("。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开牛39</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>042</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤虎。诗：鸡死牛伤，万贯金银一天尽。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开猪05</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>041</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤龙。诗：猪死马伤，子行千里家人忧。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开蛇23</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>040</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤猴。诗：虎死羊伤，遍地黄金三头寻。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开鸡31</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>039</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤羊。诗：兔死鸡伤，书香世家金粉玉。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开羊09</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\'>038</font><span style=box-sizing:border-box;><font face=\'微软雅黑\'><b><font color=\'#000000\'>期火车头:</font><font color=\'#FF0000\'>烧伤兔。诗：龙死鸡伤，灯红酒绿会靓女。</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>解：特开狗30</font></b><font color=\'#0000FF\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--网址开始-->");
document.writeln("<tr>");
document.writeln("");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292a.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'>澳门马会传真</font><font size=\'5\' color=\'#FF00FF\'>67</font></span></span><font size=\'4\' color=\'#0000FF\'><span style=box-sizing:border-box;>29</span></font><font size=\'4\' color=\'#008000\'><span style=box-sizing:border-box;>2</span></font><font size=\'4\' color=\'#008000\'><span style=box-sizing:border-box;>a</span></font><span style=box-sizing:border-box;font-size:14pt><font size=\'4\' color=\'#FF0000\'>.com</font></span><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("<!--网址结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("</body>");
document.writeln("");
document.writeln("");
document.writeln("</html>");