document.writeln("<html>");
document.writeln("");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>澳门马会传真</title>");
document.writeln("<style type=\'text/css\'>");
document.writeln(".style1 {");
document.writeln("background-color: #FFFF00;");
document.writeln("}");
document.writeln("table{");
document.writeln("WIDOWS: 1; TEXT-TRANSFORM: none; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; BORDER-SPACING: 0px; BORDER-COLLAPSE: collapse; FONT: 14px/21px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(68,68,68); WORD-SPACING: 0px; -webkit-text-stroke-width: 0px\' border=\'1\' cellSpacing=\'0\' cellPadding=\'0\' width=\'100%\' height=\'40\' id=\'table119\'");
document.writeln("}");
document.writeln("td{");
document.writeln("BORDER-BOTTOM: rgb(229,229,229) 1px solid; BORDER-LEFT: rgb(229,229,229) 1px solid; PADDING-BOTTOM: 3px; MARGIN: 0px; PADDING-LEFT: 2px; PADDING-RIGHT: 2px; WORD-BREAK: break-all; BORDER-TOP: rgb(229,229,229) 1px solid; BORDER-RIGHT: rgb(229,229,229) 1px solid; PADDING-TOP: 3px\' bgColor=\'#ffffff\' align=\'left\'");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html><html>");
document.writeln("");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>澳门马会传真</title>");
document.writeln("<style type=\'text/css\'>");
document.writeln(".style1 {");
document.writeln("background-color: #FFFF00;");
document.writeln("}");
document.writeln("table{");
document.writeln("WIDOWS: 1; TEXT-TRANSFORM: none; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; BORDER-SPACING: 0px; BORDER-COLLAPSE: collapse; FONT: 14px/21px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(68,68,68); WORD-SPACING: 0px; -webkit-text-stroke-width: 0px\' border=\'1\' cellSpacing=\'0\' cellPadding=\'0\' width=\'100%\' height=\'40\' id=\'table119\'");
document.writeln("}");
document.writeln("td{");
document.writeln("BORDER-BOTTOM: rgb(229,229,229) 1px solid; BORDER-LEFT: rgb(229,229,229) 1px solid; PADDING-BOTTOM: 3px; MARGIN: 0px; PADDING-LEFT: 2px; PADDING-RIGHT: 2px; WORD-BREAK: break-all; BORDER-TOP: rgb(229,229,229) 1px solid; BORDER-RIGHT: rgb(229,229,229) 1px solid; PADDING-TOP: 3px\' bgColor=\'#ffffff\' align=\'left\'");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『红蓝绿肖』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=\'WIDOWS: 1; TEXT-TRANSFORM: none; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; BORDER-SPACING: 0px; BORDER-COLLAPSE: collapse; FONT: 14px/21px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(68,68,68); WORD-SPACING: 0px; -webkit-text-stroke-width: 0px\' border=\'1\' cellSpacing=\'0\' cellPadding=\'0\' width=\'100%\' height=\'40\' id=\'table119\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=40 style=\'border-style: solid; border-width: 1px\'><b>");
document.writeln("<font style=\'font-size: 14pt\' color=\'#FF0000\'>红肖：马、兔、鼠、鸡</font><font style=\'font-size: 14pt\' color=\'#FF00FF\'><br></font>");
document.writeln("<font style=\'font-size: 14pt\' color=\'#008000\'>绿肖：羊、龙、牛、狗</font><font style=\'font-size: 14pt\' color=\'#FF00FF\'><br>");
document.writeln("");
document.writeln("</font>");
document.writeln("<font style=\'font-size: 14pt\' color=\'#0000FF\'>蓝肖：蛇、虎、猪、猴</font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=42 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<font size=\'4\' color=\'#008000\'><b>067</b></font><b><font size=\'4\'><font color=\'#008000\'>期必开</font>【<font color=\'#FF0000\'>蓝肖红肖</font>】开<font color=\'#0000FF\'>？00准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=42 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<font size=\'4\' color=\'#008000\'><b>065</b></font><b><font size=\'4\'><font color=\'#008000\'>期必开</font>【<font color=\'#FF0000\'>蓝肖<span style=\'background-color: #FFFF00\'>绿肖</span></font>】开<font color=\'#0000FF\'>羊09准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=42 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<font size=\'4\' color=\'#008000\'><b>064</b></font><b><font size=\'4\'><font color=\'#008000\'>期必开</font>【<font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>红肖</span>绿肖</font>】开<font color=\'#0000FF\'>马46准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=42 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<font size=\'4\' color=\'#008000\'><b>063</b></font><b><font size=\'4\'><font color=\'#008000\'>期必开</font>【<font color=\'#FF0000\'>红肖<span style=\'background-color: #FFFF00\'>蓝肖</span></font>】开<font color=\'#0000FF\'>猴32准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=42 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<font size=\'4\' color=\'#008000\'><b>062</b></font><b><font size=\'4\'><font color=\'#008000\'>期必开</font>【<font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>绿肖</span>蓝肖</font>】开<font color=\'#0000FF\'>牛27准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=42 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<font size=\'4\' color=\'#008000\'><b>060</b></font><b><font size=\'4\'><font color=\'#008000\'>期必开</font>【<font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>红肖</span>蓝肖</font>】开<font color=\'#0000FF\'>鼠04准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=42 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<font size=\'4\' color=\'#008000\'><b>059</b></font><b><font size=\'4\'><font color=\'#008000\'>期必开</font>【<font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>绿肖</span>蓝肖</font>】开<font color=\'#0000FF\'>牛39准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=42 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<font size=\'4\' color=\'#008000\'><b>058</b></font><b><font size=\'4\'><font color=\'#008000\'>期必开</font>【<font color=\'#FF0000\'><span style=\'background-color: #FFFF00\'>红肖</span>蓝肖</font>】开<font color=\'#0000FF\'>兔49准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("");
document.writeln("</table>");
document.writeln("<p style=\'box-sizing: border-box; margin: 0; padding: 0\' align=\'center\'>");
document.writeln("<font face=\'微软雅黑\'>&nbsp;</font></p>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");