document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100% style=\'border-collapse: collapse\'>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'58\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『四组三连』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("     <tr>");
document.writeln("    <td align=\'center\'><b><font size=\'4\'>067期（三连肖/11.1倍）</br>");
document.writeln("    【<font color=\'#FF0000\'>猪龙马</font>】 【<font color=\'#FF0000\'>鼠狗羊</font>】</br>");
document.writeln("    【<font color=\'#FF0000\'>猴虎牛</font>】 【<font color=\'#FF0000\'>兔鸡蛇</font>】</br>");
document.writeln("    <font color=\'#0000FF\'>开奖结果：00-00-00-00-00-00T00</font></font></font></font></font></font></b><font size=\'4\'></br>");
document.writeln("	</font></td>");
document.writeln("    </tr>");
document.writeln("    ");
document.writeln("    ");
document.writeln("    ");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680c.com/\'>点击玄机网</a></font><a target=\'_blank\' href=\'https://868680c.com/#51\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'58\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'55\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 49px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『复式连尾』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=52><b><font style=\'font-size: 14pt\' face=\'楷体\'>067期<font color=\'#008000\'>复试连尾</font>【9-6-7-0-3】<br><font color=\'#FF00FF\'>");
document.writeln("	开奖结果：00-00-00-00-00-00T00</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680c.com/\'>点击玄机网</a></font><a target=\'_blank\' href=\'https://868680c.com/#51\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<!--网址结束-->");
document.writeln("</span>");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");