document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'54\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 48px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『⑥肖⑥码』</font></font></b></table>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>068期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>《⑥肖⑥码》</font><font face=\'微软雅黑\' size=\'4\' color=\'#008000\'>开？00准</font><br>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>");
document.writeln("(蛇23)(羊21)(牛15)(马34)(龙24)(鸡19)</font></font></span></b><font color=\'#FF0000\'><font color=\'#FF0000\'><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>067期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>《⑥肖⑥码》</font><font face=\'微软雅黑\' size=\'4\' color=\'#008000\'>开猴08准</font><br>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>");
document.writeln("(兔13)(虎38)(<span style=\'background-color: #FFFF00\'>猴</span>20)(马34)(龙24)(猪17)</font></font></span></b><font color=\'#FF0000\'><font color=\'#FF0000\'><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>066期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>《⑥肖⑥码》</font><font face=\'微软雅黑\' size=\'4\' color=\'#008000\'>开狗42准</font><br>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>");
document.writeln("(<span style=\'background-color: #FFFF00\'>狗</span>18)(猪17)(羊33)(马34)(蛇23)(鼠28)</font></font></span></b><font color=\'#FF0000\'><font color=\'#FF0000\'><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>065期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>《⑥肖⑥码》</font><font face=\'微软雅黑\' size=\'4\' color=\'#008000\'>开羊09准</font><br>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>");
document.writeln("(兔13)(虎38)(<span style=\'background-color: #FFFF00\'>羊09</span>)(马34)(牛15)(鼠28)</font></font></span></b><font color=\'#FF0000\'><font color=\'#FF0000\'><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#000000\'>064期:</font><font face=\'微软雅黑\' size=\'4\' color=\'#FF33CC\'>《⑥肖⑥码》</font><font face=\'微软雅黑\' size=\'4\' color=\'#008000\'>开马46准</font><br>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>");
document.writeln("(兔37)(虎38)(龙12)(<span style=\'background-color: #FFFF00\'>马</span>34)(鸡31)(鼠28)</font></font></span></b><font color=\'#FF0000\'><font color=\'#FF0000\'><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680c.com/\'><font color=\'#000000\'>点击玄机网</font></a></font><a target=\'_blank\' href=\'https://868680c.com/#51\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");
document.writeln("");