document.writeln("<html>");
document.writeln("");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 1</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'59\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 53px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『买肖输尽光』</font></font></b></table>");
document.writeln("<table border=\'1\' width=\'100%\' cellspacing=\'0\' cellpadding=\'0\' bordercolor=\'#008000\' style=\'border-collapse: collapse; border-spacing: 0px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; color: rgb(255, 0, 0); font-size: 18.6667px; font-variant-ligatures: normal; orphans: 2; font-family: Simsun; padding: 0px; margin: 0px; word-wrap: break-word; background-color: rgb(255, 255, 255);\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	<tr>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'30\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' size=\'3\' color=\'#0000FF\'>068期</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'30\' width=\'54%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>今期买<span style=\'background-color: #FFFF00\'>兔鸡猪</span>输尽光</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'30\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		</font><font size=\'3\' face=\'微软雅黑\' color=\'#0000FF\'>开？00</font></td>");
document.writeln("	</tr>");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("		<tr>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'30\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' size=\'3\' color=\'#0000FF\'>066期</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'30\' width=\'54%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>今期买<span style=\'background-color: #FFFF00\'>猴马牛</span>输尽光</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'30\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		</font><font size=\'3\' face=\'微软雅黑\' color=\'#0000FF\'>开狗42</font></td>");
document.writeln("	</tr>");
document.writeln("");
document.writeln("	");
document.writeln("		<tr>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'30\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' size=\'3\' color=\'#0000FF\'>065期</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'30\' width=\'54%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>今期买<span style=\'background-color: #FFFF00\'>猴鸡虎</span>输尽光</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'30\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		</font><font size=\'3\' face=\'微软雅黑\' color=\'#0000FF\'>开羊09</font></td>");
document.writeln("	</tr>");
document.writeln("	");
document.writeln("");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'30\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' size=\'3\' color=\'#0000FF\'>064期</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'30\' width=\'54%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		<font face=\'微软雅黑\' color=\'#FF0000\'>今期买<span style=\'background-color: #FFFF00\'>牛蛇鸡</span>输尽光</font></td>");
document.writeln("		<td bgcolor=\'#FFFFFF\' height=\'30\' width=\'23%\' style=\'margin: 0px; padding: 0px; border: 1px solid rgb(229, 229, 229); word-wrap: break-word;\'>");
document.writeln("		<p align=\'center\' style=\'margin: 0px 0px 8px; padding: 0px;\'>");
document.writeln("		</font><font size=\'3\' face=\'微软雅黑\' color=\'#0000FF\'>开马46</font></td>");
document.writeln("	</tr>");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("<table id=\'table400900750\' border=\'1\' bordercolor=\'#ffcccc\' width=\'100%\' bgcolor=\'#ffffff\' style=\'font-family: &quot;Microsoft YaHei&quot;; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; border-bottom-style: solid; padding: 0px; margin: 0px; word-wrap: break-word; border-top-style: solid; font-size: 9pt;\'>");
document.writeln("<tbody style=\'padding: 0px; margin: 0px; word-wrap: break-word;\'>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'>澳门马会传真</font></span><span style=box-sizing:border-box;><font size=\'5\' color=\'#FF00FF\'>67</font><font size=\'4\' color=\'#0000FF\'>29</font><font size=\'4\' color=\'#008000\'>2c</font><font size=\'4\' color=\'#FF0000\'>.com</font></span><font color=\'#000000\'><span style=box-sizing:border-box;font-size:14pt>一定谨记!</span></font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");
document.writeln("");