document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'taext/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『复式3中3』</font></font></b></table>");
document.writeln("");
document.writeln("<table id=\'table52\' border=\'1\' width=\'100%\'>");
document.writeln("");
document.writeln("		<tr>");
document.writeln("		<td><p align=center><strong>");
document.writeln("		<span style=\'font-family: 微软雅黑; font-size: large\'>068</span><span style=font-family:微软雅黑;font-size:large>期<span style=color:red>【八码复式三中三】650倍</span><br>");
document.writeln("		「09.11.06.45.16.39.26.27」<br>");
document.writeln("		开奖：00-00-00-00-00-00特00<br><span style=color:#FF6600>澳门马会传真</span><span style=color:#00f>67</span><font color=\'#FF00FF\'>292</font><span style=color:green>b.com</span></span></strong>");
document.writeln("         </tr>");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("	</table>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");