document.writeln("<table border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100% height=\'151\'>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 50px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『经典杀码』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=44><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#0000FF\'>068期：大刀砍杀→</font><font face=\'微软雅黑\' color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>开？00准</span></font><br>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\' size=\'4\'>");
document.writeln("33.06.07.37.03.20.45.46.38.44.08.35</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=44><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#0000FF\'>067期：大刀砍杀→</font><font face=\'微软雅黑\' color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>开猴08准</span></font><br>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\' size=\'4\'>");
document.writeln("05.09.36.02.46.04.13.41.24.06.22.29</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=44><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#0000FF\'>066期：大刀砍杀→</font><font face=\'微软雅黑\' color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>开狗42准</span></font><br>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\' size=\'4\'>");
document.writeln("25.09.27.18.44.41.35.40.01.34.46.49</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=44><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#0000FF\'>065期：大刀砍杀→</font><font face=\'微软雅黑\' color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>开羊09准</span></font><br>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\' size=\'4\'>");
document.writeln("27.44.12.38.45.42.20.14.18.17.35.49</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=44><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#0000FF\'>064期：大刀砍杀→</font><font face=\'微软雅黑\' color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>开马46准</span></font><br>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\' size=\'4\'>");
document.writeln("48.16.41.07.17.25.34.33.21.26.37.36</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=44><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#0000FF\'>063期：大刀砍杀→</font><font face=\'微软雅黑\' color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>开猴32准</span></font><br>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\' size=\'4\'>");
document.writeln("17.29.15.12.04.20.22.19.10.02.33.18</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=44><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#0000FF\'>061期：大刀砍杀→</font><font face=\'微软雅黑\' color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>开马46准</span></font><br>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\' size=\'4\'>");
document.writeln("25.13.14.02.33.24.44.32.39.09.45.05</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=44><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#0000FF\'>060期：大刀砍杀→</font><font face=\'微软雅黑\' color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>开鼠04准</span></font><br>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\' size=\'4\'>");
document.writeln("43.49.42.25.06.11.08.38.29.27.45.15</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=44><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'4\' color=\'#0000FF\'>059期：大刀砍杀→</font><font face=\'微软雅黑\' color=\'#FF0000\' size=\'4\'><span style=\'background-color: #FFFF00\'>开牛39准</span></font><br>");
document.writeln("<font face=\'微软雅黑\' color=\'#000000\' size=\'4\'>");
document.writeln("29.31.04.43.32.02.17.01.21.07.05.15</font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=41><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'>澳门马会传真</font></span><font size=\'5\' color=\'#FF00FF\'><span style=box-sizing:border-box;>67</font><font size=\'4\' color=\'#0000FF\'><span style=box-sizing:border-box;>29</span></font><font size=\'4\' color=\'#008000\'><span style=box-sizing:border-box;>2a</span></font><span style=box-sizing:border-box;font-size:14pt><font size=\'4\' color=\'#FF0000\'>.com</font></span></span><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln(" ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『四头四行』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=35><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>068期</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'> </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#FF0000\'>4312头，火土木金行</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>&nbsp; </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>开：？00准</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=35><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>067期</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'> </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#FF0000\'>");
document.writeln("<span style=\'background-color: #00FF00\'>0</span>312头，水土木金行</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>&nbsp; </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>开：猴08准</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=35><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>066期</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'> </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#FF0000\'>0312头，<span style=\'background-color: #00FF00\'>水</span>金木火行</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>&nbsp; </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>开：狗42准</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=35><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>065期</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'> </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#FF0000\'>");
document.writeln("<span style=\'background-color: #00FF00\'>0</span>312头，水土火木行</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>&nbsp; </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>开：羊09准</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=35><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>064期</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'> </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#FF0000\'>031<span style=\'background-color: #00FF00\'>4</span>头，金土<span style=\'background-color: #00FF00\'>火</span>木行</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>&nbsp; </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>开：马46准</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=35><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>063期</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'> </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#FF0000\'>0<span style=\'background-color: #00FF00\'>3</span>12头，<span style=\'background-color: #00FF00\'>金</span>土水木行</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>&nbsp; </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>开：猴32准</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=35><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>062期</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'> </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#FF0000\'>");
document.writeln("<span style=\'background-color: #00FF00\'>2</span>314头，金火<span style=\'background-color: #00FF00\'>水</span>木行</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>&nbsp; </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>开：牛27准</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=35><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>061期</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'> </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#FF0000\'>2<span style=\'background-color: #00FF00\'>4</span>31头，土<span style=\'background-color: #00FF00\'>火</span>水木行</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>&nbsp; </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>开：马46准</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=35><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>060期</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'> </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#FF0000\'>2<span style=\'background-color: #00FF00\'>0</span>31头，<span style=\'background-color: #00FF00\'>土</span>火金木行</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>&nbsp; </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>开：鼠04准</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=35><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>059期</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'> </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#FF0000\'>2<span style=\'background-color: #00FF00\'>3</span>41头，水火<span style=\'background-color: #00FF00\'>金</span>木行</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>&nbsp; </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>开：牛39准</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=35><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>058期</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'> </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#FF0000\'>23<span style=\'background-color: #00FF00\'>4</span>1头，土火金木行</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>&nbsp; </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>开：兔49准</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=34><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>057期</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'> </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#FF0000\'>");
document.writeln("<span style=\'background-color: #00FF00\'>0</span>341头，金<span style=\'background-color: #00FF00\'>土</span>火水行</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'>&nbsp; </font>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#0000FF\'>开：牛03准</font><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#008000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'https://67292c.com/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680c.com/\'>澳门玄机网</a></font><a target=\'_blank\' href=\'https://868680c.com/\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("");
document.writeln("");
document.writeln("</table>");