document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'taext/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<tbody>");
document.writeln("");
document.writeln("	");
document.writeln("	");
document.writeln("	<tr>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100% height=\'106\'>");
document.writeln("<td style=\'text-align:center\' height=\'61\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 50px;\' bgcolor=#800000>");
document.writeln("<p align=center>");
document.writeln("<b><font color=\'#FFFFFF\' face=\'楷体\' style=\'font-size: 19pt\'>马会传真【平1肖1码】</font></b></table>");
document.writeln("	</tr>");
document.writeln("");
document.writeln("	");
document.writeln("			<tr>");
document.writeln("			<td height=\'46\'>");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#008000\'>068期：</font><font color=\'#FF00FF\' size=\'4\'>独平</font><font color=\'#FF00FF\' size=\'5\'>【猪05】</font><font color=\'#0000FF\' size=\'4\'>开0000准</font></b></td>");
document.writeln("		</tr>");
document.writeln("		");
document.writeln("		");
document.writeln("					<tr>");
document.writeln("			<td height=\'46\'>");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#008000\'>067期：</font><font color=\'#FF00FF\' size=\'4\'>独平</font><font color=\'#FF00FF\' size=\'5\'>【猴44】</font><font color=\'#0000FF\' size=\'4\'>开猴08准</font></b></td>");
document.writeln("		</tr>");
document.writeln("");
document.writeln("		");
document.writeln("		");
document.writeln("					<tr>");
document.writeln("			<td height=\'46\'>");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#008000\'>066期：</font><font color=\'#FF00FF\' size=\'4\'>独平</font><font color=\'#FF00FF\' size=\'5\'>【牛15】</font><font color=\'#0000FF\' size=\'4\'>开牛27准</font></b></td>");
document.writeln("		</tr>");
document.writeln("");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("			<tr>");
document.writeln("			<td height=\'46\'>");
document.writeln("					<p align=\'center\'><font size=\'4\' color=\'#008000\'>065期：</font><font color=\'#FF00FF\' size=\'4\'>独平</font><font color=\'#FF00FF\' size=\'5\'>【狗06】</font><font color=\'#0000FF\' size=\'4\'>开狗30准</font></b></td>");
document.writeln("		</tr>");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln(" ");
document.writeln("		<table style=border-collapse:collapse border=0 width=100% height=\'33\'><tbody><tr>");
document.writeln("			<td height=33><p style=text-align:center><strong>");
document.writeln("			<img src=https://www.62755a.com/images/zu.gif  width=35 height=20><span style=font-family:楷体;color:#00f><font size=\'4\'>澳门马会传真</font></span><span style=font-family:楷体;><font color=\'#FF0000\' size=\'5\'>67292b</font><font size=\'5\'>.com</strong></tr></table>");
document.writeln("");
document.writeln("</tr></table>");
document.writeln("");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");