document.writeln("");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'56\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 50px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『正版诗象』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<span style=box-sizing:border-box;><b><font face=\'微软雅黑\'><font color=\'#FF0000\'>");
document.writeln("067期澳门正版诗象（开？00）</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>倩。倩女幽魂美哉。一句猜：（绿特）鸡爆。 提供：(大单)。</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<span style=box-sizing:border-box;><b><font face=\'微软雅黑\'><font color=\'#FF0000\'>");
document.writeln("066期澳门正版诗象（开狗42）</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>穷，丑，上天渡劫。一句猜：红花开码。提供：(六合）。</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<span style=box-sizing:border-box;><b><font face=\'微软雅黑\'><font color=\'#FF0000\'>");
document.writeln("065期澳门正版诗象（开羊09）</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>妖，整日作妖。一句猜：无福无报。提供：(44)中特。</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<span style=box-sizing:border-box;><b><font face=\'微软雅黑\'><font color=\'#FF0000\'>");
document.writeln("064期澳门正版诗象（开马46）</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>草，吃草挨饿，一句猜：老人。提供：死后发，（六后）。</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<span style=box-sizing:border-box;><b><font face=\'微软雅黑\'><font color=\'#FF0000\'>");
document.writeln("063期澳门正版诗象（开猴32）</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>野，山野丛林。一句猜：（狠)中特。提供：(死)。</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<span style=box-sizing:border-box;><b><font face=\'微软雅黑\'><font color=\'#FF0000\'>");
document.writeln("062期澳门正版诗象（开牛27）</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>钱，（金元宝）。一句猜：（天下无敌）。提供：（2，1，3）出特</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<span style=box-sizing:border-box;><b><font face=\'微软雅黑\'><font color=\'#FF0000\'>");
document.writeln("061期澳门正版诗象（开马46）</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>无，无头无尾。一句猜：（像东像西）直中。提供：（汪）</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<span style=box-sizing:border-box;><b><font face=\'微软雅黑\'><font color=\'#FF0000\'>");
document.writeln("060期澳门正版诗象（开鼠04）</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>凶。状元招杀身。（八）必中。一句猜：（七）。提供：（大）</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<span style=box-sizing:border-box;><b><font face=\'微软雅黑\'><font color=\'#FF0000\'>");
document.writeln("059期澳门正版诗象（开牛39）</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>草，吃草出力做牛马，一句猜：长胡须。提供：（特6后）</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<span style=box-sizing:border-box;><b><font face=\'微软雅黑\'><font color=\'#FF0000\'>");
document.writeln("058期澳门正版诗象（开兔49）</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>（虎类）。桌上肉。一句猜：忠诚卫士第一集。提供：（猪）</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<span style=box-sizing:border-box;><b><font face=\'微软雅黑\'><font color=\'#FF0000\'>");
document.writeln("057期澳门正版诗象（开牛03）</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>庄，神圣佛相，不可（一世），一句猜，威威惊雷，提供，(42）</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<span style=box-sizing:border-box;><b><font face=\'微软雅黑\'><font color=\'#FF0000\'>");
document.writeln("056期澳门正版诗象（开羊21）</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>白。白日做梦。一句猜：(五块)肥肉定中特。提供：(鸡羊)</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<span style=box-sizing:border-box;><b><font face=\'微软雅黑\'><font color=\'#FF0000\'>");
document.writeln("055期澳门正版诗象（开狗06）</font><font color=\'#000000\'><br></font>");
document.writeln("<font color=\'#0000FF\'>朱，朱红（酒绿）。一句猜：一了百了。提供：（蓝）</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--网址开始-->");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'>澳门马会传真</font><font size=\'5\' color=\'#FF00FF\'>67</font></span><font size=\'4\' color=\'#0000FF\'><span style=box-sizing:border-box;>29</span></font><font size=\'4\' color=\'#008000\'><span style=box-sizing:border-box;>2a</span></font><font size=\'4\' color=\'#FF0000\'>.com</font></span><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("<!--网址结束-->");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("");
document.writeln("</html>");