document.writeln("<html>");
document.writeln("");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>澳门马会传真</title>");
document.writeln("<style type=\'text/css\'>");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table style=\'WIDOWS: 1; TEXT-TRANSFORM: none; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; BORDER-SPACING: 0px; BORDER-COLLAPSE: collapse; FONT: 14px/21px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(68,68,68); WORD-SPACING: 0px; -webkit-text-stroke-width: 0px\' border=\'1\' cellSpacing=\'0\' cellPadding=\'0\' width=\'100%\' height=\'40\' id=\'table119\'>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『菜肉草肖』</font></font></b></table>");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=38><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\' size=\'2\'>");
document.writeln("<b>");
document.writeln("<span style=box-sizing:border-box;><font color=\'#0000FF\'>吃肉肖(虎蛇龙狗)</font><font color=\'#FF0000\'>吃菜肖(猪鼠鸡猴)</font><font color=\'#008000\'>吃草肖(牛羊马兔)</font></span></b><span style=box-sizing:border-box;><font color=\'#008000\'></strong>");
document.writeln("</font></font>");
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=41><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>068</font></b><span style=box-sizing:border-box;font-size:14pt><font face=\'微软雅黑\'><b><span style=box-sizing:border-box;><font color=\'#000000\'>期</font><font color=\'#008000\'>菜肉草肖</font><font color=\'#FF0000\'>【吃草吃肉】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>￥00</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=41><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>067</font></b><span style=box-sizing:border-box;font-size:14pt><font face=\'微软雅黑\'><b><span style=box-sizing:border-box;><font color=\'#000000\'>期</font><font color=\'#008000\'>菜肉草肖</font><font color=\'#FF0000\'>【吃草<span style=\'background-color: #FFFF00\'>吃菜</span>】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>猴08</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=41><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>066</font></b><span style=box-sizing:border-box;font-size:14pt><font face=\'微软雅黑\'><b><span style=box-sizing:border-box;><font color=\'#000000\'>期</font><font color=\'#008000\'>菜肉草肖</font><font color=\'#FF0000\'>【<span style=\'background-color: #FFFF00\'>吃肉</span>吃菜】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>狗42</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=41><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>064</font></b><span style=box-sizing:border-box;font-size:14pt><font face=\'微软雅黑\'><b><span style=box-sizing:border-box;><font color=\'#000000\'>期</font><font color=\'#008000\'>菜肉草肖</font><font color=\'#FF0000\'>【吃肉<span style=\'background-color: #FFFF00\'>吃草</span>】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>马46</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=41><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>063</font></b><span style=box-sizing:border-box;font-size:14pt><font face=\'微软雅黑\'><b><span style=box-sizing:border-box;><font color=\'#000000\'>期</font><font color=\'#008000\'>菜肉草肖</font><font color=\'#FF0000\'>【吃肉<span style=\'background-color: #FFFF00\'>吃菜</span>】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>猴32</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=41><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>061</font></b><span style=box-sizing:border-box;font-size:14pt><font face=\'微软雅黑\'><b><span style=box-sizing:border-box;><font color=\'#000000\'>期</font><font color=\'#008000\'>菜肉草肖</font><font color=\'#FF0000\'>【吃肉<span style=\'background-color: #FFFF00\'>吃草</span>】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>马46</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=41><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<b><font face=\'微软雅黑\' style=\'font-size: 14pt\' color=\'#000000\'>060</font></b><span style=box-sizing:border-box;font-size:14pt><font face=\'微软雅黑\'><b><span style=box-sizing:border-box;><font color=\'#000000\'>期</font><font color=\'#008000\'>菜肉草肖</font><font color=\'#FF0000\'>【吃肉<span style=\'background-color: #FFFF00\'>吃菜</span>】</font><font color=\'#000000\'>开</font><span style=\'background-color: #FFFF00\'><font color=\'#FF00FF\'>鼠04</font></span><font color=\'#000000\'>准</font></span></b><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40><p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'><a target=\'_blank\' href=\'https://868680a.com/\'>点击玄机网</a></font><a target=\'_blank\' href=\'https://868680a.com/#51\'><font size=\'5\' color=\'#FF00FF\'>86</font><font size=\'4\' color=\'#0000FF\'>86</font><font size=\'4\' color=\'#008000\'>80</font><font size=\'4\' color=\'#FF0000\'>.com</font></a></span><font color=\'#000000\'>一定谨记!</font></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("");
document.writeln("</table>");
document.writeln("<p style=\'box-sizing: border-box; margin: 0; padding: 0\' align=\'center\'>");
document.writeln("<font face=\'微软雅黑\'></font></p>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");