document.writeln("<html>");
document.writeln("");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>澳门马会传真</title>");
document.writeln("<style type=\'text/css\'>");
document.writeln(".style1 {");
document.writeln("background-color: #FFFF00;");
document.writeln("}");
document.writeln("table{");
document.writeln("WIDOWS: 1; TEXT-TRANSFORM: none; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; BORDER-SPACING: 0px; BORDER-COLLAPSE: collapse; FONT: 14px/21px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(68,68,68); WORD-SPACING: 0px; -webkit-text-stroke-width: 0px\' border=\'1\' cellSpacing=\'0\' cellPadding=\'0\' width=\'100%\' height=\'40\' id=\'table119\'");
document.writeln("}");
document.writeln("td{");
document.writeln("BORDER-BOTTOM: rgb(229,229,229) 1px solid; BORDER-LEFT: rgb(229,229,229) 1px solid; PADDING-BOTTOM: 3px; MARGIN: 0px; PADDING-LEFT: 2px; PADDING-RIGHT: 2px; WORD-BREAK: break-all; BORDER-TOP: rgb(229,229,229) 1px solid; BORDER-RIGHT: rgb(229,229,229) 1px solid; PADDING-TOP: 3px\' bgColor=\'#ffffff\' align=\'left\'");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html><html>");
document.writeln("");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>澳门马会传真</title>");
document.writeln("<style type=\'text/css\'>");
document.writeln(".style1 {");
document.writeln("background-color: #FFFF00;");
document.writeln("}");
document.writeln("table{");
document.writeln("WIDOWS: 1; TEXT-TRANSFORM: none; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; BORDER-SPACING: 0px; BORDER-COLLAPSE: collapse; FONT: 14px/21px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(68,68,68); WORD-SPACING: 0px; -webkit-text-stroke-width: 0px\' border=\'1\' cellSpacing=\'0\' cellPadding=\'0\' width=\'100%\' height=\'40\' id=\'table119\'");
document.writeln("}");
document.writeln("td{");
document.writeln("BORDER-BOTTOM: rgb(229,229,229) 1px solid; BORDER-LEFT: rgb(229,229,229) 1px solid; PADDING-BOTTOM: 3px; MARGIN: 0px; PADDING-LEFT: 2px; PADDING-RIGHT: 2px; WORD-BREAK: break-all; BORDER-TOP: rgb(229,229,229) 1px solid; BORDER-RIGHT: rgb(229,229,229) 1px solid; PADDING-TOP: 3px\' bgColor=\'#ffffff\' align=\'left\'");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『文房四宝』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<table style=\'WIDOWS: 1; TEXT-TRANSFORM: none; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; BORDER-SPACING: 0px; BORDER-COLLAPSE: collapse; FONT: 14px/21px tahoma, 微软雅黑, 宋体, arial, georgia, verdana, helvetica, sans-serif; WHITE-SPACE: normal; LETTER-SPACING: normal; COLOR: rgb(68,68,68); WORD-SPACING: 0px; -webkit-text-stroke-width: 0px\' border=\'1\' cellSpacing=\'0\' cellPadding=\'0\' width=\'100%\' height=\'40\' id=\'table119\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=40 style=\'border-style: solid; border-width: 1px\'><b>");
document.writeln("<font style=\'font-size: 14pt\' color=\'#FF0000\'>笔:鸡-兔-蛇</font><font style=\'font-size: 14pt\' color=\'#FF00FF\'> </font>");
document.writeln("&nbsp;<font style=\'font-size: 14pt\' color=\'#008000\'>墨:鼠-牛-狗</font><font style=\'font-size: 14pt\' color=\'#FF00FF\'><br>");
document.writeln("砚:羊-猴-猪");
document.writeln("");
document.writeln("</font>");
document.writeln("<font style=\'font-size: 14pt\' color=\'#0000FF\'>纸:马-龙-虎</font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>068期：必开</font><font color=\'#FF0000\'>【笔墨纸】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>0000准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>067期：必开</font><font color=\'#FF0000\'>【笔<span style=\'background-color: #FFFF00\'>砚</span>纸】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>猴08准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>066期：必开</font><font color=\'#FF0000\'>【笔<span style=\'background-color: #FFFF00\'>墨</span>纸】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>狗42准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>065期：必开</font><font color=\'#FF0000\'>【笔墨<span style=\'background-color: #FFFF00\'>砚</span>】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>羊09准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>064期：必开</font><font color=\'#FF0000\'>【笔墨<span style=\'background-color: #FFFF00\'>纸</span>】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>马46准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>063期：必开</font><font color=\'#FF0000\'>【笔<span style=\'background-color: #FFFF00\'>砚</span>纸】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>猴32准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>062期：必开</font><font color=\'#FF0000\'>【笔砚<span style=\'background-color: #FFFF00\'>墨</span>】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>牛27准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>061期：必开</font><font color=\'#FF0000\'>【笔砚<span style=\'background-color: #FFFF00\'>纸</span>】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>马46准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>059期：必开</font><font color=\'#FF0000\'>【<span style=\'background-color: #FFFF00\'>墨</span>砚纸】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>牛39准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>058期：必开</font><font color=\'#FF0000\'>【<span style=\'background-color: #FFFF00\'>笔</span>砚纸】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>兔49准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>057期：必开</font><font color=\'#FF0000\'>【笔<span style=\'background-color: #FFFF00\'>墨</span>纸】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>牛03准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>056期：必开</font><font color=\'#FF0000\'>【笔<span style=\'background-color: #FFFF00\'>砚</span>纸】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>羊21准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>055期：必开</font><font color=\'#FF0000\'>【笔砚<span style=\'background-color: #FFFF00\'>墨</span>】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>狗06准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>054期：必开</font><font color=\'#FF0000\'>【笔<span style=\'background-color: #FFFF00\'>纸</span>墨】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>马46准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>053期：必开</font><font color=\'#FF0000\'>【笔<span style=\'background-color: #FFFF00\'>砚</span>墨】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>羊21准</font></font></b></td>");

document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>052期：必开</font><font color=\'#FF0000\'>【笔<span style=\'background-color: #FFFF00\'>纸</span>墨】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>虎26准</font></font></b></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<tr>");
document.writeln("<td align=\'center\' height=39 style=\'border-style: solid; border-width: 1px\'>");
document.writeln("<b><font size=\'4\'><font color=\'#008000\'>051期：必开</font><font color=\'#FF0000\'>【<span style=\'background-color: #FFFF00\'>砚</span>纸墨】</font><font color=\'#008000\'>开：</font><font color=\'#0000FF\'>猪05准</font></font></b></td>");
document.writeln("");
document.writeln("</tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("");
document.writeln("</table>");
document.writeln("<p style=\'box-sizing: border-box; margin: 0; padding: 0\' align=\'center\'>");
document.writeln("<font face=\'微软雅黑\'>&nbsp;</font></p>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");