document.writeln("");
document.writeln("");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=gb2312\'>");
document.writeln("<title>新建网页 2</title>");
document.writeln("</head>");
document.writeln("<body><table border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<table style=\'border-collapse:collapse;color:#800000;font-weight:700;border:1px solid #800000\' border=1 width=100%>");
document.writeln("<tbody>");
document.writeln("<tr>");
document.writeln("<td style=\'text-align:center\' height=\'60\'>");
document.writeln("<table border=1 width=100% bgcolor=#ffffff height=\'53\'><tbody>");
document.writeln("<td style=\'border:10px double #800000; height: 47px;\' bgcolor=#800000><p align=center>");
document.writeln("<b><font face=\'楷体\' style=\'font-size: 19pt\'><font color=\'#FFFF00\'>澳门马会传真</font><font color=\'#FFFFFF\'>『一字拆特』</font></font></b></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40 bordercolor=\'#C0C0C0\'>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\'><b><span style=\'box-sizing:border-box; \'><font color=\'#008000\'>");
document.writeln("068期澳门奇人一字玄机：</font><font size=\'5\' color=\'#FF0000\'>【剦】</font></span><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#FF0000\'><br></font>");
document.writeln("</span>");
document.writeln("<span s01虎.tyle=\'box-sizing:border-box; \'><font color=\'#0000FF\'>");
document.writeln("[解]：左下角电字解电肖，马羊蛇；刂解带刀肖，虎蛇兔龙。</font></span><span style=\'box-sizing:border-box; font-size:14pt\'><br><br>");
document.writeln("</span>");
document.writeln("<span style=\'box-sizing:border-box; \'>");
document.writeln("<font color=\'#FF00FF\' size=\'4\'>综合出肖：马羊蛇虎兔龙</font></span></b></font></tr>");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#FFFF00 height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'>澳门马会传真<font color=\'#FF0000\'>67292.com</font></font></span></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40 bordercolor=\'#C0C0C0\'>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\'><b><span style=\'box-sizing:border-box; \'><font color=\'#008000\'>");
document.writeln("066期澳门奇人一字玄机：</font><font size=\'5\' color=\'#FF0000\'>【皙】</font></span><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#FF0000\'><br></font>");
document.writeln("</span>");
document.writeln("<span s01虎.tyle=\'box-sizing:border-box; \'><font color=\'#0000FF\'>");
document.writeln("[解]：左上角木解木肖，虎兔；下部白字解白肖，鼠牛虎鸡狗猪。</font></span><span style=\'box-sizing:border-box; font-size:14pt\'><br><br>");
document.writeln("</span>");
document.writeln("<span style=\'box-sizing:border-box; \'>");
document.writeln("<font color=\'#FF00FF\' size=\'4\'>综合出肖：鼠牛虎鸡<span style=\'background-color: #00FF00\'>狗</span>猪</font></span></b></font></tr>");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#FFFF00 height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'>澳门马会传真<font color=\'#FF0000\'>67292.com</font></font></span></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--开始-->");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#ffffff height=40 bordercolor=\'#C0C0C0\'>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=left>");
document.writeln("<font face=\'微软雅黑\'><b><span style=\'box-sizing:border-box; \'><font color=\'#008000\'>");
document.writeln("065期澳门奇人一字玄机：</font><font size=\'5\' color=\'#FF0000\'>【萩】</font></span><span style=\'box-sizing:border-box; font-size:14pt\'><font color=\'#FF0000\'><br></font>");
document.writeln("</span>");
document.writeln("<span s01虎.tyle=\'box-sizing:border-box; \'><font color=\'#0000FF\'>");
document.writeln("[解]：艹解草肖，牛羊马兔；秋，解秋肖，猴鸡狗。</font></span><span style=\'box-sizing:border-box; font-size:14pt\'><br><br>");
document.writeln("</span>");
document.writeln("<span style=\'box-sizing:border-box; \'>");
document.writeln("<font color=\'#FF00FF\' size=\'4\'>综合出肖：牛<span style=\'background-color: #00FF00\'>羊</span>马兔猴鸡</font></span></b></font></tr>");
document.writeln("<tr>");
document.writeln("<td style=box-sizing:border-box bgcolor=#FFFF00 height=40>");
document.writeln("<p style=box-sizing:border-box;padding:0;margin:0 align=center>");
document.writeln("<font face=\'微软雅黑\'>");
document.writeln("<b><span style=box-sizing:border-box;font-size:14pt>");
document.writeln("<img src=\'/images/yyy123.gif\' style=\'width:20px\' height=\'19\'><span style=box-sizing:border-box;><font color=\'#000000\'>澳门马会传真<font color=\'#FF0000\'>67292.com</font></font></span></span></b><span style=box-sizing:border-box;font-size:14pt><font color=\'#000000\'><span style=\'font-size: 14pt\'></strong>");
document.writeln("</span></font></font>");
document.writeln("</tr>");
document.writeln("<!--结束-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</tbody>");
document.writeln("");
document.writeln("</table>");
document.writeln("<p style=\'box-sizing: border-box; margin: 0; padding: 0\' align=\'center\'>");
document.writeln("<font face=\'微软雅黑\' style=\'font-size: 14pt\'>&nbsp;</font></p>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");