# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update application

on:
  workflow_dispatch:
  repository_dispatch:
    types: [webhook]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Download and update
      run: |
        python ./Script/Download.py
        
    - name: Push
      run: |
        git pull origin main
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./aomen

        git commit -m "$(date '+%Y.%m.%d %H:%M:%S') Today update" || true
        git push origin main || true
