# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [webhook]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade requests
        pip install aiohttp aiofiles
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    
    - name: Download 
      run: |
        python ./Script/Download.py
        python ./Script/DJS.py
        
    - name: Push
      run: |
        git pull origin main
        git config --global user.name "Rokate"
        git config --global user.email "77772464+Rokate@users.noreply.github.com"
        git add ./Script
        git commit -m "Update:  $(date '+%Y.%m.%d %H:%M:%S')" || true
        git push origin main || true
